### ISSUE TITLE
hello Cannot specify sharding when creating index?

### ISSUE THREAD

**Issue by zdwork** [elastic/go-elasticsearch#102]
hello Cannot specify sharding when creating index?

**Comment by karmi** [comment]
Pass the index settings/mappings as na `io.Reader` to the [Indices.Create()](https://godoc.org/github.com/elastic/go-elasticsearch/esapi#IndicesCreate) method.

**Comment by zdwork** [comment]
I am a novice can a case ? 谢谢

**Comment by zdwork** [comment]
I used the 7.x version

**Comment by zdwork** [comment]
res, err := client.Indices.Create("test-0",)
	if err != nil {
		log.Printf("Malformed response to create index: %s", err)

	}
	if res.IsError() {
		log.Printf("Cannot create index: %s", res)
		return
	}
	log.Print("Successfully created index")

**Comment by zdwork** [comment]
Can you help me?
