### ISSUE TITLE
connect go-elasticsearch

### ISSUE THREAD

**Issue by ZP-AlwaysWin** [elastic/go-elasticsearch#103]
Can I connect to es by encrypting the key file？
It's not too safe to connect directly through user name & password, after all, it's clear text

**Comment by karmi** [comment]
Hey, I think I need more information about what are you asking about? What is "encrypting a key file". If you want to use TLS, there's an example in the documentation how to do that, using the Go standard library packages.

**Comment by ZP-AlwaysWin** [comment]
> Hey, I think I need more information about what are you asking about? What is "encrypting a key file". If you want to use TLS, there's an example in the documentation how to do that, using the Go standard library packages.

hi @karmi 

Thanks your review, Now I connect to elasticsearch only to use username&password to authenticate，but username&password usually in plain text, exposed to the outside, very unsafe.
so I want to know is there a way to use the key file for authentication.

**Comment by niaiwomattt** [comment]
Is `go-elasticsearch` working with RestApi?  Or other ？

**Comment by karmi** [comment]
Hey, I'm afraid I still don't understand your question. When you connect to Elasticsearch over TLS (https://), you're not sending the credentials "exposed".

Apart from username/password authentication, Elasticsearch supports the [API key authentication](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html), which the Go client supports.

**Comment by niaiwomattt** [comment]
> > Hey, I think I need more information about what are you asking about? What is "encrypting a key file". If you want to use TLS, there's an example in the documentation how to do that, using the Go standard library packages.
> 
> hi @karmi
> 
> Thanks your review, Now I connect to elasticsearch only to use username&password to authenticate，but username&password usually in plain text, exposed to the outside, very unsafe.
> so I want to know is there a way to use the key file for authentication.

ssh is not，ssl/tls is yes

**Comment by karmi** [comment]
I'm afraid I can't be of much help with the limited information. Can you please rephrase your question?
