### ISSUE TITLE
Index patterns: cannot use asterisk as part of the index name

### ISSUE THREAD

**Issue by unmultimedio** [elastic/go-elasticsearch#105]
# Issue

When using an asterisk as part of the index name like: `some-events-*` to match different indexes like:
```
some-events-foo
some-events-bar
some-events-20191118
```
the url encodes the `*`

Sample code:
```
esIndexName := "some=events-*"
esResp, err := c.ESClient.Search(
  c.ESClient.Search.WithContext(ctx),
  c.ESClient.Search.WithIndex("some-events-*"),
  c.ESClient.Search.WithBody(&buf),
  c.ESClient.Search.WithErrorTrace(),
)
if err != nil {
  // Not err
}
defer esResp.Body.Close()
if esResp.IsError() {
  // It's a 403 like:
  // [403 Forbidden] <html><body><h1>403 Forbidden</h1>\nRequest forbidden by administrative rules.\n</body></html>\n
  return fmt.Errorf("%s", esResp.String())
}
```

And I can see the logs in Elastic like:
```
Timestamp ... 200 ... "GET /some-events-%2A/_search?error_trace=true HTTP/1.1"
```

# Expected
```
Timestamp ... 200 ... "GET /some-events-*/_search?error_trace=true HTTP/1.1"
```

# Root cause
- Index name gets appended here: https://github.com/elastic/go-elasticsearch/blob/v7.4.1/esapi/api.search.go#L112
- Request is formed here https://github.com/elastic/go-elasticsearch/blob/v7.4.1/esapi/api.search.go#L307
- Path is parsed here: https://github.com/elastic/go-elasticsearch/blob/v7.4.1/esapi/esapi.request.go#L36

Behavior: https://play.golang.org/p/zhxBAT5hHUc

# Additional info
- Version from `go.mod`: `github.com/elastic/go-elasticsearch/v7 v7.4.1`
- Golang URL Parser: https://stackoverflow.com/a/13821803/1755300

**Comment by karmi** [comment]
Hello, the URL parameter handling is a bit more subtle, due to the behaviour of Go's stdlib, where a slash character (`/`) has to be encoded manually. Any other character should be properly encoded by the library.

I've prepared the following example, can you run it? It behaves correctly on my end.

```golang
//+build ignore

package main

import (
	"log"
	"os"
	"strings"

	"github.com/elastic/go-elasticsearch/v8"
	"github.com/elastic/go-elasticsearch/v8/estransport"
)

func main() {
	log.SetFlags(0)

	cfg := elasticsearch.Config{
		Logger: &estransport.ColorLogger{Output: os.Stdout},
	}
	es, err := elasticsearch.NewClient(cfg)

	if err != nil {
		log.Fatalf("Error creating the client: %s", err)
	}

	es.Index(
		"test",
		strings.NewReader(`{"foo":"bar"}`),
		es.Index.WithDocumentID("fôô"),
		es.Index.WithRefresh("true"))

	res, _ := es.Search(
		es.Search.WithIndex("t*"),
		es.Search.WithPretty())

	log.Println(res)
}
```

**Comment by unmultimedio** [comment]
@karmi your sample works:
```
➜  go run ./test/test_elastic.go 
   PUT http://localhost:9200/test/_doc/fôô?refresh=true 201 Created 458ms
   GET http://localhost:9200/t*/_search?pretty=true 200 OK 59ms
[200 OK] {some json}
```
Are those `PUT|GET` logs part of the v8 library?

What do you suggest? Waiting for `v8` to come out as official release? I'm currently on `v7.4.1`

**Comment by karmi** [comment]
It should behave exactly the same on 7 as on master... (Version 8 will be available only when the Elastic Stack as whole is released.)

I did try against the `v7.x` branch, and it works correctly, see the code below.

I also checked the commits between 7.x and 7.4.1, and it doesn't look like there's a related change in there... (`git log --oneline 7.x --not v7.4.1`)

```golang
//+build ignore

package main

import (
	"log"
	"os"
	"strings"

	"github.com/elastic/go-elasticsearch/v7"
	"github.com/elastic/go-elasticsearch/v7/estransport"
)

func main() {
	log.SetFlags(0)

	log.Println("go-elasticsearch", elasticsearch.Version)
	log.Println(strings.Repeat("-", 80))

	cfg := elasticsearch.Config{
		Logger: &estransport.ColorLogger{Output: os.Stdout},
	}
	es, err := elasticsearch.NewClient(cfg)

	if err != nil {
		log.Fatalf("Error creating the client: %s", err)
	}

	es.Index(
		"test",
		strings.NewReader(`{"foo":"bar"}`),
		es.Index.WithDocumentID("fôô"),
		es.Index.WithRefresh("true"))

	res, _ := es.Search(
		es.Search.WithIndex("t*"),
		es.Search.WithPretty())

	log.Println(res)
}
```

**Comment by karmi** [comment]
(The logging is part of the library, check the example at https://github.com/elastic/go-elasticsearch/blob/master/_examples/logging/default.go)

**Comment by unmultimedio** [comment]
Thanks!!, I've run it also with the logger on, locally on my machine and I can see the `index-pattern-*` in the URL, so I assume it should be an issue elsewhere. Feel free to close this 👍

**Comment by karmi** [comment]
Great! Please reopen or open a new issue if you run into problems.

**Comment by unmultimedio** [comment]
Sorry, I kept testing and checked the logger in deep, and still found issues.

It really depends on the logger. `Color`, `Curl` and `JSON` loggers use `req.URL.Path` which logs `*`, but `Text` logger uses `req.URL.String()` which logs `%2A`.

So since really the loggers couldn't be trusted, I used a request catcher to see how those requests were really arriving:

TextLogger:
```
2019-11-19T16:04:14Z GET http://test.requestcatcher.com:80/some-index-%2A/_search?error_trace=true [status:301 request:399ms]
```

RequestCatcher:
```
GET /some-index-%2A/_search?error_trace=true HTTP/1.1
Host: test.requestcatcher.com:80
Accept-Encoding: gzip
Content-Length: 633
Content-Type: application/json
User-Agent: go-elasticsearch/7.4.1 (darwin amd64; Go 1.12.7)
```

Try it with `Addresses` pointing to a local server or a service like RequestCatcher and check please how those requests are arriving.

https://play.golang.org/p/lZcD7srDB0i

**Comment by karmi** [comment]
Logging format aside, the important part is that with the code I've posted, I'm getting results from the index... It's the same as running `curl http://localhost:9200/t%2A/_search?pretty`.

**Comment by unmultimedio** [comment]
Yes, seems to be elastic is able to handle both:
```
curl http://localhost:9200/t*/_search?pretty
curl http://localhost:9200/t%2A/_search?pretty
```
and return successful results.

I guess the bottom question is, Should the library (or not) encode the `*` in the request path?

**Comment by karmi** [comment]
Yes, the library should definitely encode URL parameters. As I've indicated in my first comment, the exception is the `/` character, which has to be manually encoded in the calling code.

**Comment by unmultimedio** [comment]
I think there should be a way to allow certain characters in the index part of the path. For example, Java or JS url encode doesn't encode the `*` and the requests go out like `localhost:9200/some-index-*/_search`. Do you know if there's such a way to send a _raw_ index pattern?

**Comment by karmi** [comment]
> Do you know if there's such a way to send a raw index pattern?

I think we have to return to your original question/concern. The crucial thing is that the code I've posted returns correct results. I don't understand why you would need to send a "raw" index pattern. Can you clarify, please?

**Comment by unmultimedio** [comment]
Sure, I understand the code you posted returns correct results, and that's because elasticsearch server is able to handle indexes in the URL both `like-this-*` and `like-this-%2A`.

We've established the library does the requests `like-this-%2A`. My question now would be, is there a way to force the library to do requests with URL indexes `like-this-*`?

**Comment by karmi** [comment]
> My question now would be, is there a way to force the library to do requests with URL indexes like-this-*

I'm sorry, but I don't really understand why would you want to do that?

**Comment by unmultimedio** [comment]
It can be a small detail, but it makes the server logs more readable and also allows us to put controls in place for more restrictive URLs that explicitly use static index names or allowed index patterns.

**Comment by Anaethelion** [comment]
Closing as this issue has been answered already.
