### ISSUE TITLE
elastic/go-elasticsearch vs olivere/elastic

### ISSUE THREAD

**Issue by harishanumula** [elastic/go-elasticsearch#107]
I am using Elasticsearch 7.x, I am fairly new to Go, I want to migrate away from python to go and hence would need an Elasticsearch Data Access Layer. I was wondering what the differences were between the official client and olivere/elastic, and which once is better for the long term. I see that olivere/elastic has more stars and more activity, but that may be due to the first-movers advantage.

**Comment by LuckyWindsck** [comment]
I saw your issues in the `olivere/elastic`.
Let me put a link here for more information.

https://github.com/olivere/elastic/issues/1240
