### ISSUE TITLE
where can it set the cluster name for 6.x ?

### ISSUE THREAD

**Issue by apple0407** [elastic/go-elasticsearch#108]
when i do a search using client.Search(), i get the error "no handler found for uri xxxx"
my es cluster name is not elasticsearch , so i think this may be the problem. 
But where can i configure the cluster name ? which api can i use ?
any help , thanks !

**Comment by karmi** [comment]
Not sure why you would get such an error, and cluster name is really not important for the Search API. Can you run the https://github.com/elastic/go-elasticsearch/blob/6.x/_examples/main.go example and see how that works for you?

**Comment by apple0407** [comment]
i run this code:
![image](https://user-images.githubusercontent.com/10057216/69423807-19db9b00-0d62-11ea-98b4-aed217979cf7.png)
and console log is: 
![image](https://user-images.githubusercontent.com/10057216/69423847-2fe95b80-0d62-11ea-8a22-7e32311fe1e9.png)
can't figure out what cause this, i just follow the example code .

**Comment by karmi** [comment]
From the ES error it looks like you're not passing a document type to some of the APIs. But it's hard to say without the complete code.

**Comment by apple0407** [comment]
fix it .  it's because of my network proxy, i shutdown the proxy and the problem gone .
Thanks anyway @karmi
