### ISSUE TITLE
CreateRequest struct doesn't allow for not specifying DocumentID

### ISSUE THREAD

**Issue by heshamnaim** [elastic/go-elasticsearch#110]
https://github.com/elastic/go-elasticsearch/blob/master/esapi/api.create.go#L81 there is no check to see if DocumentID is left blank for auto generating.

**Comment by karmi** [comment]
Hello, can you please elaborate? It's hard to understand what is the actual problem or issue you're describing.

**Comment by heshamnaim** [comment]
esapi CreateRequest requires that the DocumentID be specified. However the elasticsearch documentation mentions that if the DocumentID is not specified it will be auto generated

**Comment by karmi** [comment]
The "Create" API expects you to pass a document ID — if you want to have the ID auto-generated by Elasticsearch, you need to use the "Index" API:

```golang
res, err := es.Index("test", strings.NewReader(`{"foo":"bar"}`))
fmt.Println(res, err)
// [201 Created] {"_index":"test","_id":"Mvq2ym4BvGLaerir28I5","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1} <nil>
```
