### ISSUE TITLE
_example  so simple and confusing 

### ISSUE THREAD

**Issue by wuxiaoxiaoshen** [elastic/go-elasticsearch#116]
i am confused about the _example， and hard to use this package.  so, how about more example?

**Comment by karmi** [comment]
Hello, can you point out the specific example which is confusing (there are many of them in the `_examples` folder), and what is specifically confusing about it?

**Comment by Emixam23** [comment]
Hey!

Tbh I am kinda stuck on the readme example (as for me)

I don't get how does the search work..  I have inserted 3 documents (_id, name, pseudo) but I can't find the way to query for a partial search 

3 docs like this got indexed : {_id:a1, name: max23, pseudo: Emixam23}

However, I would like to now have results for when I am looking for either  a name or a pseudo..
Good thing is that pseudo is unique, but name can be similar accross different documents

thanks!

**Comment by karmi** [comment]
Hello — I'm afraid I don't understand what are you referring to as a "partial match".

The package allows to pass a search definition as the request body, eg. in the example:

https://github.com/elastic/go-elasticsearch/blob/e9eb76d55d12256a0777ad825bf25cd5e02fa105/_examples/main.go#L113-L123

It is of course possible to use a different query in the definition, but that's more about general Elasticsearch usage than the Go package...

**Comment by Emixam23** [comment]
Hi,

Yes that's what I finally understood :) I was kinda lost about it (the query approach of elastic search) but I get it now :)

thanks!
