### ISSUE TITLE
I have imported the elasticsearch package,but occured the issue.

### ISSUE THREAD

**Issue by hubo123** [elastic/go-elasticsearch#117]
index2.go content:
import (
	"log"
	"github.com/elastic/go-elasticsearch/v8/esapi"
    	"github.com/elastic/go-elasticsearch/v8/estransport"
    	"github.com/elastic/go-elasticsearch/v8/internal/version"
	
)

func main() {
	es,_:=elasticsearch.NewDefaultClient()
	log.Println(elasticsearch.Version)
	log.Println(es.Info())
}

index2.go:5:2: cannot find package "github.com/elastic/go-elasticsearch/v8/esapi" in any of:
        D:\install\Go\src\github.com\elastic\go-elasticsearch\v8\esapi (from $GOROOT)
        C:\Users\Bush\go\src\github.com\elastic\go-elasticsearch\v8\esapi (from $GOPATH)
index2.go:6:6: cannot find package "github.com/elastic/go-elasticsearch/v8/estransport" in any of:
        D:\install\Go\src\github.com\elastic\go-elasticsearch\v8\estransport (from $GOROOT)
        C:\Users\Bush\go\src\github.com\elastic\go-elasticsearch\v8\estransport (from $GOPATH)
index2.go:7:6: cannot find package "github.com/elastic/go-elasticsearch/v8/internal/version" in any of:
        D:\install\Go\src\github.com\elastic\go-elasticsearch\v8\internal\version (from $GOROOT)
        C:\Users\Bush\go\src\github.com\elastic\go-elasticsearch\v8\internal\version (from $GOPATH)

**Comment by karmi** [comment]
Hello. How did you install the package? Are you using `go.mod`?

---

The `github.com/elastic/go-elasticsearch/v8/internal/version` is internal, you shouldn't import it.

**Comment by karmi** [comment]
Hey, any news here?
