### ISSUE TITLE
[feature request] Export res.Body details

### ISSUE THREAD

**Issue by eslam-mahmoud** [elastic/go-elasticsearch#124]
Hello,

I had an issue with a req that was returning `[400 bad request]`
spend a lot of time around it but finally, find the root cause when I did `fmt.Println(res)` (maybe I should start with that)
```
{
  "error": {
    "root_cause": [
      {
        "type": "invalid_index_name_exception",
        "reason": "Invalid index name [Card], must be lowercase",
        "index_uuid": "_na_",
        "index": "Card"
      }
    ],
    "type": "invalid_index_name_exception",
    "reason": "Invalid index name [Card], must be lowercase",
    "index_uuid": "_na_",
    "index": "Card"
  },
  "status": 400
}
```
then i had to unmarchal the body and create custom type and var
I hope to have the Reason exported on the `responce` so it could be wrapped into an error

**Comment by karmi** [comment]
Hello! I don't see the calling code, but usually, what I do is to call `res.IsError()`, and if that's true, either parse the response, or just call `res.String()`, which does that automatically. See this part of the main example:

https://github.com/elastic/go-elasticsearch/blob/5398a82b748f62db8eb34d37afbf0f95b7356176/_examples/main.go#L138-L150

With that said, I definitely agree that something like `(*esapi.Response).ParsedError()` would be very convenient, and it's on my todo list. See https://github.com/elastic/go-elasticsearch/pull/73 for a discussion about this topic.

**Comment by eslam-mahmoud** [comment]
> With that said, I definitely agree that something like (*esapi.Response).ParsedError() would be very convenient

Yes exactly 
```go
if res.IsError() {
		type resReason struct {
			Reason string `json:"reason"`
		}
		var resBody struct {
			Err resReason `json:"error"`
		}

		b, err := ioutil.ReadAll(res.Body)
		if err != nil {
			// do something
		}
		err = json.Unmarshal(b, &resBody)
		if err != nil {
			// do something
		}

		// Use this resBody.Err.Reason
}
```
This is what I do to get to the reason
I see #73 covering my issue, this can be closed
