### ISSUE TITLE
Highlight option in Search

### ISSUE THREAD

**Issue by tansawit** [elastic/go-elasticsearch#129]
Hi. I've been trying to find out how to enable highlighting when getting search results but could not seem to find it in either the elasticsearch.go or esapi folder. Please let me know if I've looked over something. Thanks!

**Comment by karmi** [comment]
Hello! Highlighting is done by passing the corresponding configuration in the search definition, ie. in the search body — there's no method or something like that on the Search API.

Have a look in the "XKCD" example, which has a comprehensive demo of returning, parsing, and displaying highlights:

https://github.com/elastic/go-elasticsearch/blob/ca32bbd4b9860afbb832ebbaa9149a50740e9f9a/_examples/xkcdsearch/store.go#L184-L188

**Comment by tansawit** [comment]
Thank you for such a quick reply! Will be sure to look into it.
