### ISSUE TITLE
_alias API is missing

### ISSUE THREAD

**Issue by arigon** [elastic/go-elasticsearch#130]
Is the _alias API missing or am I unable to find it? As a workaround I can use the _cat/aliases API, but it doesn't provide a JSON response.

**Comment by karmi** [comment]
See [`esapi.Indices.GetAlias`](https://pkg.go.dev/github.com/elastic/go-elasticsearch/v7/esapi?tab=doc#IndicesGetAlias) and related methods.

Also, all Cat APIs can return JSON, try this:

```
curl 'http://localhost:9200/_cat/aliases?format=json'
```
