### ISSUE TITLE
Checking if an index exists

### ISSUE THREAD

**Issue by denisvmedia** [elastic/go-elasticsearch#133]
I spent some time on searching info on how I can check if an [index exists](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-exists.html), but failed.  If it's possible with the current library state, could you please show me an example? If not, can we add it?

**Comment by denisvmedia** [comment]
I was blind. I was looking for something like "index exists", but it turned out to be `IndicesExists` :)

**Comment by idanoo** [comment]
@perlhub here is what I'm using at the moment. Then I'm just checking if resp.StatusCode == 404

```
	client, err := elasticsearch.NewDefaultClient()
	if err != nil {
		log.Fatal(err)
	}

	resp, err := esapi.IndicesExistsRequest{
		Index: []string{"test-index"},
	}.Do(context.Background(), es)

	if err != nil {
		log.Fatal(err)
	}
```
