### ISSUE TITLE
type *http.Transport has no field or method Clone

### ISSUE THREAD

**Issue by struce** [elastic/go-elasticsearch#134]
On 6.x， **error message**: go-elasticsearch/estransport/estransport.go:118:32: httpTransport.Clone undefined (type *http.Transport has no field or method Clone)

Install command: `git clone --branch 6.x https://github.com/elastic/go-elasticsearch.git $GOPATH/src/github.com/elastic/go-elasticsearch`

**Comment by karmi** [comment]
Hello, what version of Go are you using? AFAIK it's available since Go 1.13.

**Comment by struce** [comment]
Go version: `go version go1.12.7 linux/amd64`.
i see `httpTransport.Clone` added in last version.
so I used tag v6.8.2, is ok，thanks.

**Comment by karmi** [comment]
Yes, it is related to the new configuration option for custom certificate authorities. I'll increase the Go version in `go.mod` to properly set the requirement.
