### ISSUE TITLE
Always hits / 

### ISSUE THREAD

**Issue by pkutishch** [elastic/go-elasticsearch#14]
`func elast() error {
    api := snapshot.New(transport.New())
	snap, err := api.GetRepository()
	if err != nil {
		return err
	}
	defer snap.Response.Body.Close()
	body, err := ioutil.ReadAll(snap.Response.Body)
        if err != nil {
                return err
        }
	fmt.Println(string(body))
	return nil
}`
always returns 
`{
  "name" : "nV2Q0j1",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "ng6xB6B5T_e8oZpxhcw6mQ",
  "version" : {
    "number" : "5.6.11",
    "build_hash" : "bc3eef4",
    "build_date" : "2018-08-16T15:25:17.293Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
`
Expected result
`
{
  "elastic": {
    "type": "fs",
    "settings": {
      "compress": "true",
      "location": "/mnt/elastic"
    }
  }
}`

**Comment by 7AC** [comment]
Probably part of the pending items in https://github.com/elastic/go-elasticsearch/issues/5

**Comment by karmi** [comment]
Hello, the project has been replaced today by a new codebase — I'll close this issue if it's OK?
