### ISSUE TITLE
Bulk insert

### ISSUE THREAD

**Issue by mporracindie** [elastic/go-elasticsearch#140]
Hi,

I would like to know if is there any examples of bulk inserts using go-elasticsearch.
I'm not being able to find the right methods. 

Regards.

**Comment by karmi** [comment]
Hello,

see the Bulk API implementation in [`esapi/api.bulk.go`](https://github.com/elastic/go-elasticsearch/blob/master/esapi/api.bulk.go) for the base API, and the recently added [`esutil.BulkIndexer`](https://github.com/elastic/go-elasticsearch/blob/master/esutil/bulk_indexer.go) helper.

There are comprehensive examples for both in [`_examples/bulk`](https://github.com/elastic/go-elasticsearch/tree/master/_examples/bulk).

**Comment by mporracindie** [comment]
@karmi Thank you very much for the information. 
Do you happen to know if it's possible to bulk index to multiple indexes on the same call?

**Comment by karmi** [comment]
Yes it is — just set the `index` property for the individual operation.
