### ISSUE TITLE
Getting error "read on closed response body" when trying to delete doc that does not exist

### ISSUE THREAD

**Issue by eslam-mahmoud** [elastic/go-elasticsearch#141]
ex:
```go
	req := esapi.DeleteRequest{
		Index:   indexName,
		DocumentID: doc.DocID(), //404 ID
	}
	res, err := req.Do(ctx, es.esClient)
	if err != nil {
		return err
	}
	// read the entire body so that the connection can be re-used
	_, _ = io.Copy(ioutil.Discard, res.Body) // does not return error
	res.Body.Close()

	if res.IsError() {
		es.logger.Log(
			"message", "could not delete index",
			"id", doc.DocID(),
			"index", indexName,
			"error", res.String(), // error reading response body: http: read on closed response body
			"status", res.Status(), // 404
			"severity", "DEBUG",
		)
	}

	return nil
```
when I execute this code I get error ` error reading response body: http: read on closed response `

if we check `if res.IsError()` before the copy/close it still returns true but with different message `[404 Not Found]`, after the `res.Body.Close()` the message change to `read on closed response body`

**Comment by karmi** [comment]
Hello, sorry for not getting to you sooner.

When you discard the body and close it, it is expected that the subsequent call to `res.String()` fails, because it actually tries to read a closed body. I think it's perhaps better to add the discard and close into a `defer` statement in your case?

**Comment by karmi** [comment]
Hello, should we close this issue?

**Comment by eslam-mahmoud** [comment]
Yes thanks
