### ISSUE TITLE
Support for voting configuration exclusions API

### ISSUE THREAD

**Issue by kamolhasan** [elastic/go-elasticsearch#144]
I'm using go-elasticsearch `7.x` branch.

I need to perform both `POST` and `DELETE` requests using `/_cluster/voting_config_exclusions` API endpoint.

```
POST /_cluster/voting_config_exclusions/nodeId1

DELETE /_cluster/voting_config_exclusions
```

But I didn't find any implementation of `voting_configuration_exclusions` API in Cluster APIs:

```go
type Cluster struct {
	AllocationExplain       ClusterAllocationExplain
	DeleteComponentTemplate ClusterDeleteComponentTemplate
	ExistsComponentTemplate ClusterExistsComponentTemplate
	GetComponentTemplate    ClusterGetComponentTemplate
	GetSettings             ClusterGetSettings
	Health                  ClusterHealth
	PendingTasks            ClusterPendingTasks
	PutComponentTemplate    ClusterPutComponentTemplate
	PutSettings             ClusterPutSettings
	RemoteInfo              ClusterRemoteInfo
	Reroute                 ClusterReroute
	State                   ClusterState
	Stats                   ClusterStats
}
```

Can you guide a way out by telling how can I perform these requests using go-elasticsearch?

**Comment by karmi** [comment]
It seems like the API is missing from the [specification](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/main/resources/rest-api-spec/api). I'll have a look into that.

In the meantime, if you want to unblock your situation quickly, you can use the guidelines for extending the client:

https://github.com/elastic/go-elasticsearch/blob/6f36a473b19f05f20933da8f59347b308ab46594/_examples/extension/main.go#L29-L51

**Comment by karmi** [comment]
So, there's an ongoing work on revisiting the API, and adding the specification when it's completed. No timeline for that yet, so if you need it badly now, the extension approach should work well.

**Comment by kamolhasan** [comment]
Thanks, @karmi!

**Comment by karmi** [comment]
Hello, the support for the API has been added to the `master` branch in https://github.com/elastic/go-elasticsearch/commit/76a7f0b6ec401c8c61f0646c69958eb5fe85b924, and to the `7.x` branch in https://github.com/elastic/go-elasticsearch/commit/9a4447ee944f9c59e49d698116a8043ea5ec8b77. Can you try it out?
