### ISSUE TITLE
Is it possible to use go-elasticsearch with dep?

### ISSUE THREAD

**Issue by robertjli** [elastic/go-elasticsearch#145]
I'm working on a project that is proving difficult to migrate to go modules - is it possible to use this client with dep?

**Comment by karmi** [comment]
Hi! At some point, I've experimented how to make the package work with Govendor, and it _was_ possible, although it did require a lot of acrobatics... Here's the working code from the time: https://gist.github.com/karmi/52fe8086128dea4a931e9d911530d532

I'm not 100% sure about `dep`, but I assume it is based on the `vendor` directory? If so, similar acrobatics might make it happy?

**Comment by robertjli** [comment]
Great, thank you so much for the info! Closing the issue.
