### ISSUE TITLE
How to use the 7.7 branch?

### ISSUE THREAD

**Issue by moon-bits** [elastic/go-elasticsearch#148]
I would like to use the BulkIndexer that is only available in the masters and 7.7 branch.

Yet, adding the following to my _go.mod_:
`
require (
	github.com/elastic/go-elasticsearch/v7 7.7
)
`
gets immediately replaced by the following
`require (
	github.com/elastic/go-elasticsearch/v7 v7.5.1-0.20200429062015-7feb806067e
)`

The same applies to when I run the command:
`
go get github.com/elastic/go-elasticsearch/v7@7.7
`
`
go: github.com/elastic/go-elasticsearch/v7 7.7 => v7.5.1-0.20200429062015-7feb806067ec
`

Is the 7.7 branch not stable to use for production or is it more like a technical preview for v8?

Any help is appreciated!

Thanks in advance!

**Comment by karmi** [comment]
Hello, seems like Go has somewhat surprising resolution from branches to versions... I can confirm the replacement, but the following works for me:

```
// go.mod
module example.com/go-elasticsearch-7.7

go 1.14

require github.com/elastic/go-elasticsearch/v7 7.7
```

```
// main.go
package main

import (
	"fmt"

	"github.com/elastic/go-elasticsearch/v7"
	"github.com/elastic/go-elasticsearch/v7/esutil"
)

func main() {
	fmt.Println("version:", elasticsearch.Version)
	fmt.Printf("indexer: %+v\n", esutil.BulkIndexerConfig{})
}

```

Ie., it prints the correct version, `7.7.0`, and it knows about the `esutil.BulkIndexerConfig` type.

The `7.7` branch is intented as a pre-release for the upcoming `7.7.0` version of the stack.

The `v7.5.1` seems to be misleading, because the commit 7feb806067ec references a last commit on the 7.7 branch...

**Comment by moon-bits** [comment]
Indeed, it works. Thanks!

I was confused by the IDE that showed me it cannot find the BulkIndexer and the version number of v7.5.1.

Apparently, the BulkIndexer API is not compatible with the Elastic stack v7.6.2, as no indices are created. Pity!

Thanks anyways @karmi !

**Comment by moon-bits** [comment]
Nevermind. I had a typo inside the **_Action_** field. It works.

Thanks again @karmi !

**Comment by karmi** [comment]
> Apparently, the BulkIndexer API is not compatible with the Elastic stack v7.6.2, as no indices are created. Pity!

That would be pretty weird — it wraps the Bulk API, which should be compatible. If you turn on the logger (see `_examples/logging`), it should print the details.
