### ISSUE TITLE
Add new constructor with custom http.Client to create new Client

### ISSUE THREAD

**Issue by kvch** [elastic/go-elasticsearch#149]
We would like to adopt this lib to interact with Elasticsearch in Beats. The current implementation in Beats requires a configurable `http.Client`-like option/parameter to support Kerberos authentication.

I've seen that one can configure `http.Transport`. However, according to the documentation of Golang, it is a lower-level primitive. So to comply with that we need to pass a custom `http.Client` to the ES client.

I was thinking about the following signature for the new constructor:

```golang
func NewCustomClient(httpClient eshttp.Client, cfg Config) (*Client, error)
```

where `eshttp.Client` is an interface with the same function as `http.Client`.

What do you think? After we agreed on the functionality, I am happy to open a PR with the required changes.

CC @ycombinator

**Comment by karmi** [comment]
Hi @kvch, thanks for opening the issue.

In fact, in the initial design phase, we have decided to _not_ use `http.Client` as the transport component, but the lower-level `http.Transport`. One of the reasons is actually the "high-level" features — cookies, redirects — of [`http.Client`](https://golang.org/pkg/net/http/#Client) which won't fit well with the Elasticsearch client:

> A Client is higher-level than a RoundTripper (such as Transport) and additionally handles HTTP details such as cookies and redirects.

Threfore, the client accepts the `http.RoundTripper` interface for the `Transport` in `Config`.

The transport component of the client itself, `elasticsearch.Client.Transport` is actually a different interface `estransport.Interface`:

https://github.com/elastic/go-elasticsearch/blob/e9eb76d55d12256a0777ad825bf25cd5e02fa105/estransport/estransport.go#L45-L47

Underneath, `estransport.Client` uses `http.RoundTripper` again.

With all that in mind, the package allows for multiple ways of customizing the transport-related features. And nothing prevents you to implement a lightweight wrapper around `http.Client`, which would implement the `http.RoundTripper` interface. In fact, there's an example of just that in one of the integration tests:

https://github.com/elastic/go-elasticsearch/blob/e9eb76d55d12256a0777ad825bf25cd5e02fa105/elasticsearch_integration_test.go#L154-L184

Would this work for your use case?

-----

To answer your question about adding a `NewCustomClient()` function, I don't think it's the best solution here, for many reasons. It extends the API surface for something better served with a lightweight wrapper as a custom transport component — something I try to promote heavily to all package users.

**Comment by kvch** [comment]
It is something which can be implemented. However, `http.Transport` was not intended to handle authentication. I see your point and I understand that the Go documentation is not some divine scripture we need to follow all the time. We will solve the problem with the interface you provide.
Thank you for your time.
