### ISSUE TITLE
Work in Progress?

### ISSUE THREAD

**Issue by amatai** [elastic/go-elasticsearch#15]
This seems to be WIP for last year. Is there some deadline on when it will be ready for production use?

**Comment by tsg** [comment]
Sorry for the radio silence on this. The development got stalled but we have concrete plans to reboot the development process on this in October. Still, it will be at least a few more months until the client will be in a usable state.

**Comment by karmi** [comment]
Hello, the new client has been made publicly available today — sorry for the long silence, again!
