### ISSUE TITLE
Update example

### ISSUE THREAD

**Issue by Emixam23** [elastic/go-elasticsearch#150]
Hi,

As far as I could use your package, I was able to insert a document (with two fields, one unique, one that can be anything)

Now, I would like to update these fields, how can I do? On internet I saw stuff about a script but I don't really get it..

my struct:

```
type User struct {
	Id   string `json:"id,omitempty"`
	Pseudo string ` json:"pseudo,omitempty"`
	FullName string `json:"full_name,omitempty"`
}
```

As for now, I have the following code:

```
const indexUsers = "users"

type ESUtils struct {
    client *elasticsearch.Client
}

func (es *ESUtils) UpdateUsername(userId, username string) error {

	var buf bytes.Buffer
	queryMap := map[string]interface{}{
		// ?????????????
	}
	if err := json.NewEncoder(&buf).Encode(queryMap); err != nil {
		log.Fatalf("Error encoding query: %s", err)
	}
	// Perform the update request.
	res, err := es.client.Update(
		indexUsers,
		userId,
		&buf,
		es.client.Update.WithPretty())
	if err != nil {
		log.Fatalf("Error getting response: %s", err)
	}
	defer res.Body.Close()

	if res.IsError() {
		log.Printf("[%s] Error indexing document ID=%s", res.Status(), userId)
	} else {
		// Deserialize the response into a map.
		var r map[string]interface{}
		if err := json.NewDecoder(res.Body).Decode(&r); err != nil {
			log.Printf("Error parsing the response body: %s", err)
		} else {
			// Print the response status and indexed document version.
			log.Printf("[%s] %s; version=%d", res.Status(), r["result"], int(r["_version"].(float64)))
		}
	}

	return nil
}
```

Thanks for any help

**Comment by karmi** [comment]
I think that it would be best if you would first familiarise yourself with the Elasticsearch APIs and concepts first, before diving into the Go integration.

There's good overview at the Elastic website at https://www.elastic.co/guide/en/elasticsearch/reference/master/getting-started-index.html — note that you can switch the language of examples to Go, and you can copy & paste the code from there.

There's also a "Getting started" video available at https://www.elastic.co/webinars/getting-started-elasticsearch, which I highly advise to watch.

Regarding your question about using the "Update" API, it all depends on what you want to achieve (update a single field in the document, add an entry to a list of tags, increase a counter, ...) If you look at the corresponding page in the documentation: https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-update.html, you can switch the language of examples to Go, so you have something readymade to try out.
