### ISSUE TITLE
slice scroll parallel support

### ISSUE THREAD

**Issue by hackerwin7** [elastic/go-elasticsearch#154]
Is there any support for slice scroll in parallel?
#44 and  #142 is simple common scroll example.
just like this api https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-scroll.html#sliced-scroll

**Comment by karmi** [comment]
The package provides access to the _Scroll_ API ([docs](https://pkg.go.dev/github.com/elastic/go-elasticsearch/v7@v7.7.0/esapi?tab=doc#Scroll)), so you can pass the `slice` parameter in the request body, as outlined in the example you've linked to.

As of now, there's no high-level helper for "scanning" an index, similar to the `esutil.BulkIndexer` helper, but it is planned for future versions.
