### ISSUE TITLE
Writing query for multiple conditions

### ISSUE THREAD

**Issue by readingtfsc** [elastic/go-elasticsearch#157]
`	query := map[string]interface{}{
		"query": map[string]interface{}{
			"bool": map[string]interface{}{
				"must": []interface{}{
					map[string]interface{}{
						"term": map[string]interface{}{
							"user_status": map[string]interface{}{
								"value": 1,
							},
						},
					},
					map[string]interface{}{
						"term": map[string]interface{}{
							"user_id": map[string]interface{}{
								"value": 453027897653854208,
							},
						},
					},
				},
			}},
	}`

**Comment by karmi** [comment]
Hello, please provide more information about what are you trying to achieve, what is not working, and so on.

**Comment by readingtfsc** [comment]
I need to query multiple conditions, but this writing method is very difficult

eg: 
I want to query through three conditions: username, userstatus and registrationtime. There will be many map [string] interface {} {}. It is very inflexible

sorry ,my english is very Poor. Can you understand what I mean ？

**Comment by karmi** [comment]
I understand what you're trying to achieve. The package accepts an `io.Reader` as the query definition, so it's up to you to provide the query — it could be a serialization of `map[string]interface{}` —, or it could be simply a `strings.Reader`. Have a look into `_examples/encoding` and `_examples/xkcdsearch` for samples.

In Elasticsearch terms, you probably want the Bool query — if you look into the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-bool-query.html), and switch the language to Go, you'll see an example.
