### ISSUE TITLE
BulkIndexer cannot insert data to Elastic Search < 7.0.0

### ISSUE THREAD

**Issue by Llewellin** [elastic/go-elasticsearch#158]
I am using `BulkIndexer` to insert data to ES. The problem is I don't see any places that I can add `_type` as traditional `Bulk` API provides. Any hints? How can I achieve this using `BulkIndexer`? 

Current version
```
type BulkIndexerItem struct {
	Index           string
	Action          string
	DocumentID      string
	Body            io.Reader
	RetryOnConflict *int

	OnSuccess func(context.Context, BulkIndexerItem, BulkIndexerResponseItem)        // Per item
	OnFailure func(context.Context, BulkIndexerItem, BulkIndexerResponseItem, error) // Per item
}
```
Should we add type here?
```
type BulkIndexerItem struct {
	Index           string
        Type            string
	Action          string
	DocumentID      string
	Body            io.Reader
	RetryOnConflict *int

	OnSuccess func(context.Context, BulkIndexerItem, BulkIndexerResponseItem)        // Per item
	OnFailure func(context.Context, BulkIndexerItem, BulkIndexerResponseItem, error) // Per item
}
```

**Comment by karmi** [comment]
Hello, for Elasticsearch 6.x, you have to use the corresponding version of the client, ie. [`6.x`](https://github.com/elastic/go-elasticsearch/tree/6.x). The support for document type was added in https://github.com/elastic/go-elasticsearch/commit/c022ac3fb26cdd903e9afe99a5562c41f0e83b64. Can you try with the 6.x branch?

It appears as the patch has not been released in a Git tag yet, I'll work on that.

**Comment by karmi** [comment]
I've released https://github.com/elastic/go-elasticsearch/releases/tag/v6.8.10 with the patch.

**Comment by Llewellin** [comment]
It works perfectly. Thank you very much.
