### ISSUE TITLE
Find() ret Root field value Pointer maybe nil

### ISSUE THREAD

**Issue by micheal0929** [elastic/go-elasticsearch#160]
`rsp, err := soup.Get(pSp.pageQueue[pSp.pageIndex])`
	       `if err != nil {
			log.Printf("get page : %s, err : %s", pSp.pageQueue[pSp.pageIndex], err)
		}`
		`doc := soup.HTMLParse(rsp)`
		`pageExist := doc.Find("div", "class", "page")`
just like this 
type Root struct {
	Pointer   *html.Node
	NodeValue string
	Error     error
}
pageExist type is Root 
Pointer maybe nil,so not suggest using like this 
`doc.Find("div", "class", "tags").FindAll("span", "class", "tag-item")`
sometimes may cause panic
better use like this:
`
pageExist := doc.Find("div", "class", "page")`
`if pageExist.Pointer == nil {
	return//or do something else
}`
`aLinks := pageExist.FindAll("a")
`

**Comment by karmi** [comment]
Hello, are you sure you've opened this issue in a correct repository?

**Comment by micheal0929** [comment]
> Hello, are you sure you've opened this issue in a correct repository?

so sorry, I made a mistake

**Comment by karmi** [comment]
No worries at all :)
