### ISSUE TITLE
how to disable host name validation

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [elastic/go-elasticsearch#162]
When I use go-elasticsearch to connect the remote elasticsearch which configure TLS. I am in trouble for the connection refused problem.
```
ERROR: Unable to get response: x509: cannot validate certificate for 10.113.215.206 because it doesn't contain any IP SANs
```
Can I disable X509 host name validation?

**Comment by karmi** [comment]
Hello, to customize the transport settings, see the example in the README, directly after the _“To configure other HTTP settings (...)”_ sentence. 

An executable example is available here:

https://github.com/elastic/go-elasticsearch/blob/68f14edba6d35cbf14652c26f89f2e99b5e4cb6c/_examples/configuration.go#L27-L38

As you are no doubt aware, disabling the validation is not the best option, and it's best to provide a certificate to the client — it exposes the `CACert` configuration option to make this easy.
