### ISSUE TITLE
Use context to pass value to bulk importer callback 

### ISSUE THREAD

**Issue by mbudge** [elastic/go-elasticsearch#163]
Hi, 

It would be useful if we could use the context to pass a value to the callback functions.

```	
        item := esutil.BulkIndexerItem{
                Action: "index",
		Body:   bytes.NewReader(j),
		OnSuccess: s.OnSuccess,
	}
	ctx := context.Background()
	ctx = context.WithValue(ctx, "k", "value")
	indexer.Add(ctx, item)
```

The context might be getting replaced, as we aren't able to get the value from the context in the callback functions. 

```
	func (s *Scanner) OnSuccess(ctx context.Context, item esutil.BulkIndexerItem, res esutil.BulkIndexerResponseItem) {
		_, ok := ctx.Value("k").(string)
		if !ok {
			log.Println("value not found")
		}
	}

```

prints value not found.

Being able to use the context to pass a value to the callback function makes it easier to cache a key + elastic ID in Redis for deduplication.

**Comment by karmi** [comment]
Hi, right, I had usecases like this in mind when I added the `ctx` argument to the signatures. I guess you're saying the context is not being correctly propagated from the `Add()` method to the callbacks?

**Comment by mbudge** [comment]
Yeah that's right. 

I'm using v7.3.0

**Comment by karmi** [comment]
You've mentioned Redis and deduplication, which sounds interesting. Could you provide more sample code for what you're doing in there? It would also help me to model the situation when I look into the implementation.

**Comment by mbudge** [comment]
Hi Karmi, 

Got no code to share I but can go over the process. 

If someone has a use case where they only want 1 copy of each document indexed in Elasticsearch, the easiest way to do this is hash a unique key and that as the _id. This hammers performance at scale, as elastic has to lookup each id when doing an upsert, and this doesn't work well when indexing millions of documents. 

Instead I use the following process to achieve high throughput while de-duplicating the data.

- Choose a unique key in the data set
- Use the key to get the elastic document ID from Redis 
- If the key exists, update the document. This is to get round the elastic refresh interval, as the document might not be visible in the index if another document was indexes within the last few seconds. 
- If the key does not exist in Redis, search the elastic index for the key to get the document ID. 
- If a document was found, get the document ID and update the document with the new values. 
- If no document was found, create a new document. 
- Cache the unique key and document ID in Redis 

Thanks
