### ISSUE TITLE
Got 'An HTTP line is larger than 4096 bytes' error when use scroll mechanism

### ISSUE THREAD

**Issue by DmSide** [elastic/go-elasticsearch#166]
Get the scroll_id by the request:
```
res, err := c.Search(
		c.Search.WithContext(background),
		c.Search.WithIndex(elasticIndex),
		c.Search.WithBody(&query),
		c.Search.WithSize(10000),
		c.Search.WithScroll(30*time.Second),
	)
```
After try to get second batch by the request:
```
res, err := c.Scroll(
			c.Scroll.WithScrollID(scrollId),
			c.Scroll.WithScroll(30*time.Second),
		)
```
and got an error  'An HTTP line is larger than 4096 bytes'

**Comment by karmi** [comment]
Hi! This is a known issue. The client is 1:1 to the ES API, and therefore `c.Scroll.WithScrollID()` will pass the value as an URL parameter, which will break for large values. The solution is to pass the value in the `Body`.

**Comment by karmi** [comment]
Hello! Getting back to this issue. As I was suggesting on the related pull request, the only solution here is to warn people that they should use the body, not the URL parameter. To really hit the issue, the [specification](https://github.com/elastic/elasticsearch/blob/8bdf36d18b5f013f97b8cc82efc2e076df5f2c6d/rest-api-spec/src/main/resources/rest-api-spec/api/scroll.json#L42-L45) would have to be updated to mark the URL parameter as deprecated. I'll raise this internally.

**Comment by Anaethelion** [comment]
As a solution has been provided, I'm going to close this issue.
If anyone stumbles upon this, please prioritize the use of the body for long scroll ids.
