### ISSUE TITLE
Get empty slice when reading body though logger reports valid response size

### ISSUE THREAD

**Issue by sptrakesh** [elastic/go-elasticsearch#168]
Hello,

I am running into a weird issue.  I have the exact same docker image deployed locally as well as within a GKE cluster.  I have no issues (all my tests pass) with the container running locally, but see the same issue everywhere (regardless of response size) on the GKE instance.

The logger reports something similar to the following:

```
{"duration":111386262,"method":"GET","reqBytes":0,"resBytes":269,"start":"2020-07-02T14:35:19.294456388Z","statusCode":200,"url":"https://<clusterid>.us-central1.gcp.cloud.es.io/<index>/_doc/1002"}
```

Attempting to parse into structs results in
```
Error parsing response body EOF
```

I tried using `ioutil.ReadAll` and I get back an empty array of bytes, though as above the logger reports `269` bytes.  The same happens regardless of the reported size (small or large).

I am unable to replicate this locally, so wondering if anyone has run into a similar issue and what the root cause could be.

Thanks
Rakesh

**Comment by karmi** [comment]
Hi, this is indeed weird. Could you please post more information about the version of the client, and the snippet of the Go code which executes the ES API? Also, this is running against Elastic Cloud?

**Comment by sptrakesh** [comment]
Hi,

Yes, this is running against Elastic Cloud.  Using the `v8` version of client.

```github.com/elastic/go-elasticsearch/v8```

The `client` is initialised using the following config (very trivial, just clusterID and api key)

```
cloud := func() elasticsearch.Config {
		const fn = "client.cloud"

		ec, err := util.EtcdClientInstance().Get("/database/elasticsearch/cloudId")
		if err != nil {
			log().Fatal(commonMessage(fn, "ElasticSearch cloudId not configured in etcd (/database/elasticsearch/cloudId)"))
		}

		kid, err := util.EtcdClientInstance().Get("/database/elasticsearch/apikey/id")
		if err != nil {
			log().Fatal(commonMessage(fn, "ElasticSearch API key id not configured in etcd (/database/elasticsearch/apikey/id)"))
		}

		key, err := util.EtcdClientInstance().Get("/database/elasticsearch/apikey/key")
		if err != nil {
			log().Fatal(commonMessage(fn, "ElasticSearch API key not configured in etcd (/database/elasticsearch/apikey/key)"))
		}

		aks := fmt.Sprintf("%v:%v", kid, key)
		ak := base64.StdEncoding.EncodeToString([]byte(aks))
		log().Info(commonMessage(fn, fmt.Sprintf("Using API Key: %v", ak)))

		return elasticsearch.Config{CloudID: ec, APIKey: ak, Logger: &ESLogger{}}
	}
```

```
func GetNutrient(ctx context.Context, id string) (*fdc.Nutrient, error) {
	const fn = "GetNutrient"

	es := client()
	res, err := es.Get(fdcNutrientIndex, id, es.Get.WithContext(ctx))

	if err != nil {
		log().Warning(nutrientMessage(fn, fmt.Sprintf("Error retrieving nutrient %v\n%v", id, err)))
		return nil, err
	}

	defer res.Body.Close()

	if res.IsError() {
		var e map[string]interface{}
		if err := json.NewDecoder(res.Body).Decode(&e); err != nil {
			log().Warning(nutrientMessage(fn, fmt.Sprintf("Error parsing error response body %v", err)))
			return nil, err
		}

		msg := "Error retrieving nutrient"
		log().Warning(nutrientMessage(fn, fmt.Sprintf("%v %v\n%v", msg, util.PrettyPrint(e), err)))
		return nil, errors.New(msg)
	}

	n := NutrientHit{}
	if err := json.NewDecoder(res.Body).Decode(&n); err != nil {
		log().Warning(nutrientMessage(fn, fmt.Sprintf("Error parsing response body %v", err)))
		return nil, err
	}

	return n.Source, nil
}
```

**Comment by karmi** [comment]
I'll try to replicate against an Elastic Cloud cluster, but in the meantime, can you `fmt.Println(res)`, to see if the body is indeed empty? Also, you can enable the response body logging. What happens when you `curl` the document URL?

**Comment by sptrakesh** [comment]
Will post back, but `curl` executed directly off the GKE pod works as expected.

**Comment by karmi** [comment]
Just so I understand, the _exact_ same code, running against Elastic Cloud, works locally, but not when executed in the GKE pod?

**Comment by sptrakesh** [comment]
Yes, I ran the same container locally against the same cloud cluster.

**Comment by sptrakesh** [comment]
Very interesting.  Setting response body logging seems to be **required**?

My logger function was as follows:

```
func (l *ESLogger) ResponseBodyEnabled() bool {
  return "local" == util.CacheManagerInstance().GetEnvironment()
}
```

I changed that to return `true`, and everything works on GKE.  I thought this would only affect logging, but is the response body being closed/consumed by just having a logger configured, and this is a mandatory setting?

**Comment by sptrakesh** [comment]
Never mind, found the issue with my logger implementation.

**Comment by karmi** [comment]
Curious about the logger — there's a couple of different loggers provided by the package, including a JSON-based one. Did you have some specific requirement which they didn't support?

**Comment by sptrakesh** [comment]
We used a unified logger that performs daily file rotation and a few other such old fashioned tasks.  Not as relevant with the tools cloud vendors provide, but still like to have them.
