### ISSUE TITLE
Migrate to go modules

### ISSUE THREAD

**Issue by andriisoldatenko** [elastic/go-elasticsearch#17]
What do you think if I can create PR to migrate to https://golang.github.io/dep/docs/migrating.html?

**Comment by andriisoldatenko** [comment]
cc @tsg

**Comment by miagile** [comment]
dep makes no sense after Go 1.11.  Libs should use modules.

**Comment by andriisoldatenko** [comment]
@miagile ^

**Comment by karmi** [comment]
Hi, sorry for the silence here, the client has been completely reworked, and made publicly available today.

It natively supports Go modules, see https://github.com/elastic/go-elasticsearch#installation
