### ISSUE TITLE
Cannot create document without _id

### ISSUE THREAD

**Issue by ndc629** [elastic/go-elasticsearch#174]
**What I did**:
I tried to create document with auto-generated _id by not specifying `DocumentID` into `esapi.CreateRequest`.

**Expectation**:
The document is created successfully, new _id is auto-generated and returned in response body.
This behavior can be archived by using POST `_index/_doc`
or Bulk request with empty create action `{ "create": {} }`

**Actual result**:
Got error:
`{
   "error":{
      "root_cause":[
         {
            "type":"illegal_argument_exception",
            "reason":"if _id is specified it must not be empty"
         }
      ],
      "type":"illegal_argument_exception",
      "reason":"if _id is specified it must not be empty"
   },
   "status":400
}`

**Comment by karmi** [comment]
The Create API _requires_ ID to be set. If you want to have the ID auto-generated, use the Index API.

**Comment by ndc629** [comment]
@karmi that makes sense a lot, thanks
