### ISSUE TITLE
Bulk index util should allow specifying version and version type

### ISSUE THREAD

**Issue by munkyboy** [elastic/go-elasticsearch#175]
The Bulk API supports document versioning metadata. These params should be exposed in the BulkIndexerItem struct.

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-versioning

**Comment by karmi** [comment]
Hello, sorry for the delay and thanks for the patch. Unfortunately, I think this has to be approached in a more robust way, allowing _all_ the possible metadata items in the payload.
