### ISSUE TITLE
Cannot initialize an index with a mapping

### ISSUE THREAD

**Issue by docwhite** [elastic/go-elasticsearch#187]
Hello,

I am learning Elasticsearch and Go at the same time. So it's likely I'm doing something very wrong. And it's probably not your tool but my Go code.

I am trying to create an index with a given mapping as I would do in Kibana with this REST request:

```
PUT /myindex
{
  "mappings": {
    "properties": {
      "Name": {
        "type": "text"
      },
      "Username": {
        "type": "keyword"
      },
      "Description": {
        "type": "text"
      }
    }
  }
}
```

When I try to translate this into Go, it generates a very strange recursion of key-values:

```
{
  "myindex" : {
    "mappings" : {
      "properties" : {
        "mappings" : {
          "properties" : {
            "properties" : {
              "properties" : {
                "Description" : {
                  "properties" : {
                    "type" : {
                      "type" : "text",
                      "fields" : {
                        "keyword" : {
                          "type" : "keyword",
                          "ignore_above" : 256
                        }
                      }
                    }
                  }
                },
                "Name" : {
                  "properties" : {
                    "type" : {
                      "type" : "text",
                      "fields" : {
                        "keyword" : {
                          "type" : "keyword",
                          "ignore_above" : 256
                        }
                      }
                    }
                  }
                },
                "Username" : {
                  "properties" : {
                    "type" : {
                      "type" : "text",
                      "fields" : {
                        "keyword" : {
                          "type" : "keyword",
                          "ignore_above" : 256
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

```

Here's the Go code that I tried to translate from the Kibana request.

```
mappings := map[string]interface{}{
	"mappings": map[string]interface{}{
		"properties": map[string]interface{}{
			"Name": map[string]interface{}{
				"type": "text",
			},
			"Username": map[string]interface{}{
				"type": "keyword",
			},
			"Description": map[string]interface{}{
				"type": "text",
			},
		},
	},
}

log.Println(mappings)
mappingsBytes, _ := json.Marshal(&mappings)
log.Println(string(mappingsBytes))
req := esapi.IndexRequest{
	Index:   "myindex",
	Body:    bytes.NewReader(mappingsBytes),
}
res, err := req.Do(ctx, es)
```

Here's my output logs:

```
2020/09/27 18:39:13 map[mappings:map[properties:map[Description:map[type:text] Name:map[type:text] Username:map[type:keyword]]]]
2020/09/27 18:39:13 {"mappings":{"properties":{"Description":{"type":"text"},"Name":{"type":"text"},"Username":{"type":"keyword"}}}}
```

The client I am using is the `elasticsearch.NewDefaultClient()`.

Thanks.

**Comment by karmi** [comment]
Hello, hard to say what's going on, but I have a couple of pointers.

First, can you enable the client logging in order to see what's happenning? See https://github.com/elastic/go-elasticsearch/tree/master/_examples/logging for examples of doing that. Can you enable request+response body logging and post the output here?

Second, here's an example of creating an index with a mapping from the `_examples/xkcdsearch` folder:

https://github.com/elastic/go-elasticsearch/blob/7442a8de30322bb1ed809b8d3a7847017842803a/_examples/xkcdsearch/store.go#L67

The mapping is defined here:

https://github.com/elastic/go-elasticsearch/blob/7442a8de30322bb1ed809b8d3a7847017842803a/_examples/xkcdsearch/cmd/xkcd/commands/index.go#L286-L304

In general, I prefer storing index settings/mappings as simple JSON strings in the codebase — it makes it much easier to read, much easier to maintain or reason about. 

Also, if you're starting, I'd suggest going through the examples in the `_examples` folder, as they have a lot of runnable code for common client operations.

Last, there's a series of blog posts published lately on the Elastic blog about the client, with a lot of explanations about client internals and usage patterns:

* https://www.elastic.co/blog/the-go-client-for-elasticsearch-introduction
* https://www.elastic.co/blog/the-go-client-for-elasticsearch-configuration-and-customization
* https://www.elastic.co/blog/the-go-client-for-elasticsearch-working-with-data

**Comment by docwhite** [comment]
Thanks @karmi I will give it a shot this afternoon and provide more information while I also read more examples, I didn't see them.

**Comment by Freesoul1982** [comment]
@docwhite I struggled with this issue too until realized that 'esapi.IndexRequest' creates/updates document inside index, you need to use 'esapi.IndicesCreateRequest' to create Index.

**Comment by docwhite** [comment]
Fantastic @Freesoul1982 thanks so much, I still haven't had the chance to try anything, I will try this afternoon or weekend and will let you know something to you and @karmi 

Thanks for your help.

**Comment by karmi** [comment]
Argh, I've overlooked the `esapi.IndexRequest` call in your original example — that indeed indexes documents, and doesn't create an index. For that, you need to use `myclient.Indices.Create()` or `esapi.IndicesCreateRequest`, as suggested.

**Comment by docwhite** [comment]
Thanks @Freesoul1982 and @karmi for the answer! Also I now know how to have colorful logs. 

Here's what was happening (wrongly using esapi.IndexRequest):

```
  HEAD http://localhost:9200/myindex 404 Not Found 5ms
────────────────────────────────────────────────────────────────────────────────
2020/11/13 19:15:09 map[mappings:map[properties:map[Name:map[type:text] Description:map[type:text] Username:map[type:keyword]]]]
2020/11/13 19:15:09 {"mappings":{"properties":{"Name":{"type":"text"},"Description":{"type":"text"},"Username":{"type":"keyword"}}}}
  POST http://localhost:9200/myindex/_doc 201 Created 144ms
       » {"mappings":{"properties":{"Name":{"type":"text"},"Description":{"type":"text"},"Username":{"type":"keyword"}}}}
       « {"_index":"myindex","_type":"_doc","_id":"kKUIw3UBWJsevEr7aTwG","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}
────────────────────────────────────────────────────────────────────────────────
```

And here's with `es.Indices.Create`:

```
  HEAD http://localhost:9200/myindex 404 Not Found 4ms
────────────────────────────────────────────────────────────────────────────────
2020/11/13 19:42:32 map[mappings:map[properties:map[Name:map[type:text] Description:map[type:text] Username:map[type:keyword]]]]
2020/11/13 19:42:32 {"mappings":{"properties":{"Name":{"type":"text"},"Description":{"type":"text"},"Username":{"type":"keyword"}}}}
   PUT http://localhost:9200/myindex 200 OK 104ms
       » {"mappings":{"properties":{"Body":{"type":"text"},"Description":{"type":"text"},"Username":{"type":"keyword"}}}}
       « {"acknowledged":true,"shards_acknowledged":true,"index":"myindex"}
────────────────────────────────────────────────────────────────────────────────
```

The issue can be now resolved if you want.

**Comment by karmi** [comment]
@docwhite , glad to hear that. Please feel free to close the issue.
