### ISSUE TITLE
'BulkIndexer Add'  func can't surport external-verison 

### ISSUE THREAD

**Issue by gxusc** [elastic/go-elasticsearch#189]
I can't control the version by use BulkIndexer Add()

**Comment by karmi** [comment]
There's couple of issues opened about this problem. As I've said on those and the the https://github.com/elastic/go-elasticsearch/pull/176 pull request, this needs to be solved in a more robust way, so all the parameters, not just the version, are supported. This assumes a bit of code generation, to keep the code in sync with the service.

**Comment by Anaethelion** [comment]
Closing this as this has been addresses in #265
