### ISSUE TITLE
No support for fuzzy search?? 

### ISSUE THREAD

**Issue by elftech** [elastic/go-elasticsearch#191]
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html

**Comment by elftech** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html.

**Comment by karmi** [comment]
The Query DSL is passed as the `Body` to search requests in the package, and therefore is supported as any other Query DSL part. Have a look at one approach in this example: https://github.com/elastic/go-elasticsearch/blob/master/_examples/xkcdsearch/store.go#L132, or here: https://github.com/elastic/go-elasticsearch/blob/master/_examples/encoding/jsonreader.go#L41 at another one.

**Comment by elftech** [comment]
> The Query DSL is passed as the `Body` to search requests in the package, and therefore is supported as any other Query DSL part. Have a look at one approach in this example: https://github.com/elastic/go-elasticsearch/blob/master/_examples/xkcdsearch/store.go#L132, or here: https://github.com/elastic/go-elasticsearch/blob/master/_examples/encoding/jsonreader.go#L41 at another one.

3ks!

**Comment by huangyingjun1989** [comment]
i have two documents. both have 'name' filed. the value are: 'huangyingjun1' and 'huangyingjun2'
the code: 
`import (
	"context"
	"github.com/olivere/elastic/v7"
)

func main() {
	ctx, _ := context.WithTimeout(context.Background(), 5*time.Second)
	// Create a client and connect to http://192.168.2.10:9201
	client, err := elastic.NewClient(elastic.SetURL("http://127.0.0.1:9200"))
	if err != nil {
		// Handle error
		panic(err)
	}
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("11111")
	search := client.Search().Index("twitter")

	q := elastic.NewRegexpQuery("user", ".+uan.+")
	sr, err := search.Query(q).Do(ctx)
	fmt.Println(sr.Hits)
}
`
output:
`
11111
&{0xc0000aca98 0xc0000a1df8 [0xc0000d7320 0xc0000d7440]}
`
it's works fine for me
