### ISSUE TITLE
Missing DocumentType field?

### ISSUE THREAD

**Issue by JackGzj** [elastic/go-elasticsearch#193]
I am using a esUtil in v8 version and I notice that there is no DocumentType field in BulkIndexerItem while a v6 version has. Please tell me how to specify the "type" value in a v8 version esUtil when using BulkIndexer？

**Comment by karmi** [comment]
Hello — the mapping types has been [deprecated since Elasticsearch version 7.x](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html), so the `v8` version doesn't provide support for it across the API, including the bulk indexer.

**Comment by JackGzj** [comment]
> Hello — the mapping types has been [deprecated since Elasticsearch version 7.x](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html), so the `v8` version doesn't provide support for it across the API, including the bulk indexer.

Get, Thanks.
