### ISSUE TITLE
There is any plan about release date of version 8?

### ISSUE THREAD

**Issue by Alexfilus** [elastic/go-elasticsearch#194]
I like the way of constructing requests from examples in master branch. There is some information when it will be released?

**Comment by philkra** [comment]
Hi @Alexfilus , I can confirm that there will be an `8.x` version of the go client, but I can't predict any dates. This and the other official language clients follow the Elastic Stack releases, in other words once we released `v8` of the Stack, we will also release an `8.0.0` version of the client.

**Comment by karmi** [comment]
@Alexfilus , can you clarify what is it specifically you want to do by "constructing requests from examples in the master branch"? As @philkra says above, there's no release date for the version 8 of the whole Elastic Stack, but you can you use the `elastic/go-elasticsearch/v8` version in your Go application as of now just fine — just do something like this in you `go.mod`:

https://github.com/elastic/go-elasticsearch/blob/1af099fb3eca91852c745621890299f88912af2e/_examples/xkcdsearch/go.mod#L7-L8

**Comment by Alexfilus** [comment]
@karmi I says about using "github.com/elastic/go-elasticsearch/v8/esapi" 
Ok, thanks, I will try it.

**Comment by karmi** [comment]
Right — then have a look at the example I've posted above. You can use the package version from the main branch in your `go.mod` like this:

```
module myapp

require (
	github.com/elastic/go-elasticsearch/v8 master
)
```

Then use it in your app like this:

```golang
package foo

import (
	"github.com/elastic/go-elasticsearch/v8"
	"github.com/elastic/go-elasticsearch/v8/esapi"
)
```
