### ISSUE TITLE
es.Search not working with Google Cloud Loadbalancing

### ISSUE THREAD

**Issue by jonny08152** [elastic/go-elasticsearch#198]
Similarly to #112 we are experiencing problems with the es.Search function in conjunction with our elasticsearch cluster behind a Google Cloud Loadbalancer. Google returns an Error 400:
> Your client has issued a malformed or illegal request.

This is when using es.Search.WithBody because of https://github.com/elastic/go-elasticsearch/blob/2e1f801663c62359a29cfa99d03ed6026d25767f/esapi/api.search.go#L106

Google seems to [not support a body when using GET](https://issuetracker.google.com/issues/36886282). When manually changing the request method to POST in the sources, everything works as expected.

For this please add an option to either automatically set the request method based on whether there is a body or add a switch to explicitly set the method for a request.

This issue also seems to be around in other elasticsearch clients ([elasticsearch-py](https://github.com/elastic/elasticsearch-py/issues/1146), other [go-client](https://github.com/olivere/elastic/issues/167)), for reference how they solved this.

**Comment by Anaethelion** [comment]
Similar to #112, closing this, the client now favors `POST` whenever possible to avoid any issues.
