### ISSUE TITLE
database/sql driver

### ISSUE THREAD

**Issue by themihai** [elastic/go-elasticsearch#20]
Driver for[ database/sql ](https://golang.org/pkg/database/sql/)interface using the SQL feature introduced in 6.3.

**Comment by karmi** [comment]
Hi @themihai, that's an interesting idea. The client codbase has been completely replaced today.

The SQL-related APIs are not implemented yet — I'll ping when they're added, and will take a look about integration with the `database/sql` package.

**Comment by technige** [comment]
While this is a good idea for a feature, it's not something which has been assigned priority over the five years since this issue was opened. Therefore, closing.
