### ISSUE TITLE
Add support for github.com/elastic/go-elasticsearch

### ISSUE THREAD

**Issue by abruneau** [elastic/go-elasticsearch#200]
given the [olivier/elasticsearch](https://github.com/olivere/elastic) is tentative on v8 and the official support is the long term choice for most customers it is important to add support for [elastic/go-elasticsearch](https://github.com/elastic/go-elasticsearch).

All is needed is to dupplicate oliver implementation and return a `RoundTripper` insted off a `http.Client`

**Comment by karmi** [comment]
Hello, can you add more details to the issue, clarify what exactly needs to be supported, and what is not working as expected?

**Comment by abruneau** [comment]
Sorry I oppened it on the wrong side. I wanted to ask Datadog to support this lib.
Sorry :)

**Comment by karmi** [comment]
Ah, right, no worries! :)

**Comment by karmi** [comment]
For the record, Elastic APM does support the package out of the box, see the [documentation](https://www.elastic.co/guide/en/apm/agent/go/current/builtin-modules.html#builtin-modules-apmelasticsearch) and the  [example](https://github.com/elastic/go-elasticsearch/tree/master/_examples/instrumentation#elastic-apm).
