### ISSUE TITLE
How can I delete according to the ID of es

### ISSUE THREAD

**Issue by huisebug** [elastic/go-elasticsearch#203]
How can I delete according to the ID of es

**Comment by philkra** [comment]
Hii @huisebug , could you please elaborate what you mean with _es_? Are you referring to a document in Elasticsearch?

**Comment by huisebug** [comment]
Thanks, I have solved it and used it
req := esapi.DeleteRequest{
Index: "esindex",
DocumentType: "image",
DocumentID: "esid",
Refresh: "true",
}


res, err := req.Do(context.Background(), es)
if err != nil {
log.Fatalf("Error getting response: %s", err)
}
defer res.Body.Close()

**Comment by philkra** [comment]
@huisebug , glad you were able to resolve it. Closing this issue.
