### ISSUE TITLE
esapi.Update Example

### ISSUE THREAD

**Issue by kurianCoding** [elastic/go-elasticsearch#214]
I am trying to use esapi.Update, looking through documentation and test i did not find one that pointed towards using this in in an app. Please point me towards one.

**Comment by kurianCoding** [comment]
https://github.com/swaggo/swag/issues/863

**Comment by loganbfisher** [comment]
@kurianCoding can you provide me with some information on how you got this working?  I cant seem to find anything on this either.

**Comment by surethink** [comment]
@loganbfisher  me too, I search for a long time, but cant find any example on how to update doc user go-elasticsearch

**Comment by claudiunicolaa** [comment]
I'll leave this here for future reference https://github.com/elastic/go-elasticsearch/issues/150
