### ISSUE TITLE
Feature request: compress body

### ISSUE THREAD

**Issue by adongy** [elastic/go-elasticsearch#217]
Hello,

Elasticsearch allows the request body to be compressed to save bandwidth at the cost of CPU time on the client.

Could we get an option for bulk indexers (and normal clients) to compress the body ?

Thanks!

**Comment by bschofield** [comment]
I wanted this feature, so I implemented it in PR https://github.com/elastic/go-elasticsearch/pull/288.

I'm using this now by adding this line to my `go.mod`:

```
replace github.com/elastic/go-elasticsearch/v7 v7.13.1 => github.com/bschofield/go-elasticsearch/v7 v7.13.2-0.20210628141847-eccb27ca97ab
```

**Comment by bschofield** [comment]
Should be closed by https://github.com/elastic/go-elasticsearch/pull/302, thanks @Anaethelion!
