### ISSUE TITLE
Bulk Upload

### ISSUE THREAD

**Issue by StuartScott5** [elastic/go-elasticsearch#218]
Hi,
Is it possible to Bulk upload and force overwriting documents using these components?
i.e. to avoid this... 'Version conflict, document already exists (current version [1]'

Thanks

**Comment by nevins-b** [comment]
use `index` action instead of `create` should do this.

**Comment by StuartScott5** [comment]
> use `index` action instead of `create` should do this.

@nevins-b - That's done it. Thank you for your help.
