### ISSUE TITLE
can't use github.com/elastic/go-elasticsearch/v7/_examples/fasthttp

### ISSUE THREAD

**Issue by c5433137** [elastic/go-elasticsearch#226]
go mod : require github.com/elastic/go-elasticsearch/v7 v7.6.0

import "github.com/elastic/go-elasticsearch/v7/_examples/fasthttp"
 
when i do this, i can't use the fasthttp package of _examples? 
![1](https://user-images.githubusercontent.com/21951963/108471306-27b20000-72c6-11eb-98d3-3750f6f801fa.png)

**Comment by Anaethelion** [comment]
@c5433137 This is intended behavior, the examples in the repository might change in the future and you wouldn't want to rely on this code.
A better way would be to copy the example into your own codebase and probably adapt it to your use case.
