### ISSUE TITLE
High memory footprint when using bulkIndexer

### ISSUE THREAD

**Issue by lichuan6** [elastic/go-elasticsearch#232]
I'm using bulkIndexer to index some data to es, I notice the memory footprint is quite high when there are a lot of data to index. pprof shows that `bulkIdexer.init` uses a lot of memory.

<img width="735" alt="Screen Shot 2021-02-24 at 1 37 11 PM" src="https://user-images.githubusercontent.com/74223747/108961403-42afb600-76b2-11eb-92bf-62ab6cb42118.png">

**Comment by lichuan6** [comment]
After doing some pprof work I found `buf.ReadFrom(item.Body)` there maybe memory leak when either `OnSuccess` or `OnFailure` is not nil.

```
github.com/elastic/go-elasticsearch/v7/esutil.(*worker).writeBody
/Users/git/beauty/elasticsearch-sync/vendor/github.com/elastic/go-elasticsearch/v7/esutil/bulk_indexer.go

  Total:           0   869.25MB (flat, cum) 87.99%
    416            .          .            
    417            .          .           		var getBody func() io.Reader 
    418            .          .            
    419            .          .           		if item.OnSuccess != nil || item.OnFailure != nil { 
    420            .          .           			var buf bytes.Buffer 
    421            .   827.71MB           			buf.ReadFrom(item.Body) 
    422            .          .           			getBody = func() io.Reader { 
    423            .          .           				r := buf 
    424            .          .           				return ioutil.NopCloser(&r) 
    425            .          .           			} 
    426            .          .           			item.Body = getBody() 
    427            .          .           		} 
    428            .          .            
    429            .     9.54MB           		if _, err := w.buf.ReadFrom(item.Body); err != nil { 
    430            .          .           			if w.bi.config.OnError != nil { 
    431            .          .           				w.bi.config.OnError(context.Background(), err) 
    432            .          .           			} 
    433            .          .           			return err 
    434            .          .           		} 
    435            .          .           		w.buf.WriteRune('\n') 
    436            .          .            
    437            .          .           		if getBody != nil && (item.OnSuccess != nil || item.OnFailure != nil) { 
    438            .       32MB           			item.Body = getBody() 
    439            .          .           		} 
    440            .          .           	} 
    441            .          .           	return nil 
    442            .          .           } 
    443            .          .            
```

**Comment by kendru** [comment]
I am running into the same issue. This is eventually leading to production crashes for me. Is there any update on it?

**Comment by lichuan6** [comment]
@kendru 
The [elasticsearch-rs](https://github.com/elastic/elasticsearch-rs) client library uses little memory for bulk index, you can see [example here](https://github.com/elastic/elasticsearch-rs/blob/master/elasticsearch/examples/index_questions_answers/main.rs).

**Comment by karmi** [comment]
I'm no longer maintaining this library, but I think I can see where this is coming from. The line which @lichuan6's investigation points to was added as part of https://github.com/elastic/go-elasticsearch/commit/8413c97f30112984737796ca9db1e93a11fe7e5a, in order to access item bodies in callbacks (eg. to put them onto a "dead letter queue" etc). It seems like when an `OnSuccess/OnFailure` callback is registered, but the body is not drained in it, it might indeed cause a severe leak. Not sure about a straightforward approach for a fix, because the indexer has no idea if the calling code will or will not access (and drain) the item body or not.

---

@lichuan6 , the example from the Rust client you points to seems to use only the generic Bulk API, notice that it is different from a high-level component like the BulkIndexer.

**Comment by Anaethelion** [comment]
Hi there, first of all, sorry for the late reply.
I took the time to investigate this issue and I am failing to replicate the problem described above.

The only way I could make pprof behave as such is by looking at cumulatives allocations (`alloc_space`) which would not indicate a memory leak, only high allocations which is to be expected in this case.

@lichuan6 could you share a little bit more informations about your metrics collection and the context if the trace is indeed from `inuse_space` ?

**Comment by keroro6** [comment]
@Anaethelion hi, I also meet the  problem. 
`
func BenchmarkMetrics(b *testing.B) {
	bi, _ := elasticsearch.NewBulkIndexer(elasticsearch.BulkIndexerConfig{
		Index: "123", // The default index name
		NumWorkers:    1000,        // The number of worker goroutines
		FlushBytes:    1024 * 1024, // The flush threshold in bytes
		FlushInterval: time.Second, // The periodic flush interval
		Decoder:       elasticsearch.CustomJSONDecoder{},
	})
	for n := 0; n < b.N; n++ {
		di := elasticsearch.BulkIndexerItem{
			Index:      "123",
			Action:     "create",
			DocumentID: fmt.Sprintf("%d", n),
			Body:       bytes.NewReader([]byte("morycxbegiuwtsnp3{instance_id=\"i-abcdefghigklmn\",inner_addr=\"192.168.x.x\",project_id=\"fjajebngiajvjjyn\"}")),
		}
		_ = bi.Add(context.Background(), di)
	}
}`

refer https://github.com/elastic/go-elasticsearch/blob/master/esutil/bulk_indexer.go 

When I run 
go test -bench=BenchmarkMetrics -benchtime=2s   -memprofile mem.out
go tool pprof  metrics.test mem.out

**Comment by Anaethelion** [comment]
Hi @keroro6,

I've taken some time to look into this issue and have a possible fix pushed to https://github.com/elastic/go-elasticsearch/pull/315
Can you have a look, maybe test these changes, and let me know ?

Thank you!

**Comment by Anaethelion** [comment]
Dealt with in #315
