### ISSUE TITLE
How to set and get type? -> is Deprecated in elasticsearch 7.12.0

### ISSUE THREAD

**Issue by swaaws** [elastic/go-elasticsearch#245]
GET http://es01:9200/index/type/_id

The Code:
doc := data{Title: "test"}
res, _ := es.Index("index", esutil.NewJSONReader(&doc))
log.Println(res)

Index can be set in the es.Index() function but how to set the type. Sometimes the Type will be "_doc" if i set "DocumentID" the type is sometimes the "DocumentID"

Can the Type set?

**Comment by swaaws** [comment]
Updatet go-elasticsearch from go get V8.0.0 to V7.12.0

New Error:
400 Bad Request] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [test] as the final mapping would have more than 1 type: [_doc, love]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [test] as the final mapping would have more than 1 type: [_doc, love]"},"status":400}

Code:
res, err := es.Index(
				"test",                                  // Index name
				esutil.NewJSONReader(&doc), // Document body
				es.Index.WithDocumentType("love"),            // Document ID
				es.Index.WithRefresh("true"),            // Refresh
			)

**Comment by Anaethelion** [comment]
Hi there, Types are deprecated in APIs in 7.0.
You can find some strategies in the documentation if you really need types in your documents :
https://www.elastic.co/guide/en/elasticsearch/reference/7.12/removal-of-types.html

**Comment by swaaws** [comment]
Thanks
