### ISSUE TITLE
Invalid time duration formatting

### ISSUE THREAD

**Issue by andrewkroh** [elastic/go-elasticsearch#25]
I was trying to do a scroll query and hit an issue caused by the formatting of time durations that are passed to Elasticsearch. You can see and example in: 

https://play.golang.org/p/fKd7ErkUTJB

I tracked down the line in the generator but I wasn't exactly sure how to regenerate the source. (I think this would be a good topic for the readme or maybe a contributing doc.)

The scroll time was being formatted based on the Go time.Duration format. So for one minute it would use 16666h40m0s. Elasticsearch supports nanoseconds as a [time unit](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/common-options.html#time-units) so it can pass the Go time.Duration value through without any conversion just by appending "nanos". 

```patch
diff --git a/internal/cmd/generate/commands/gensource/generator.go b/internal/cmd/generate/commands/gensource/generator.go
index cf05218..50b7936 100755
--- a/internal/cmd/generate/commands/gensource/generator.go
+++ b/internal/cmd/generate/commands/gensource/generator.go
@@ -625,7 +625,7 @@ func (r ` + g.Endpoint.MethodWithNamespace() + `Request) Do(ctx context.Context,
                                fieldValue = `strings.Join(r.` + fieldName + `, ",")`
                        case "time.Duration":
                                fieldCondition = `r.` + fieldName + ` != 0`
-                               fieldValue = `time.Duration(r.` + fieldName + ` * time.Millisecond).String()`
+                               fieldValue = `strconv.FormatInt(int64(r.` + fieldName +`), 10) + "nanos"`
                        default: // interface{}
                                fieldCondition = `r.` + fieldName + ` != nil`
                                // TODO: Use type switching instead?
```

**Comment by karmi** [comment]
Thanks for the report, @andrewkroh! I was expecting to hit this problem in time, and was aware that the conversion in that spot is too naïve. I'll have a look into that soon.

And yes, documentation on the generator is a good idea — when the setup is right, `make gen-api` is the command to run.

**Comment by karmi** [comment]
This has been closed via https://github.com/elastic/go-elasticsearch/commit/c7dbbb6ef673cfbd47d24ab7acaa45e75fe2b17b and https://github.com/elastic/go-elasticsearch/commit/6b958862886db89d5dffa052185781dc54c91550 — thanks for the report again!
