### ISSUE TITLE
Update returns 400 without body

### ISSUE THREAD

**Issue by tomiok** [elastic/go-elasticsearch#261]
`	req := esapi.UpdateRequest{
		Index:      "test",
		DocumentID: id,
		Body:       bytes.NewReader(b),
		Refresh:    "true",
	}
`
this code, after the req.Do functions, returns no error but a 400 in the response with the body empty.

**Comment by Anaethelion** [comment]
Hi @tomiok,

Sorry for the late reply, could you give me some details about the request, the go client version and Elasticsearch version ?
Is you server behind a proxy which could truncate the response body and only return the status code ?

**Comment by chanced** [comment]
The package doesn't check (all? any?). You'll need to do that as you would using the `http` package.
