### ISSUE TITLE
Feature request:  Repository analysis API

### ISSUE THREAD

**Issue by Utsavk** [elastic/go-elasticsearch#275]
I cannot find the support for the new API "/_snapshot/my_repository/_analyze" which is introduced in version 7.12. I checked the branch 7.12 for the same but could not find anything.

If it is still not implemented, I would like to contribute.

**Comment by Anaethelion** [comment]
Hi @Utsavk 

Thanks for raising this issue!
The spec for this has been moved to the right place in https://github.com/elastic/elasticsearch/pull/73378
Since the client is generated from the spec files, it will be included in the next release.
