### ISSUE TITLE
Error "missing authentication credentials for REST request"

### ISSUE THREAD

**Issue by susana-garcia** [elastic/go-elasticsearch#279]
Hi,
I'm using version v7.13.0 with Elastic Cloud and having an issue trying to execute a `search`. 
I'm getting this error:
```
[401 Unauthorized] {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/logstash-*/_search]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/logstash-*/_search]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}},"status":401} <nil>
``` 

This is how the client config looks like:
```
	cfg := elasticsearch.Config{
		CloudID: "MY_CLOUD_ID",
		APIKey:  "MY_API_KEY",
		Logger: &estransport.ColorLogger{
			Output:             os.Stdout,
			EnableRequestBody:  true,
			EnableResponseBody: true,
		},
	}
	client, err := elasticsearch.NewClient(cfg)
```

Debugging the code, I can see that the `Authorization` header is added to the request by the transport: "ApiKey MY_API_KEY"

What am I missing?

**Comment by Anaethelion** [comment]
Hi @susana-garcia 

How did you create the API Key ?
Can you check the API key has the proper rights to access the cluster ?

As far as code goes, this is the way it works so you didn't miss anything on that front.

**Comment by susana-garcia** [comment]
hi @Anaethelion 

I created the API Key following these steps: https://www.elastic.co/guide/en/cloud/current/ec-api-authentication.html

But I ended up using user/password instead of the API Key.

Cheers

**Comment by Anaethelion** [comment]
Ok that explains why the client was throwing `401` status codes.
This API key is for the Elastic Cloud operations such as deployments or autoscaling.

For the client you can generate an API key for your Elasticsearch cluster via Kibana in the `API Keys` page which can be found in `Manage > Security`.

Hope this helps !

**Comment by susana-garcia** [comment]
oh, that makes perfect sense, thank you so much for your answer. I'll try it 👍 
cheers!

**Comment by susana-garcia** [comment]
and it worked just fine, thanks again!
