### ISSUE TITLE
How to use the esutil bulk indexer?

### ISSUE THREAD

**Issue by girafferiel** [elastic/go-elasticsearch#284]
I have a worker which is a kafka consumer which listens to a message queue. When a message is received, it syncs the data in the message to elastic search. I am reading how to use esutil bulk indexer in this article: https://www.elastic.co/blog/the-go-client-for-elasticsearch-working-with-data

I'm wondering, should I call this code once or everytime I want to sync (kafka message is received)?

```
bi, err := esutil.NewBulkIndexer(esutil.BulkIndexerConfig{
  Index:         indexName,        // The default index name
  Client:        es,               // The Elasticsearch client
  NumWorkers:    numWorkers,       // The number of worker goroutines
  FlushBytes:    int(flushBytes),  // The flush threshold in bytes
  FlushInterval: 30 * time.Second, // The periodic flush interval
})
```

Because if I call it once only (when my worker is initialized), I will never close the bulk indexer:
```
if err := bi.Close(context.Background()); err != nil {
  log.Fatalf("Unexpected error: %s", err)
}
```
because listening to queue is non-stop. I'm wondering if its OK to not call this function?
Thanks

**Comment by Anaethelion** [comment]
While it is OK to never call this function, I would still call it before quitting your program to ensure the BulkIndexer queue has been flushed.
If you don't, you may lose some documents that did not have enough time to be indexed in Elasticsearch.

The idea is to initialize the indexer once and then use the `Add` method to add documents in the queue to be indexed. Indexation is triggered either by time interval, size of the queue or by calling `Close` which flushes the entire queue before closing.

**Comment by girafferiel** [comment]
thank you, if you have time please take a look at my new issue @Anaethelion https://github.com/elastic/go-elasticsearch/issues/285
