### ISSUE TITLE
Can i use gzip compress in bulk-index api?

### ISSUE THREAD

**Issue by Bale-do** [elastic/go-elasticsearch#298]
i try to use gzip compress refer [this example code](https://github.com/elastic/go-elasticsearch/blob/master/_examples/bulk/indexer.go)
in my case, i put compressed body into bulkIndexerItem (in example, line 209)
but response return status '0'

this is my compress function
```
func compressQueryByGZip(queryByteBuff *bytes.Buffer) (*bytes.Buffer, error) {
	buf := new(bytes.Buffer)
	w := gzip.NewWriter(buf)

	if _, err := w.Write(queryByteBuff.Bytes()); err != nil {
		return nil, err
	}

	if err := w.Close(); err != nil {
		return nil, err
	}

	return buf, nil
}
```

thanks

**Comment by bschofield** [comment]
Compressing the individual items in the bulk indexing request won't work. Instead, the bulk items should be supplied uncompressed, and the final constructed HTTP request (containing all the bulk items) needs to be compressed as a single unit. The request compression also needs to be indicated to the server using the appropriate HTTP header.

PR https://github.com/elastic/go-elasticsearch/pull/302 (merged) adds a `CompressRequestBody` option to the client, that you can now use for this purpose. If you set that, it should work?
