### ISSUE TITLE
client support for v6 missing update mapping types for existing index

### ISSUE THREAD

**Issue by cuongld2** [elastic/go-elasticsearch#299]
For example :
PUT {index_name} 
{
    "mappings": {
        "index_type": {
            "properties": {
                "field": {
                    "type": "keyword"
                },
                "field": {
                    "type": "keyword"
                },
                "field": {
                    "type": "long"
                },
                "field": {
                    "type": "nested",
                    "properties": {
                        "field": {
                            "type": "long"
                        },
                        "field": {
                            "type": "keyword"
                        },
                        "field": {
                            "type": "keyword"
                        },
                        "field": {
                            "type": "long"
                        },
                        "field": {
                            "type": "long"
                        }
                    }
                }
            }
        }
    }
}

**Comment by Anaethelion** [comment]
V6 not being maintained anymore, I'm closing this issue.
