### ISSUE TITLE
Collapse for Search API

### ISSUE THREAD

**Issue by belindaxinyi** [elastic/go-elasticsearch#306]
Will collapse be supported for the search API?

**Comment by Anaethelion** [comment]
Hi @belindaxinyi,

This client is a low level one and the body is part of what is delegated to the user.
The `collapse` can be handled directly into the payload you send via the `Search` method and should already work if you are using a >7.13 version of Elasticsearch.

Did you have anything specific in mind or did you encounter problems ?

**Comment by belindaxinyi** [comment]
I was trying to write queries using the search API, and found parameters like Sort catered for in the methods but not Collapse. May I know what is taken into consideration when creating the methods, since I would think that whatever possible parameters possible for each API would be taken into account when creating the API methods.

**Comment by Anaethelion** [comment]
Of course!
The client is generated from json specification files which can be found in the Elasticsearch repository.
For example, Search would be this file : https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/search.json

As you can see those files only cover URL parameters, hence no support for body.

There are plans in the works to support body as well but I do not have any ETA yet.

**Comment by belindaxinyi** [comment]
Noted, thank you!
