### ISSUE TITLE
Provide alternative for basic auth

### ISSUE THREAD

**Issue by jordansissel** [elastic/go-elasticsearch#32]
Including user:pass in the URL is, as we've learned from time to time on Logstash, not a safe thing to do. The reason is that you can easily make mistakes when logging such that you intend to log the URL, but that URL includes secrets, and now you've written your secrets to the log file.

Proposal: Include a way to provide credentials without embedded them into the URL string.

**Comment by karmi** [comment]
Hey, I've added the `Username` and `Password` fields to the configuration struct and across the documentation — see the attached commit for more info.
