### ISSUE TITLE
something wrong with 7.x

### ISSUE THREAD

**Issue by mutsunico** [elastic/go-elasticsearch#337]
package command-line-arguments
        imports case-api/elastic
        imports elastic/go-elasticsearch/v7
        D:\Go\src\elastic\go-elasticsearch\v7\elasticsearch.go:39:2: use of internal package github.com/elastic/
go-elasticsearch/v7/internal/version not allowed

**Comment by Anaethelion** [comment]
Hi @mutsunico 

I've tried replicating your issue on a Windows machine without success.
Can you provide a `main` file which would replicate your problem and specify which version of Go you are using ?
