### ISSUE TITLE
Allow different Username/Password for each URLs

### ISSUE THREAD

**Issue by rugamaga** [elastic/go-elasticsearch#338]
Currently, Username/Password for BasicAuth is common for all urls.
But it seems better to allow different username/password for each urls.

For example, it allow us graceful password update like following process(Currently, we must stop client before update the password):

1. First we start with following configulations:
	- there is a elasicsearch cluster on `example.com:9200` and it accept `Username=elastic, Password=xxxxxxxx`
	- Our client setting is like: `Config1: URL=example.com:9200, Username=elastic, Password=xxxxxxxx`

2. Update configulation like:
```
Config1: URL=example.com:9200, Username=elastic, Password=xxxxxxxx
Config2: URL=example.com:9200, Username=elastic, Password=yyyyyyyy // add this config
```

3. Deploy it. 
	- it will occur error on Config2 but Config1 so it's continue connected.

4. Change password config of our elasticsearch cluster on example.com:9200 from `xxxxxxxx` to `yyyyyyyy`.
	- it will occur error on Config1 but Config2 so it's continue connected.

5. Delete configulation for `password=xxxxxxxx`

**Comment by Anaethelion** [comment]
If you want to store the two passwords for the same user I would recommend to create two clients with the relevant configurations.
You could then control which client you decide to use or implement fallback on error if the first client fails, allowing you to gracefully update your credentials.

An easier way would be to create a new user, propagate the change to your application and then remove the old user on the cluster.
