### ISSUE TITLE
dial tcp IP:PORT: i/o timeout

### ISSUE THREAD

**Issue by wlacp** [elastic/go-elasticsearch#34]
When I use this vendor to connect elasticsearch 2.x, It's error, I know it's support for 7.x now, but it's no error when I doing NewClient, then I use client.Info(), it's nil, and the error is dial `tcp IP:PORT: i/o timeout`.

**Comment by karmi** [comment]
Hello, can you post the code you're using to initialize the client, including how do you pass the address  of the Elasticsearch cluster?

**Comment by wlacp** [comment]
I use it as `_examples/configuration.go` and replace the Addresses to myself

```
    cfg := elasticsearch.Config{
		Addresses: []string{"http://localhost:9200"},
		Transport: &http.Transport{
			MaxIdleConnsPerHost:   10,
			ResponseHeaderTimeout: time.Millisecond,
			DialContext:           (&net.Dialer{Timeout: time.Nanosecond}).DialContext,
			TLSClientConfig: &tls.Config{
				MaxVersion:         tls.VersionTLS11,
				InsecureSkipVerify: true,
			},
		},
	}

	es, err := elasticsearch.NewClient(cfg)
	if err != nil {
		log.Printf("Error creating the client: %s", err)
	} else {
		log.Println(es.Info())
	}
```

**Comment by karmi** [comment]
I see. The timeout values in the example above is only illustrative, only as examples. Therefore your client times out, since `time.Nanosecond` is probably a bit too short... :)

If you want to set addresses, keep the `Transport` part out:

```golang
cfg := elasticsearch.Config{
	Addresses: []string{"http://localhost:9200"},
	
}

es, err := elasticsearch.NewClient(cfg)

if err != nil {
	log.Printf("Error creating the client: %s", err)
} else {
	log.Println(es.Info())
}
```

**Comment by wlacp** [comment]
Thank you, you are right, like this, I connect success and already got result through the Search()

**Comment by karmi** [comment]
Thanks for the hint! I'll separate the example in the README, and add note to the `configuration.go` file, in order to make this more transparent.
