### ISSUE TITLE
I'm getting this error when trying to ping an ES server

### ISSUE THREAD

**Issue by feketegy** [elastic/go-elasticsearch#344]
The error is: `the client noticed that the server is not a supported distribution of Elasticsearchmake[1]`

I'm using `github.com/elastic/go-elasticsearch/v7 v7.15.0` with `go1.16`

The ES server info is: 

```
"version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2021-05-21T20:25:46.519671Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
```

**Comment by Anaethelion** [comment]
This is explained in the compatibility matrix in the readme:
`Language clients are forward compatible; meaning that clients support communicating with greater or equal minor versions of Elasticsearch. Elasticsearch language clients are only backwards compatible with default distributions and without guarantees made.`

Hence, the `7.15` client is not compatible with the `oss` distribution version `7.10.2`.
You can still use the version `v7.10.0` of this client for full compatibility!
