### ISSUE TITLE
timeout 参数 BUG

### ISSUE THREAD

**Issue by as0x** [elastic/go-elasticsearch#35]
使用超时选项，s.client.Search(s.client.Search.WithIndex("index"), s.client.Search.WithBody(body), s.client.Search.WithTimeout(180000))
生成的请求URL为：
/index/_search?timeout=3m0s
ES 6.4 版本不能解析timeout参数，响应的错误信息为：
"reason": "failed to parse [3m0s]"
请求URL修改为 /index/_search?timeout=3m 则可以正常工作。
希望可以帮助到你们。

**Comment by karmi** [comment]
The timeout formatting is currently incorrect, there's https://github.com/elastic/go-elasticsearch/pull/27 open to address.

**Comment by as0x** [comment]
> The timeout formatting is currently incorrect, there's #27 open to address.

Thank you for your reply.

**Comment by karmi** [comment]
This has been closed via https://github.com/elastic/go-elasticsearch/commit/c7dbbb6ef673cfbd47d24ab7acaa45e75fe2b17b and https://github.com/elastic/go-elasticsearch/commit/6b958862886db89d5dffa052185781dc54c91550 — please try with current `master` or version branches.
