### ISSUE TITLE
Is elasticsearch.Client thread safe? Can I share the client in multiple goroutines?

### ISSUE THREAD

**Issue by zbflcy** [elastic/go-elasticsearch#361]
Is elasticsearch.Client thread safe? Can I share the client in multiple goroutines?

**Comment by DanielSmetanka** [comment]
I am experiencing some weird behaviour when increasing the number of goroutines. It feels like some kind of race condition...

**Comment by Anaethelion** [comment]
Hey @zbflcy yes the client is, as highlighted in the [README](https://github.com/elastic/go-elasticsearch#usage) of this repository.

@DanielSmetanka Could you open a specific issue with a snippet of code that would reproduce the problem you are facing ?
