### ISSUE TITLE
bulk.api -> olivere/elastic.bulk.api 

### ISSUE THREAD

**Issue by liuwangchen** [elastic/go-elasticsearch#37]
olivere/elastic.bulk.api better than this.bulk.api

**Comment by karmi** [comment]
Because`olivere/elastic` is a higher-level client than `go-elasticsearch`, it's focused a bit differently.

Nevertheless, if you'd provide examples of how the API is "better", I can add examples or extensions which would improve dealing with the API.

**Comment by liuwangchen** [comment]
Well~this.bulk.api such like 
![image](https://user-images.githubusercontent.com/25526033/54909279-c724b780-4f24-11e9-87c9-61c85afc1c5f.png)
io.Reader is too complex to join syntax-json-string

But the olivere/elastic.bulk.api is very simple,just add some optionRequest.like
![image](https://user-images.githubusercontent.com/25526033/54909623-9db85b80-4f25-11e9-92c1-67089a2ae4d1.png)

Hope this.bulk.api provide join-syntax-json-string.api to (instead of OR transform) the io.Reader

**Comment by ngocchien** [comment]
> Because`olivere/elastic` is a higher-level client than `go-elasticsearch`, it's focused a bit differently.
> 
> Nevertheless, if you'd provide examples of how the API is "better", I can add examples or extensions which would improve dealing with the API.

Please give me a sample of this method.
From esapi.BulkRequest to esapi.Bulk()

Thank you very much!
I love you!

**Comment by ngocchien** [comment]
![image](https://user-images.githubusercontent.com/10099022/55013293-6b892580-501b-11e9-84fd-c020829fe4df.png)

this code is PHP

But can not convert to golang :(

![image](https://user-images.githubusercontent.com/10099022/55013516-d63a6100-501b-11e9-8d8f-95ae6400f803.png)

Please give me an example for this method!

Thank you very much!

**Comment by karmi** [comment]
Hey, so as said, the `olivere/elastic` package provides a higher-level API, while the `elastic/elasticsearch` package is a low-level client.

I started working on an example for using the _Bulk_ API. Before it's fully merged, you can check the code here: https://github.com/elastic/go-elasticsearch/blob/example_bulk/_examples/bulk/bulk.go

It demonstrates how to send data from a slice in batches, by filling a `bytes.Buffer`, and how to properly check for errors during indexing. Hopefully it's helpful.

**Comment by karmi** [comment]
Hello, closing this, feel free to open a new issue or re-open this one.
