### ISSUE TITLE
Conditional update based of numeric fields

### ISSUE THREAD

**Issue by sir-farfan** [elastic/go-elasticsearch#384]
Hello Elastic

I'm new to the package, I'm still reading the [blog](https://www.elastic.co/blog/the-go-client-for-elasticsearch-working-with-data) and the documentation.

We have a continuous stream of events that we're sending to ES and we care to keep only the latest one based on **modified.[seconds, nanos]** fields in the JSON object.
We're seeing a performance issues, lots of idle time waiting apparently, due to the fact that we first (try to) retrieve the document and then decide whether or not to update it from the client side; it would be nice to save one or two trips to the server.

Some [old stuff](https://discuss.elastic.co/t/conditional-update-to-the-document/64964/11) I've found suggest people have tried dealing with similar issues in the past but I'm not sure they actually reached a conclusion or if it's implemented in this fine library.
There's also an [old similar](https://github.com/elastic/go-elasticsearch/issues/109) question here in the repo but didn't seem to reach any conclusion either.

**Comment by Anaethelion** [comment]
Hello @sir-farfan

Thanks for your question, this isn't handled by this library but can be handled by Elasticsearch directly depending on your needs.
I strongly recommend that the `_id` of the documents you are sending is known beforehand, you then could rely on the [noop detection](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_detect_noop_updates) from Elasticsearch to do the job and post to the `_update` endpoint of your index. You could even do a `scripted_upsert` as shown in [this example](https://discuss.elastic.co/t/conditional-update-to-the-document/64964/20) if you are creating and updating in one request.

Given this is more a question about Elasticsearch API than an issue with this library I propose you push forward in [the forum](https://discuss.elastic.co/).

**Comment by sir-farfan** [comment]
Interesting, so this was like a server side function all along. I though it was an special endpoint which could receive a script or something like that.

Thanks for the advice, I'll see if we can get the ES admin involved on this.
