### ISSUE TITLE
How to connect only the coordinating node

### ISSUE THREAD

**Issue by wudaoluo** [elastic/go-elasticsearch#392]
How to connect only the coordinating node.
 I didn't see it on the documentation or use cases

**Comment by Anaethelion** [comment]
Hi @wudaoluo 

Assuming we are talking about the discovery process, you can enable in the client's `Config` the `DiscoverNodesOnStart` and `DiscoverNodesInterval` and then provide a `ConnectionPoolFunc` function to filter the connection pool in a way that best fit your usage.

Let me know if that's not the case!
