### ISSUE TITLE
DiscoverNodesOnStart causes I/O timeout

### ISSUE THREAD

**Issue by danvixent** [elastic/go-elasticsearch#393]
Library version 7.16.0, elasticsearch version 7.16.2
Setting DiscoverNodesOnStart in elasticsearch.Config when initializing a client results in I/O timeout error from the server:

```go
dial tcp xxx.xx.x.x:9200: i/o timeout
```

**Comment by Anaethelion** [comment]
Hi @danvixent 

Just tested locally and this seems to work as expected using the same versions you mentioned.
Do you have any additional configuration set that could make this fail ?

For reference here is the code I used:

```go
package main

import (
	"fmt"
	"github.com/elastic/go-elasticsearch/v7"
	"io"
)

func main() {
	cfg := elasticsearch.Config{
		DiscoverNodesOnStart: true,
	}
	client, err := elasticsearch.NewClient(cfg)
	if err != nil {
		panic(err)
	}

	res, err := client.Info()
	if err != nil {
		panic(err)
	}
	defer res.Body.Close()
	data, _ := io.ReadAll(res.Body)
	fmt.Println(string(data))
}

```

**Comment by danvixent** [comment]
Hello @Anaethelion, my bad. The client will initialize correctly but won't work when querying data.
That’s when the i/o timeout occurs. It's worthy to note that this issue, about 2 months ago, once occurred for me locally. I moved to cloud and it disappeared.

It appeared on cloud recently and that was when i opened the issue, also i set `DiscoverNodesInterval` to 10 minutes.

**Comment by Anaethelion** [comment]
Thank you for reporting this, I've managed to reproduce the issue!

**Comment by danvixent** [comment]
You're welcome. I'm happy to provide any form of assistance in resolving this.

**Comment by Anaethelion** [comment]
> It appeared on cloud recently and that was when i opened the issue, also i set `DiscoverNodesInterval` to 10 minutes.

Note that if you are using Elastic Cloud, you should not enable discovery as it is already done by the cloud on your behalf. In that case discovery gathers only private instances IPs that are not publicly routed, ending in a timeout.

**Comment by danvixent** [comment]
Ah, that explains why removing it works. Thank you.

**Comment by danvixent** [comment]
@Anaethelion i can close this now right?

**Comment by Anaethelion** [comment]
Closing this as the question has been answered.
