### ISSUE TITLE
Unknown server detected by v7 and v8 of the module

### ISSUE THREAD

**Issue by lferro9000** [elastic/go-elasticsearch#394]
What is expected:

Connection to be successful.

What happens:

When using client V8 against a server version 5.6 (yes i know is old), the connection fails with the message:

`Error getting response: the client noticed that the server is not Elasticsearch and we do not support this unknown product`

Same code against server version 7.x works fine.

Downgrading v8 to v7 results in the same error.

Downgrading to v6 works as expected.

Potencial actions:

- Remove the check on version v7 and v8 (unlikely) or
- Update the check to correctly identify ES servers < 6.x (more plausible)

**Comment by Anaethelion** [comment]
As stated in the readme, the Go client is only forward compatible, and as you stated 5.6 is quite old.
Best options would be to update Elasticsearch or if that cannot be done pin the client to `<7.14`.
