### ISSUE TITLE
Extend Client to Watcher API

### ISSUE THREAD

**Issue by evanfreed** [elastic/go-elasticsearch#40]
It'd be nice to see this client cover the watcher API's as well.

Wiki Reference:
https://www.elastic.co/guide/en/elasticsearch/reference/7.0/watcher-api.html

**Comment by karmi** [comment]
Hello, absolutely: support for the X-Pack APIs is on the roadmap. It has its own set of [REST API specification](https://github.com/elastic/elasticsearch/tree/master/x-pack/plugin/src/test/resources/rest-api-spec/api) and [tests](https://github.com/elastic/elasticsearch/tree/master/x-pack/plugin/src/test/resources/rest-api-spec/test), and I need to update the generators to work correctly with them.

**Comment by karmi** [comment]
So, I got curious how to extend the client from the outside, and call a custom endpoint, eg. for one of the [API extension plugins](https://www.elastic.co/guide/en/elasticsearch/plugins/7.x/api.html), and came up with the following:

```golang
//+build ignore

package main

import (
	"io"
	"log"
	"net/http"
	"strings"

	"github.com/elastic/go-elasticsearch"
	"github.com/elastic/go-elasticsearch/esapi"
)

// CustomClient allows to call custom APIs via the elasticsearch client.
//
type CustomClient struct {
	client *elasticsearch.Client
}

// PutWatch registers a new watch or updates an existing one.
//
// https://github.com/elastic/go-elasticsearch/blob/xpack/esapi/xpack/api.watcher.put_watch.go
//
func (c *CustomClient) PutWatch(id string, body io.Reader) (*esapi.Response, error) {
	req, err := http.NewRequest("PUT", "/_watcher/watch/"+id, body)
	if err != nil {
		return nil, err
	}
	req.Header["Content-Type"] = []string{"application/json"}

	res, err := c.client.Perform(req)
	if err != nil {
		return nil, err
	}

	return &esapi.Response{
		StatusCode: res.StatusCode,
		Body:       res.Body,
		Header:     res.Header,
	}, nil
}

func main() {
	es, _ := elasticsearch.NewDefaultClient()
	client := CustomClient{client: es}

	body := strings.NewReader(`
{
	"trigger": { "schedule": { "interval": "10s" } },
	"condition": {  "compare": { "ctx.payload.hits.total": { "gt": 3 } } },
	"input" : {
    "search" : {
      "request" : {
        "indices" : ["test"],
        "body" : {
          "query" : {
            "bool" : {
              "must" : { "match": { "status": 500 } },
              "filter" : { "range": { "@timestamp": { "from": "{{ctx.trigger.scheduled_time}}||-5m", "to": "{{ctx.trigger.triggered_time}}" } } }
            }
          }
        }
      }
    }
  },
	"actions" : {
    "send_email" : {
      "email" : {
        "to" : "example@example.com",
        "subject" : "[ALERT] {{ctx.watch_id}}"
      }
    }
  }
}`)

	log.Println(client.PutWatch("test", body))

	// => 2019/03/30 08:44:51 [201 Created] {"_id":"test","_version":1,"_seq_no":0,"_primary_term":1,"created":true} <nil>
}
```

Basically, you need to implement a method, like `PutWatch()` in this example, creating a `http.Request` with the desired configuration, and pass it to the `elasticsearch.Perform()` method.

This might be helpful until the full support for X-Pack APIs is added.

**Comment by evanfreed** [comment]
Glad to hear it's on the roadmap and thanks for the example 👍 that example will be helpful until then

**Comment by karmi** [comment]
Here's an even more elegant version, which embeds `elasticsearch.Client` directly, so you just call the APIs on a single object:

```golang
log.Println(client.Info())
log.Println(client.PutWatch("test", body))
```

--> https://hastebin.com/eqamizaliy.go

**Comment by karmi** [comment]
I've added a more comprehensive example of extending the clients to custom endpoints here: https://github.com/elastic/go-elasticsearch/tree/master/_examples/extension

I'll keep this issue open and close it when the full X-Pack APIs are added.

**Comment by phillbaker** [comment]
@karmi - just curious, would that also include support for the kibana apis?

**Comment by karmi** [comment]
@phillbaker , there's no immediate plan, we still need to figure out the format of the specification etc., but there are ongoing conversations on how to support the Kibana APIs in the official clients.

**Comment by karmi** [comment]
I forgot to close this issue — the X-Pack APIs have been added in https://github.com/elastic/go-elasticsearch/commit/6da7fa0091af3419822d692f78575b0ca7244713. See the documentation for the [_Watcher_](https://godoc.org/github.com/elastic/go-elasticsearch/esapi#Watcher) APIs.
