### ISSUE TITLE
Run bugfix release to pull in Bulk Indexer Memory Leak

### ISSUE THREAD

**Issue by wmorgan6796** [elastic/go-elasticsearch#402]
I've been using the Bulk Indexer as part of a production application and noticed frequent OOMs on high throughput scenarios. This lead me [here](https://github.com/elastic/go-elasticsearch/issues/232), where I saw the fix was landed to main on this [PR](https://github.com/elastic/go-elasticsearch/pull/315). But there hasn't been a release since this has landed and I now have to pull off main to prevent OOMs from happening.

Is there any chance we can get a minor release to pull this in?

**Comment by Anaethelion** [comment]
Hi @wmorgan6796 

This fix is due for the next 8.0 release, there is already an v8.0.0-alpha pre-release that you can use right now for testing!

**Comment by wmorgan6796** [comment]
@Anaethelion our team is stuck on ES 7. Is ES 8 version compatible ES 7?

**Comment by Anaethelion** [comment]
@wmorgan6796 While there is no guarantee for forward compatibility you already are using the code for the 8 version if you are currently running `main`, in your use case you should be fine.

Backporting this change to the 7 branch would unfortunately break the API which is currently not in our plan.
