### ISSUE TITLE
how to use the search api with POST method by the default client

### ISSUE THREAD

**Issue by Suozz** [elastic/go-elasticsearch#41]

**Comment by karmi** [comment]
Hi, can you provide some information about the Elasticsearch version you're executing the requests against, and also about the environment (ie. is any proxy involved) and hosting (ie. how is the cluster deployed/hosted)?

**Comment by karmi** [comment]
Hello, any news here? Search API should work with a `GET` request under normal circumstances, so that's why I'm wondering about the environment.

**Comment by martinrode** [comment]
Could we reopen this issue? Migrating from "github.com/olivere/elastic", i am trying to use POST for the _search api. It is important to us, because our queries are sometimes longer than GET permits.
