### ISSUE TITLE
BulkIndexer is using _routing instead of routing

### ISSUE THREAD

**Issue by HassanAlgoz** [elastic/go-elasticsearch#425]
It seems that the [bulk_indexer.go](https://github.com/elastic/go-elasticsearch/blob/c9c1cadf489fc4d543ab5c4dc033f90665d85a21/esutil/bulk_indexer.go#L427-L435) is using the deprecated field name `"_routing"` [instead of `"routing"`](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/docs-bulk.html#bulk-routing), which outputs the following error:

```
flush: [400 Bad Request] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_routing]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_routing]"},"status":400}
```

This is my error handler and how I pass the Routing field in `v7.16`:

```go
bi, _ := esutil.NewBulkIndexer(esutil.BulkIndexerConfig{
	// ...
	OnError: func(c context.Context, e error) {
		log.Printf("Error: %v", e)
	},
})

bi.Add(
	context.Background(),
	esutil.BulkIndexerItem{
		Action: "index",
		Routing: "1",
		DocumentID: id,
		Body: bytes.NewReader(data),
	}
)
```

I am using the image: `docker.elastic.co/kibana/kibana:7.16.2`.

Am I missing something?

**Comment by TradeFace** [comment]
Thanks for the fix. Could you please republish this release?

**Comment by Anaethelion** [comment]
Hi @TradeFace sorry for the delay, the 7.17.1 has just been released with the fix!
