### ISSUE TITLE
Tags for previous versions

### ISSUE THREAD

**Issue by vonafor** [elastic/go-elasticsearch#43]
The repository contains the only tags: v.0.0.0 and v.7.0.0-rc1.

Could you please add tags for v.6.0.0 and v.5.0.0? It'll make possible to use gopkg.in

**Comment by karmi** [comment]
Hi, yes, I'm planning to do that in the next couple of days, probably over the weekend.

**Comment by karmi** [comment]
I've pushed the `v7.0.0`, `v6.7.0` and `v5.6.0` releases to Github, so they should now properly resolve.

(Not sure if it's gonna work well with gopkg.in, though, since the import paths use the `.../vX` suffixes...)

**Comment by vonafor** [comment]
Thank you.

Yeah, it's not working :)

**Comment by karmi** [comment]
... on the other hand, I think the versioning support of gopkg.in is not needed with the support for modules in recent Go versions — it should work out of the box with eg. `require github.com/elastic/go-elasticsearch/v7 v7.0.0`.
