### ISSUE TITLE
How can I search part of a word?

### ISSUE THREAD

**Issue by delgec** [elastic/go-elasticsearch#437]
Hello everyone

I just want to search part of a word. 

Example word: Bitcoin
Search term: **bitc**

How can I make it?

My query:
```
GET /news_index/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "multi_match": {
            "query": "bitc",
            "fields": [
              "title",
              "description"
            ],
            "operator": "or"
          }
        }
      ]
    }
  }
}
```

**Comment by Anaethelion** [comment]
We use GitHub issues for verified bug reports, feature requests, and pull requests.
This is a question, and we'd like to direct these kinds of things to the [Elastic Discuss Forum](https://discuss.elastic.co/c/elastic-stack/). If you can stop by there, we'd appreciate it.

As a pointer in a possible direction depending on your exact need, you might want to have a look at the [wildcard query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html).
