### ISSUE TITLE
Incorrect HTTP method for uri [/_field_usage_stats]

### ISSUE THREAD

**Issue by jiangzhikele** [elastic/go-elasticsearch#446]
I want to get es an index field

{"error":"Incorrect HTTP method for uri [/_field_usage_stats] and method [GET], allowed: [POST]","status":405}
![image](https://user-images.githubusercontent.com/38905258/157797605-17339274-3070-41f4-ad6c-bb0186521d23.png)

**Comment by Anaethelion** [comment]
I've tried replicating your issue but things are working as expected.

Can you please give more context on what version of the client you are using ?
To help you debug you can add a logger to the client's config like:

```go
config := elasticsearch.Config{
    Logger: &estransport.ColorLogger{os.Stdout, true, true},
}
c, _ := elasticsearch.NewClient(config)
```

A way this can happen is if you pass an empty string in the `Index` parameter, URL building would then fail to properly be constructed and you would request a different endpoint from what you are expecting.
