### ISSUE TITLE
Retry option in go-elasticsearch

### ISSUE THREAD

**Issue by amanjain97** [elastic/go-elasticsearch#45]
I want to implement the retry of the connection to elasticsearch. But I could not find any proper documentation or sample snippet regarding the issue.
Can someone please guide how to implement retry feature.

**Comment by karmi** [comment]
Hello, what specific use case you have in mind for a retry — eg. retrying on a different node when the actual request failed? Something like that is on the roadmap, it's a set of features common to all clients.

As for implementing something like this now, you'd have to wrap the Transport in a custom type, and do the retries in the `RoundTrip`, following eg. the example in https://github.com/elastic/go-elasticsearch/blob/master/_examples/customization.go.

Alternatively, you can implement [`estransport.Interface`](https://github.com/elastic/go-elasticsearch/blob/321640ebc6646d13860d9221d3582f736f59eeb1/estransport/estransport.go#L27) in a custom type, and pass it to the client.

**Comment by amanjain97** [comment]
I want to retry to the same es-host if the connection is failed.
Something like this: https://github.com/olivere/elastic/wiki/Retrier-and-Backoff

**Comment by amanjain97** [comment]
Thanks for the quick response. It is resolved

**Comment by karmi** [comment]
Glad to hear! Closing the issue then.
