### ISSUE TITLE
Example for using MSearch API

### ISSUE THREAD

**Issue by codecandy2015** [elastic/go-elasticsearch#450]
I am able to get Multi search results directly from the Elastic Search API using _msearch for the following request Body

`
{"index":"csv1"}
{"query" : {"match" : {"_meta._clusterID": "8811547417"} }, "size" : 1}

{"index":"csv1"}
{"query" : {"match" : {"_meta._clusterID": "88115479144"} }, "size" : 1}

{"index":"csv2"}
{"query" : {"match" : {"_meta._clusterID": "86443104548"} }, "size" : 1}

{"index":"csv3"}
{"query" : {"match" : {"_meta._clusterID": "86642503112"} }, "size" : 1}`

However, previous suggestions #85   is very difficult to understand how to use the go-elasticsearch API for Msearch. What should the MsearchRequest look like , I tried using the JSON option, It always complains an error.

If someone did use this API, any examples would be highly appreciated.

**Comment by Anaethelion** [comment]
Given the payload you provided and presuming you already have setup the relevant indices:

```go
config := elasticsearch.Config{
	Logger: &elastictransport.ColorLogger{os.Stdout, true, true},
}
c, _ := elasticsearch.NewClient(config)

payload := []byte(`{"index":"csv1"}
{"query" : {"match" : {"_meta._clusterID": "8811547417"} }, "size" : 1}
{"index":"csv1"}
{"query" : {"match" : {"_meta._clusterID": "88115479144"} }, "size" : 1}
{"index":"csv2"}
{"query" : {"match" : {"_meta._clusterID": "86443104548"} }, "size" : 1}
`)

res, err := c.API.Msearch(bytes.NewReader(payload))
if err != nil {
	log.Fatalln(err)
}
defer res.Body.Close()

fmt.Println(res.Body)
```

Notice the lack of space between the header and the body part of each request. There should also be a newline character at the very end of the payload.
