### ISSUE TITLE
Open Telemetry Support.

### ISSUE THREAD

**Issue by kutty-kumar** [elastic/go-elasticsearch#459]
Hi Folks, 
i would like to know if there's support for open telemetry in the existing library, Something similar to otel-redis and otel-mongo. Using which we can trace API calls.

**Comment by Anaethelion** [comment]
Hi @kutty-kumar 

We do have an example for APM and OpenCensus that you can find [here](../tree/main/_examples/instrumentation), if you want to use `otel` you can do something like this :

```go
cfg := elasticsearch.Config{
    Addresses: []string{"http://localhost:9200"},
    Transport: otelhttp.NewTransport(http.DefaultTransport),
}

client, err := elasticsearch.NewClient(cfg)
if err != nil {
     log.Fatalln(err)
}

res, err := client.Info()
if err != nil {
     log.Fatalln(err)
}
defer res.Body.Close()
```

Which configured with the exporter of your choice can do the trick and trace API calls!

**Comment by kutty-kumar** [comment]
thanks @Anaethelion will try and check this out
