### ISSUE TITLE
Malformed action/metadata line [339], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]

### ISSUE THREAD

**Issue by veqryn** [elastic/go-elasticsearch#460]
I am reading from a file containing newline delimited json (written by a golang process), with each line containing a single json line.
I am adding these lines to a BulkIndexer one at a time.
A little while after starting the process, I always get this error:
```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Malformed action/metadata line [339], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]"}],"type":"illegal_argument_exception","reason":"Malformed action/metadata line [339], expected START_OBJECT or END_OBJECT but found [VALUE_STRING]"},"status":400}
```

When I turn on debugging, I can see the requests being made, with most of them being fine, such as:
```
{"index":{}}
{"lang":"en","text":"blah blah blah"}
```

But then I find one like this in the last request made (the one that errored):
```
{"index":{}}
h blah"}
{"lang":"en","text":"blah bla
```

When I check my input file, the line containing that info is valid and on a single line, so I don't know how on earth this is getting messed up when put into the BulkIndexer.

**Comment by veqryn** [comment]
Ok, turns out that I was using a bufio.NewScanner on my file, then getting the scanner.Bytes(), and sending the bytes to the BulkIndexer.
I didn't realize the BulkIndexer is running in a separate goroutine and reading those additions asynchronously, which meant that there was a race and the bytes were getting overwritten by the next read.
Problem solved by moving to scanner.Text()

**Comment by Anaethelion** [comment]
A solution seem to have been found to the initial issue, closing.
