### ISSUE TITLE
how to insert one document to a index with automatic _ID

### ISSUE THREAD

**Issue by Suozz** [elastic/go-elasticsearch#47]

**Comment by karmi** [comment]
You can just leave the ID argument out when calling the [Index API](https://godoc.org/github.com/elastic/go-elasticsearch/esapi#Index):

```golang
es.Index("myindex", mybody)
```

Or, when using the request struct, like this: https://github.com/elastic/go-elasticsearch/blob/36b236c0f9d7508ee34826303a67fba36f38810c/_examples/main.go#L67-L72

leave out the `DocumentID` field.

**Comment by Suozz** [comment]
> You can just leave the ID argument out when calling the [Index API](https://godoc.org/github.com/elastic/go-elasticsearch/esapi#Index):
> 
> ```go
> es.Index("myindex", mybody)
> ```
> 
> Or, when using the request struct, like this:
> 
> [go-elasticsearch/_examples/main.go](https://github.com/elastic/go-elasticsearch/blob/36b236c0f9d7508ee34826303a67fba36f38810c/_examples/main.go#L67-L72)
> 
> Lines 67 to 72 in [36b236c](/elastic/go-elasticsearch/commit/36b236c0f9d7508ee34826303a67fba36f38810c)
> 
>  req := esapi.IndexRequest{ 
>  	Index:      "test", 
>  	DocumentID: strconv.Itoa(i + 1), 
>  	Body:       strings.NewReader(`{"title" : "` + title + `"}`), 
>  	Refresh:    "true", 
>  } 
> leave out the `DocumentID` field.

thank you. this helps me a lot
