### ISSUE TITLE
only v0.0.0 support dep

### ISSUE THREAD

**Issue by wlacp** [elastic/go-elasticsearch#48]
only v0.0.0 support dep, v0.0.0 is not the lastest.

![1556448336672](https://user-images.githubusercontent.com/34258886/56863192-f88e1880-69e5-11e9-8713-d815ebd56f7f.jpg)

**Comment by karmi** [comment]
Hi, yeah, `dep` doesn't seem to support the [version suffixes](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher) of Go modules. The `go mod init` command supports [migrating from `dep`](https://github.com/golang/go/wiki/Modules#automatic-migration-from-prior-dependency-managers), is that a good option for you?

**Comment by wlacp** [comment]
Another, How can I use basic auth at v0.0.0

**Comment by karmi** [comment]
Don't use v0.0.0 — that's an old version.

Either add the credentials to the `ELASTICSEARCH_URL` variable, or set the corresponding fields in the config struct:

https://github.com/elastic/go-elasticsearch/blob/36b236c0f9d7508ee34826303a67fba36f38810c/elasticsearch.go#L26-L33
