### ISSUE TITLE
Health check, ping etc

### ISSUE THREAD

**Issue by delgec** [elastic/go-elasticsearch#482]
Hello everyone!

How can I check if the service is running or not?

I need a health check or ping func

I searched but I didn't find anything.

Help me pls.

**Comment by volgorean** [comment]
@delgec I just use the [Info](https://github.com/elastic/go-elasticsearch/blob/f2f14d4e0a3e04328eb26ac888ea17833918df7a/esapi/api.info.go#L44) function available on the base es client:
```go
es, err := elasticsearch.NewDefaultClient()
if err != nil {
  panic(err)
}
res, err := es.Info()
if err != nil {
  panic(err)
}
fmt.Println(res.Status())
fmt.Println(res.String())
```

If no errors are returned and you get a 200 status code you should be good to go.

You could alternatively use [CatHealth](https://github.com/elastic/go-elasticsearch/blob/f2f14d4e0a3e04328eb26ac888ea17833918df7a/esapi/api.cat.health.go#L45) if you wanted to get the health of all known clusters although the `/_cat` endpoints are officially `only intended for human consumption using the command line or Kibana console`.

**Comment by Anaethelion** [comment]
Thank you @volgorean for this wonderful answer.

I'll proceed to close this issue!
