### ISSUE TITLE
How to specify the search function  returned fields

### ISSUE THREAD

**Issue by zhangtao-sw** [elastic/go-elasticsearch#484]
Hello,
i want to know how to specify the search function  returned fields

With the following code, res contains all the fields of this index.

import elasticsearch7 "github.com/elastic/go-elasticsearch/v7"
	res, err := e.esObj.Search(
		e.esObj.Search.WithContext(context.Background()),
		e.esObj.Search.WithIndex(index),
		e.esObj.Search.WithBody(&buf),
		e.esObj.Search.WithTrackTotalHits(true),
		e.esObj.Search.WithPretty(),
	)

**Comment by Anaethelion** [comment]
Hi @zhangtao-sw 

You need to specify the fields you want to retrieve directly into the payload.
Please have a look at the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html#search-fields-request) with examples on how to do that.
