### ISSUE TITLE
Error: Indices.Exists: EOF

### ISSUE THREAD

**Issue by Jeckerson** [elastic/go-elasticsearch#486]
Currently trying bulk kafka example (https://github.com/elastic/go-elasticsearch/tree/main/_examples/bulk/kafka), which gives error on running the `kafka.go` command.

```
make setup
make run
```

Gives current error:

> go run kafka.go
Error: Indices.Exists: EOF
exit status 1
make: *** [Makefile:12: run] Error 1

Go Version: `go version go1.13.8 linux/amd64`

**Comment by Anaethelion** [comment]
Hi @Jeckerson 

Thank you for reporting this!

I have temporarily disabled the security in https://github.com/elastic/go-elasticsearch/pull/489, this should fix your issue so you can run the example.
Can you check and tell me if this works for you.

**Comment by Jeckerson** [comment]
Now it gives another error:
> go run kafka.go
Initializing... producers=1 consumers=4 indexers=1
ERROR: Producer: dial tcp 127.0.0.1:9092: connect: connection refused
exit status 1
make: *** [Makefile:12: run] Error 1

Which is caused by Kafka server:
> ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.common.InconsistentClusterIdException: The Cluster ID Mc4oIkBwTqGs5CRLGNfljg doesn't match stored clusterId Some(jw9DpObmQq2n5B9bmDlgfw) in meta.properties. The broker is trying to join the wrong cluster. Configured zookeeper.connect may be wrong.
        at kafka.server.KafkaServer.startup(KafkaServer.scala:281)
        at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:140)
        at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:66)

**Comment by Anaethelion** [comment]
Have you tried running a `make clean` before retrying ?

**Comment by Jeckerson** [comment]
> Have you tried running a `make clean` before retrying ?

It worked, thanks!
