### ISSUE TITLE
DeleteByQuery throwing status code 400, action_request_validation_exception, query is missing;

### ISSUE THREAD

**Issue by superman0987** [elastic/go-elasticsearch#487]
So, I'm on the latest version of this library, go-elasticsearch. I am on 7.17 version of elasticsearch.

I have faced a strange issue with the DeleteByQuery api.

I get this error from the api no matter what I do:
`[400 Bad Request] {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: query is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: query is missing;"},"status":400}`

My code:
I have tried this:

```
t := true
d := esapi.DeleteByQueryRequest{
		Index:     []string{customerMaterialsAlias},
		Body:      esutil.NewJSONReader(b),
		Conflicts: "proceed",
		Refresh:   &t,
}
do, err := d.Do(context.Background(), esClient)
if err != nil {
	return err
}
```

Also tried this:

```
deleteByQueryResponse, err := esClient.DeleteByQuery(
		[]string{customerMaterialsAlias},
		esutil.NewJSONReader(b),
		esClient.DeleteByQuery.WithConflicts("proceed"),
		esClient.DeleteByQuery.WithRefresh(true),
	)
```

Both give the same error: `[400 Bad Request] {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: query is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: query is missing;"},"status":400}`

I have tried using aliases as well as index names, it doesn't work, no matter what.

I am posting the body I'm using, as well:
`{"query":{"bool":{"must":[{"query_string":{"fields":["customer_sold_to"],"query":"0030135600"}},{"query_string":{"fields":["customer_ship_to"],"query":"0071010562"}},{"query_string":{"fields":["customer_sales_org"],"query":"2902"}},{"query_string":{"fields":["username"],"query":"peeran"}},{"query_string":{"fields":["searched_language"],"query":"E"}},{"query_string":{"fields":["searched_gimmick_material"],"query":"FALSE"}},{"query_string":{"fields":["searched_exclude_principal"],"query":"NIL"}},{"query_string":{"fields":["searched_pick_and_pack"],"query":"NIL"}}]}}}`

I have tried passing the body as json, as well as a string. Nothing works.

When I run it on Kibana it works fine:
```
POST /customer_material_cache_uat/_delete_by_query?refresh=true&conflicts=proceed
{
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "fields": [
              "customer_sold_to"
            ],
            "query": "0030135600"
          }
        },
        {
          "query_string": {
            "fields": [
              "customer_ship_to"
            ],
            "query": "0071010562"
          }
        },
        {
          "query_string": {
            "fields": [
              "customer_sales_org"
            ],
            "query": "2902"
          }
        },
        {
          "query_string": {
            "fields": [
              "username"
            ],
            "query": "peeran"
          }
        },
        {
          "query_string": {
            "fields": [
              "searched_language"
            ],
            "query": "E"
          }
        },
        {
          "query_string": {
            "fields": [
              "searched_gimmick_material"
            ],
            "query": "FALSE"
          }
        },
        {
          "query_string": {
            "fields": [
              "searched_exclude_principal"
            ],
            "query": "NIL"
          }
        },
        {
          "query_string": {
            "fields": [
              "searched_pick_and_pack"
            ],
            "query": "NIL"
          }
        }
      ]
    }
  }
}
```

Is this a bug or am I doing something wrong? Kindly help in guiding what could be going wrong.

**Comment by superman0987** [comment]
Solved it by using 

bytes.NewReader(b)

in the body

**Comment by superman0987** [comment]
Why didn't esutil.NewJSONReader(b) work? Is this a bug? Can someone confirm?

**Comment by superman0987** [comment]
Ok, so esutil.NewJSONReader(b) can not work because I have to pass it something like a struct or a map, but also as a reference. so, esutil.NewJSONReader(&someMap), or esutil.NewJSONReader(&someStruct) would work. It did for me. Cannot we make it such that we can pass JSON or string to this function too?

**Comment by Anaethelion** [comment]
Hi @superman0987 

Glad you figured that out, however the purpose of the `JSONReader` is to provide an easier way to get a reader from a serializable structure which is encoded to json via the `encoding/json` package.
Should you already have a string with a JSON inside you only need to create a new reader for the body and need no further serialization for your payload.
