### ISSUE TITLE
Why are files executable

### ISSUE THREAD

**Issue by pratz** [elastic/go-elasticsearch#49]
Almost all files seem to be executable, seems like a mistake
<img width="854" alt="Screen Shot 2019-05-08 at 9 23 53 am" src="https://user-images.githubusercontent.com/925565/57339190-fe1cf880-7173-11e9-8327-f9ea1d7039cc.png">

**Comment by karmi** [comment]
Hi, this is surely some kind of mistake, just not sure how did it happen... If we wanna fix it, it's gonna be a massive changeset in the Git...

**Comment by karmi** [comment]
I'm gonna do some pretty invasive changes to the generated code soon, adding the X-Pack APIs, so I'm gonna keep this in mind, and correct the file permission bits as part of that change.
