### ISSUE TITLE
Pending items for v1

### ISSUE THREAD

**Issue by 7AC** [elastic/go-elasticsearch#5]
## `generator/api`
- [ ] figure out how we end up with the wrong package name in some cases (`do.tmpl`)
- [ ] add typed accessors and/or fields to structured responses (e.g., to `api.IndexResponse`). Changes should go to `generator/api/templates/method.tmpl`
- [ ] handle multiple HTTP methods in index
- [ ] render `bulk` and `dict` types in `Param.String()`

## `client`
- [ ] we should find a trick to link to `api` from `client` in godoc, so people can see the API methods embedded in `client.Client` more clearly
- [ ] support additional client options (`client/option.go`)

## `generator/test`
- [ ] resolve variables set by `set` before using them in other actions (right now they stay as `$<var>`)
- [ ] implement `catch` et al
- [ ] implement regex matching in `generator/test/action/match.go`
- [ ] implement `generator/test/action/skip.go` to skip tests
- [ ] keep raw name for test as comment to test (`testcase.go`/`test.tmpl`)

## Cleanup:
- [ ] remove `t.Skip()` in `test.tmpl`
- [ ] handle variables that are declared and not used in `test.tmpl` (still an issue after all other TODOs?)

## Nits:
- [ ] make type code in `param.go` its own type
- [ ] the code in `generator/test/util_test.go` should be shared with the `generator/api` package.

**Comment by zhaojiexi** [comment]
I have the same problem.
