### ISSUE TITLE
esapi.newRequest doesn't set Body when using esutil.JSONReader

### ISSUE THREAD

**Issue by axw** [elastic/go-elasticsearch#50]
`newRequest` only sets the body for specific types, as seen below. There should be a fallback for other `io.Reader` types.

https://github.com/elastic/go-elasticsearch/blob/e09a105a2b0a111aad7774ae521d6981e7e34e3e/esapi/esapi.request.go#L39-L51

**Comment by karmi** [comment]
Many thanks for catching this! Embarassing...

This has been fixed by 82fc17d.
