### ISSUE TITLE
Bulk insert not reporting errors

### ISSUE THREAD

**Issue by belsakn** [elastic/go-elasticsearch#500]
Hey
I'm using [bulk example ](https://github.com/elastic/go-elasticsearch/blob/main/_examples/bulk/indexer.go) to insert doc to elasticsearch.
Once the bulk insert finishes i get this error message `indexed [3,185,561] documents with [53,239] errors`, but i don't get anything logged in [OnFailure function](https://github.com/elastic/go-elasticsearch/blob/main/_examples/bulk/indexer.go#L218)

and the bulk indexer config:
```
bi, err := esutil.NewBulkIndexer(esutil.BulkIndexerConfig{
		Index:         indexName, // The default index name
		Client:        es.client, // The Elasticsearch client
		ErrorTrace:    true,
		FlushBytes:    int(100000),
		FlushInterval: time.Second * 5,
	})
```

Any thoughts?

**Comment by Anaethelion** [comment]
Hi @belsakn 

The number of errors could also indicate that you are indexing too fast and your cluster cannot keep up.
To investigate this you can specify an `OnError` func in the `BulkIndexerConfig` and log what is happening.

**Comment by belsakn** [comment]
@Anaethelion tnx. Indeed that was the problem. I'm running `builkIndexer` on multiple indices and concurrently. When i add this i got an error `OnError:  flush: [429 Too Many Requests]`. I just removed concurrency
