### ISSUE TITLE
Is it possible to search for multiple document IDs across multiple indices?

### ISSUE THREAD

**Issue by freemj** [elastic/go-elasticsearch#502]
https://github.com/elastic/go-elasticsearch/blob/47706b4dde8e8e20cf98ac513bc7f121b9628eb8/esapi/api.mget.go#L201

api.search WithIndex supports an Index slice but api.mget WithIndex does not and the MgetRequest contains only a single Index string but no document ID.  Without an example it's unclear how Mget can be used to perform a query for multiple document IDs across multiple indices.  The HTTP API is a bit clearer with how this should work: https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-multi-get.html but this does not translate to the Go API.

**Comment by Anaethelion** [comment]
Hi @freemj 

If you want to use mget accross multiple indices you need to specify the indices into your payload an not use the `WithIndex` method the client will then send the request to the `/_mget` endpoint.

In the go client this would translate to:

```go
res, err := client.Mget(strings.NewReader(`{
  "docs": [
	{
	  "_index": "my-index",
	  "_id": "1"
	},
	{
	  "_index": "my-other-index",
	  "_id": "1"
	}
  ]
}`))
```

**Comment by freemj** [comment]
@Anaethelion Is this known to work on the es6 version of the SDK?  I pass in a query with an index and ID that I've verified exist and a payload formatted as you noted above and I always get a Status 200 OK and an empty response body.
