### ISSUE TITLE
Scroll API passes scroll_id in both path and body

### ISSUE THREAD

**Issue by brendancboyle** [elastic/go-elasticsearch#51]
# Summary

The Scroll API takes in a scroll ID to identify subsequent pages. This scroll ID can be passed either through the URL path (`POST /_search/scroll/<scroll_id>`) or through the POST body (`{ scroll_id: "<scroll_id>" }`) per https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html.

In the case of this library, the scroll ID is passed in both the URL path and the POST body. However, this breaks the scroll API in cases where the scroll_id is too long to fit in the URL. When this happens you receive a TCP broken pipe error.

# Steps to reproduce

1. Create a cluster with > 10k shards
2. Fire a search request with a small size and enable scrolling
3. Use the scroll API with this extremely long scroll_id
4. Observe the TCP broken pipe error

# Remediation

Remove the scroll_id from the URL path. This is redundant and is length constrained compared to the POST body.

I believe the code is here: https://github.com/elastic/go-elasticsearch/blob/a30a816423ad91fdae29671a8794a20befde10fd/esapi/api.scroll.go#L65 and here: https://github.com/elastic/go-elasticsearch/blob/a30a816423ad91fdae29671a8794a20befde10fd/esapi/api.clear_scroll.go#L60

<img width="694" alt="Screen Shot 2019-05-11 at 12 03 57 AM" src="https://user-images.githubusercontent.com/1626106/57566358-67715700-7380-11e9-94a2-f0f42feeb6ea.png">

**Comment by karmi** [comment]
Hi @brendancboyle, thanks for the report!

This is a common problem with the clients — they are (intentionally) 1:1 to the REST API, so in order to pass the scroll ID in the body (and prevent the errors), it needs to be set as part of the body, and not via the `WithScrollID()` method:

```golang
client.Scroll(client.Scroll.WithBody(strings.NewReader(`{"scroll_id":"foobar"}`)))
```

That said, it's quite a common problem, so I'll have a look into special handling the scroll ID, and sending it in the body either always, or if it's above a certain length. I'm usually reluctant to add "smart" behaviour like this to the low-level clients, but I can see how this can be confusing.

**Comment by brendancboyle** [comment]
Ah okay! Thanks for the help, I totally forgot I could use WithBody to get around this.

**Comment by brendancboyle** [comment]
Actually @karmi couldn't you just remove the path parameter as you already set the body value here: https://github.com/elastic/go-elasticsearch/blob/a30a816423ad91fdae29671a8794a20befde10fd/esapi/api.scroll.go#L81

I think this would not interfere with the goal of remaining low level but will allow users to intuitively use the API

**Comment by karmi** [comment]
Looking at the code, I think the first problem is that it actually duplicates the parameter in the URL path and parameters, when the `ScrollID` is set. First it sets it here, as part of the path: https://github.com/elastic/go-elasticsearch/blob/a30a816423ad91fdae29671a8794a20befde10fd/esapi/api.scroll.go#L65-L68

and then on the line you mention: https://github.com/elastic/go-elasticsearch/blob/a30a816423ad91fdae29671a8794a20befde10fd/esapi/api.scroll.go#L80-L82

Looking into the [REST API spec](https://github.com/elastic/elasticsearch/blob/ac34af563cde1f04fb58336553b062a28eab1832/rest-api-spec/src/main/resources/rest-api-spec/api/scroll.json#L12), it lists the URL path as deprecated — for good reasons, as you've discovered.

I was thinking about passing the scroll ID in the body in the meantime, and it would be quite tricky, actually — as opposed to eg. the Ruby client, the body for the Go client is an opaque value, `io.Reader`, and I wouldn't like to eg. create a `bytes.Buffer` on the fly. More importantly, if somebody would use both `WithScrollID()` and `WithBody()` — quite incorrect approach, but valid on the API level —, I wouldn't have a good way to reach inside the passed body.

I think the right approach here would be to make sure the duplication is fixed, and add a good example for scrolling, like I did for [bulk](https://github.com/elastic/go-elasticsearch/blob/master/_examples/bulk/bulk.go), with explanations in code annotations, and a ready-to-adapt code. What do you think?

**Comment by brendancboyle** [comment]
Okay I see exactly what you mean. Yes, trying to augment the body seems quite anti-pattern in this case. I think strengthening the docs with examples on correct usage would help people understand the API a bit better. That said, I would potentially do this in the GoDocs around the functions of interest as it is relevant to their invocation (for instance talk about limits regarding `WIthScrollID()`). Another novel solution would be to throw a runtime error during `WithScrollID()` if the id is too long. This can help users properly diagnose the issue without hopping into the esapi code.

**Comment by karmi** [comment]
Thanks for the conversation! I'll look into fixing the code generator and updating the API later in the week.

**Comment by karmi** [comment]
I've added an override to the generator, and merged the fixes to `master`, `7.x`, `6.x` and `5.x`.

**Comment by tobinski** [comment]
This error  happens also with the new typed API (v8.11.1). If I try to scroll a search result `typedClient.Scroll().ScrollID(scrollID).Do(ctx)` I hit a 400 error. The error has the same roots as this one. The request sends the scrollID in the body and the URL path.

**Comment by frkntplglu** [comment]
> This error happens also with the new typed API (v8.11.1). If I try to scroll a search result `typedClient.Scroll().ScrollID(scrollID).Do(ctx)` I hit a 400 error. The error has the same roots as this one. The request sends the scrollID in the body and the URL path.

Could you solve this problem? My problem is that typedClient cannot add the scroll id into the body. I couldn't solve this.
