### ISSUE TITLE
Assistance on how to configure the go-elasticsearch client to not use cached IPs while using Opensearch service.

### ISSUE THREAD

**Issue by akashbalaraj** [elastic/go-elasticsearch#527]
## What version of Go are you using (go version)?

go version go1.16.14 darwin/amd64

## What version of go-elasticsearch are you using (go-elasticsearch version)?

Client version : github.com/elastic/go-elasticsearch/v8 

## What did you do?

We see that the go-elasticsearch client was not able to reach the aws elasticsearch at the end of cluster upgrade when old nodes were getting deleted. Client(go-elasticsearch) was not able to reach aws ES for at least 10 minutes with connection timeout error before connection getting reset and it started working fine.

Did check with the AWS Elasticsearch team, They mentioned that 
> Issue exists with go-elasticsearch client, when a configuration change is made to elasticsearch, A new fleet of nodes is launched to match the desired configuration. These new nodes are joined to the cluster with new IP addresses. Data is then moved from the old nodes to these new nodes and once this is complete then the new nodes take over completely and the old nodes with their old IP addresses are terminated.
If a client is configured to use persistent http/https connections then in the client itself the old node IPs are still being used and hence the connection will fail until the endpoint is updated with new node IPs depending on how long the persistent connection is set up to last.

By default, This is how our client looks like
```
func (esClient *ESClient) Init(esUrl string) {

	var err error
	esClient.client, err = es.NewClient(es.Config{
		Addresses: []string{
			esUrl,
		},
	})
	...
	...

}
```

We tried the following things to fix the issue, Unfortunately, None of them worked.

1. Disabling persistent connections by Setting the **DisableKeepAlives:true**.

```
func (esClient *ESClient) Init(esUrl string) {

    var err error
    esClient.client, err = es.NewClient(es.Config{
        Addresses: []string{
            esUrl,
        },
        Transport: &http.Transport{
            // Disable long-lived connection
            DisableKeepAlives: true,
            TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
        },
    })
    ...
    ...
}
``` 

2. Closing the idle connection every 3 seconds.

```
func (esClient *ESClient) Init(esUrl string) {

    var err error

    Transport := &http.Transport{
        // Disable long-lived connection
        DisableKeepAlives: true,
        TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    }

    go func(transport *http.Transport) {
        for {
            time.Sleep(3 * time.Second)
            transport.CloseIdleConnections()
        }
    }(Transport)

    esClient.client, err = es.NewClient(
        es.Config{
        Addresses: []string{
            esUrl,
        },
        Transport: Transport,        
    })
    ...
    ...
}

```

3. Tried Setting **DiscoverNodesOnStart** and **DiscoverNodesInterval** for initial and periodic sniffing, 
But the client didn't start, Started seeing the below error. "msg":"Error getting response","error":"dial tcp :443: connect: connection refused"
```
func (esClient *ESClient) Init(esUrl string) {

    var err error

    Transport := &http.Transport{
        // Disable long-lived connection
        DisableKeepAlives: true,
        TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    }

    go func(transport *http.Transport) {
        for {
            time.Sleep(3 * time.Second)
            transport.CloseIdleConnections()
        }
    }(Transport)

    esClient.client, err = es.NewClient(
        es.Config{
        Addresses: []string{
            esUrl,
        },
        Transport: Transport,
        DiscoverNodesOnStart: true,
        DiscoverNodesInterval: 60 * time.Second,
    })
    ...
    ...    
}  
```

## What did you expect to see?

I expect all requests to pass without any failures throughout the cluster upgrade

## What did you see instead?

Connection timeout from go-elasticsearch client at the end of cluster upgrade.

**Comment by Anaethelion** [comment]
While I cannot give you specific support on your infrastructure, here is some general advice.

The `DiscoverNodesOnStart` and `DiscoverNodesInterval` is definitely the right way to do that at the client level. I would recommend you lower the interval, 60 seconds seems a lot if node are coming and going from the cluster. Furthermore, the discovery if enabled is [triggered on start](https://github.com/elastic/go-elasticsearch/blob/5653c7576e1e5ad7a4614af7bdacfcb1a95880e0/elasticsearch.go#L178) and relies on [the transport](https://github.com/elastic/elastic-transport-go/blob/8245a9edc85c67c63fd154d9578b01dc2204b3a0/elastictransport/discovery.go#L122) to make a call to `/_nodes/http`. I don't know the specifics for OpenSearch, but for Elasticsearch, the user would need the `monitor` or `manage` permission to access the nodes list. Of course, the first node you target should still be live and part of the cluster to have relevant informations.

I find odd the AWS support states there's an issue with the client while they could have provided the idea of adding a Load Balancer in front of the cluster which would have taken care of the no downtime scenario.
[Elastic Cloud](https://www.elastic.co/cloud/) does that for you, you are provided with a simple endpoint and we take care of routing, updates and upgrades for you. You can even reach us via the [AWS Marketplace](https://aws.amazon.com/marketplace/pp/prodview-voru33wi6xs7k)!

**Comment by akashbalaraj** [comment]
Thanks for your suggestion. 

As mentioned we tried `DiscoverNodesOnStart` and `DiscoverNodesInterval` (5 sec), I see client is coming up, But calls to elasticsearch is not happening.  I see the following error :
"dial tcp :443: connect: connection refused"

I don't see any issue with the permission as we invoke */_nodes/http*, 

Below is the snippet of the response from */_nodes/http* :

```
{
  "_nodes": {
    "total": 17,
    "successful": 17,
    "failed": 0
  },
  "cluster_name": "10xxxxxx98:xxx-xxxx-elasticsearch",
  "nodes": {
    "Xysv2xxxxxxxU_lFOUdUQ": {
      "name": "e9dd66340f69xxxxxxxxxb9000bab3",
      "version": "7.10.2",
      "build_flavor": "oss",
      "build_type": "tar",
      "build_hash": "unknown",
      "roles": [
        "master",
        "remote_cluster_client"
      ]
    },
    "ZHAdCWexxxxxxxQljIY2A": {
      "name": "77c9a4a828b700xxxxxxxxx3298c615e4",
      "version": "7.10.2",
      "build_flavor": "oss",
      "build_type": "tar",
      "build_hash": "unknown",
      "roles": [
        "data",
        "ingest",
        "remote_cluster_client"
      ]
    },
    "obbtysuOQFuaWkbkpWe98g": {
      "name": "e39a13412b50ab86074babe5dc06c215",
      "version": "7.10.2",
      "build_flavor": "oss",
      "build_type": "tar",
      "build_hash": "unknown",
      "roles": [
        "data",
        "ingest",
        "remote_cluster_client"
      ]
    },
    ...
    ...
``` 

Is the above fetched information from the elasticsearch cluster is enough for the `DiscoverNodesOnStart` to work ? Or does it require any other more data ?

**Comment by Anaethelion** [comment]
Using the makefile at the root of this repo, I ran:
`make cluster nodes=3`
`curl http://127.0.0.1:9200/_nodes/http | jq`

From there you get a payload that is roughly similar to this:

```json
{
  "_nodes": {
    "total": 3,
    "successful": 3,
    "failed": 0
  },
  "cluster_name": "go-elasticsearch",
  "nodes": {
    "u0r1m6NhQW6Gg7sdIiNaDg": {
      "name": "es3",
      "transport_address": "172.24.0.4:9300",
      "host": "172.24.0.4",
      "ip": "172.24.0.4",
      "version": "8.5.0",
      "build_flavor": "default",
      "build_type": "docker",
      "build_hash": "5d6af5890f70cfdb234240f7a1d8c65c6339315d",
      "roles": [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ],
      "attributes": {
        "testattr": "test",
        "ml.machine_memory": "33563676672",
        "ml.max_jvm_size": "1073741824",
        "xpack.installed": "true",
        "ml.allocated_processors": "24"
      },
      "http": {
        "bound_address": [
          "0.0.0.0:9200"
        ],
        "publish_address": "172.24.0.4:9200",
        "max_content_length_in_bytes": 104857600
      }
    },
    "CL0JM2OnSjWqtKVZxBTZIw": {
      "name": "es1",
      "transport_address": "172.24.0.2:9300",
      "host": "172.24.0.2",
      "ip": "172.24.0.2",
      "version": "8.5.0",
      "build_flavor": "default",
      "build_type": "docker",
      "build_hash": "5d6af5890f70cfdb234240f7a1d8c65c6339315d",
      "roles": [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ],
      "attributes": {
        "ml.machine_memory": "33563676672",
        "ml.allocated_processors": "24",
        "ml.max_jvm_size": "1073741824",
        "xpack.installed": "true",
        "testattr": "test"
      },
      "http": {
        "bound_address": [
          "0.0.0.0:9200"
        ],
        "publish_address": "172.24.0.2:9200",
        "max_content_length_in_bytes": 104857600
      }
    },
    "9170hztBRqqdnzXMEF8GTg": {
      "name": "es2",
      "transport_address": "172.24.0.3:9300",
      "host": "172.24.0.3",
      "ip": "172.24.0.3",
      "version": "8.5.0",
      "build_flavor": "default",
      "build_type": "docker",
      "build_hash": "5d6af5890f70cfdb234240f7a1d8c65c6339315d",
      "roles": [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ],
      "attributes": {
        "testattr": "test",
        "ml.machine_memory": "33563676672",
        "ml.max_jvm_size": "1073741824",
        "xpack.installed": "true",
        "ml.allocated_processors": "24"
      },
      "http": {
        "bound_address": [
          "0.0.0.0:9200"
        ],
        "publish_address": "172.24.0.3:9200",
        "max_content_length_in_bytes": 104857600
      }
    }
  }
}
```

Notice how your payload differs and lacks the `publish_address` field which the transport seeks to register nodes addresses.
