### ISSUE TITLE
basic auth in last version not Configuration

### ISSUE THREAD

**Issue by wlacp** [elastic/go-elasticsearch#53]
If I have a elasticsearch cluster but have no Authentication，I can not use it

**Comment by karmi** [comment]
Have you seen the example in here?
https://github.com/elastic/go-elasticsearch/blob/1f1c46082c7d36cd09ab052b2c1283a83aa754ff/doc.go#L13-L19

Also, if you export the `ELASTICSEARCH_URL` with the username and password, it will be picked up.
