### ISSUE TITLE
Error is nil for client side validation errors

### ISSUE THREAD

**Issue by kuhuAvtx** [elastic/go-elasticsearch#530]
If an erroneous combination of `withIndex(...)` is used with Point in time for a Search query the error is returned as a response json without an associated error object (which is nil) signifying a valid response which is misleading. 

Example: 
``````
"{\n  \"error\" : {\n    \"root_cause\" : [\n      {\n        \"type\" : \"action_request_validation_exception\",\n        \"reason\" : \"Validation Failed: 1: [indices] cannot be used with point in time. Do not specify any index with point in time.;\"\n      }\n    ],\n    \"type\" : \"action_request_validation_exception\",\n    \"reason\" : \"Validation Failed: 1: [indices] cannot be used with point in time. Do not specify any index with point in time.;\"\n  },\n  \"status\" : 400\n}\n"
```
yields err object as `nil` which seems incorrect and reduces ease of debugging.

Appreciate comments on the issue.

**Comment by Anaethelion** [comment]
Hi @kuhuAvtx 

The API you are referring to is low-level oriented client, which means only the actual HTTP layer and below errors are returned as such.
The error object being `nil` indicates that there was no error during the roundtrip between the client and the server.

There is an `IsError` method on the response that allows you to know if the response body contains an error from Elasticsearch.
