### ISSUE TITLE
Error EOF on es.Info()

### ISSUE THREAD

**Issue by yoseptara** [elastic/go-elasticsearch#531]
Hello I just started learning golang and I found this issue when I try to use this library.

error : ![Screen Shot 2022-09-16 at 11 49 58](https://user-images.githubusercontent.com/49258329/190552744-9e715a81-a038-4d39-80e5-2cc444a1fb9a.png)

Steps I took to get this error :

- Configure elasticsearch docker image:

1. Run: docker pull elasticsearch
2. Run: docker network create somenetwork
3. Run : docker run -d --name elasticsearch --net somenetwork -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:8.4.0

- Create elasticsearch example project contains 3 files :

1. go.mod :
```
module my-elasticsearch-app

go 1.19

require github.com/elastic/go-elasticsearch/v8 v8.4.0

require github.com/elastic/elastic-transport-go/v8 v8.1.0 // indirect
```

2. go.sum :
```
github.com/elastic/elastic-transport-go/v8 v8.1.0 h1:NeqEz1ty4RQz+TVbUrpSU7pZ48XkzGWQj02k5koahIE=
github.com/elastic/elastic-transport-go/v8 v8.1.0/go.mod h1:87Tcz8IVNe6rVSLdBux1o/PEItLtyabHU3naC7IoqKI=
github.com/elastic/go-elasticsearch/v8 v8.4.0 h1:Rn1mcqaIMcNT43hnx2H62cIFZ+B6mjWtzj85BDKrvCE=
github.com/elastic/go-elasticsearch/v8 v8.4.0/go.mod h1:yY52i2Vj0unLz+N3Nwx1gM5LXwoj3h2dgptNGBYkMLA=
```

3. main.go :
```
package main

import (
	"log"

	"github.com/elastic/go-elasticsearch/v8"
)

  func main() {
    es, err := elasticsearch.NewDefaultClient()
    if err != nil {
      log.Fatalf("error creating client : %s", err)
    }
    log.Println(elasticsearch.Version)

    res, err := es.Info()
    if err != nil {
      log.Fatalf("error getting elastic search client info : %s", err)
    }
    defer res.Body.Close()
    log.Println(res)
  }
```

- Run : go run main.go

**Comment by Anaethelion** [comment]
Hi @yoseptara 

The EOF you get is most likely coming from the Elasticsearch server cutting the connection because you are trying to access it in HTTP instead of HTTPS.

To solve this you can configure your client to use the server's [generated CA and admin credentials](https://www.elastic.co/guide/en/elasticsearch/client/go-api/current/connecting.html#connecting-to-self-managed).

**Comment by taracakeplabs** [comment]
> Hi @yoseptara
> 
> The EOF you get is most likely coming from the Elasticsearch server cutting the connection because you are trying to access it in HTTP instead of HTTPS.
> 
> To solve this you can configure your client to use the server's [generated CA and admin credentials](https://www.elastic.co/guide/en/elasticsearch/client/go-api/current/connecting.html#connecting-to-self-managed).

Thank you for the reply, I ended up following this configuration documentation : https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-compose-file

And now it works.

**Comment by yoseptara** [comment]
> Hi @yoseptara
> 
> The EOF you get is most likely coming from the Elasticsearch server cutting the connection because you are trying to access it in HTTP instead of HTTPS.
> 
> To solve this you can configure your client to use the server's [generated CA and admin credentials](https://www.elastic.co/guide/en/elasticsearch/client/go-api/current/connecting.html#connecting-to-self-managed).

Thank you for the reply, I ended up following this configuration documentation : https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-compose-file

And now it works.
