### ISSUE TITLE
How can I pass parameters to a query by using 'SQLQueryRequest'?

### ISSUE THREAD

**Issue by Linkyx** [elastic/go-elasticsearch#534]
i want to implement such a function，like this：
`POST /_sql?format=txt
{
	"query": "SELECT YEAR(release_date) AS year FROM library WHERE page_count > ? AND author = ? GROUP BY year HAVING COUNT(*) > ?",
	"params": [300, "Frank Herbert", 0]
}`
Now，I use this：

`req := esapi.SQLQueryRequest{
    Body: strings.NewReader(sql),
}
`

but how can i pass the parameters ——  [300, "Frank Herbert", 0] ， thanks for answer～

**Comment by Anaethelion** [comment]
Hi @Linkyx 

Unfortunately, the client doesn't handle that for you.
You would have to build the SQL request with a templating library or using the `fmt` [package](https://pkg.go.dev/fmt#Sprintf) in the runtime.

Be sure to escape the inputs if they are coming from your users to prevent any injection!
