### ISSUE TITLE
How to delete entire index with its documents

### ISSUE THREAD

**Issue by taracakeplabs** [elastic/go-elasticsearch#535]
How to do this : https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-index.html
with go-elasticsearch

**Comment by Anaethelion** [comment]
You can use the `es.Indices.Delete` for which you can find an example usage [here](https://github.com/elastic/go-elasticsearch/blob/f93b2df4798f17a7268fd914a7a29c828b30df3f/esapi/esapi_integration_test.go#L99) for `esapi` and [here](https://github.com/elastic/go-elasticsearch/blob/f93b2df4798f17a7268fd914a7a29c828b30df3f/elasticsearch_integration_test.go#L359) for `typedclient`.
