### ISSUE TITLE
Opendistro sql query via esapi

### ISSUE THREAD

**Issue by shaikmuzakkir** [elastic/go-elasticsearch#538]
The ES instance I intend to query has opendistro package for sql style querying.

Generally the query would look like 
`POST /_sql?format=txt { "query": "SELECT * from Index where field.count > 0"}`
In case of opendistro(may be it's configured) the query looks like
`POST _opendistro/_sql?format=json { "query": "SELECT * from Index where field.count > 0"}`

Is there a way in the API to make opendistro type url calls which has `_opendistro/_sql` in the url instead of `/_sql` ?

**Comment by Anaethelion** [comment]
Hi @shaikmuzakkir 

Unfortunately the URL is baked in the client at the code generation level and it only support Elasticsearch.
Two ways you could make this work is by implementing the `transport.Perform` interface and rewrite the URL on the fly, or you could directly use the `Transport.Perform()` inside the client to run a custom `http.Request` to your cluster.

**Comment by shaikmuzakkir** [comment]
Hi @Anaethelion thanks for the suggestion. By any chance do you have an example?

**Comment by shaikmuzakkir** [comment]
Thanks @Anaethelion !
