### ISSUE TITLE
v7.x branch is using v8 branch code

### ISSUE THREAD

**Issue by axw** [elastic/go-elasticsearch#55]
https://github.com/elastic/go-elasticsearch/blob/709f5bfb5561498c647ac7061a4e32a6091a2079/esutil/json_reader_integration_test.go#L9

Not sure if this is intentional or not. I was surprised to find the v8 module in my application's go.mod when only using the v7 module imports in my application code.

**Comment by karmi** [comment]
That's definitely a mistake — thanks for catching that. I guess it's been left over during merging commits across the version branches. I'll fix it.

**Comment by karmi** [comment]
I've fixed the incorrect require in all the branches, apart from `7.x`, `6.x` and `5.x` also had the same problem. Thanks for the report!
