### ISSUE TITLE
I have use case to write unit tests for elasticsearch.Client. Currently it doesn't have any interface so I cannot mock Search method.

### ISSUE THREAD

**Issue by VigneshSonaiya** [elastic/go-elasticsearch#56]

**Comment by karmi** [comment]
Hello, have a look at the example here: https://github.com/elastic/go-elasticsearch/blob/8ed748708d21347462d37f4a7cdd1ca267a28436/_examples/xkcdsearch/store_test.go#L60

The client expects you to provide a mock transport implementation for unit tests, ie. you're not mocking the `Search()` method directly — which would sort of defeat the purpose —, but you're mocking the underlying HTTP calls.

**Comment by VigneshSonaiya** [comment]
Hi Karmi, Thank you so much.

**Comment by karmi** [comment]
You're welcome! Is it OK to close the issue?

**Comment by VigneshSonaiya** [comment]
Yes Please..  👍
