### ISSUE TITLE
how to use query or body in search?

### ISSUE THREAD

**Issue by ly269nva** [elastic/go-elasticsearch#562]
i want to use esClient.Search.WithQuery(string) or esClient.Search.WithBody(io.reader) to search es document, but build query param of string or body param of io.reader is  inconvenient，not easy .
is there a way better than this in go ? like QueryBuilder in java

**Comment by Anaethelion** [comment]
Hi,

Not yet, be we are still working on this.
Any update will be posted on this issue https://github.com/elastic/go-elasticsearch/issues/526
