### ISSUE TITLE
Ability to add date range to indices in search api

### ISSUE THREAD

**Issue by Abhishek627** [elastic/go-elasticsearch#58]
Do we have the ability to search my ES indices based on date-range/DateMath ?

For example, if I have ES indices of format test-<data_format> and I want to search data across specific indices, for example now-10d to now. 

Is this case feasible using this package ?

**Comment by karmi** [comment]
Not exactly: the package gets whatever would be a correct value, including a pattern like `myindex-2019-01-*` (notice the wildcard), and pass it to Elasticsearch. But you cannot use date math in the index name — only in a query definition.

**Comment by karmi** [comment]
Hello, is it OK to close this issue?

**Comment by Abhishek627** [comment]
Sure. I'll close this issue. Thank you for the explanation.

**Comment by tannaga** [comment]
Hi @karmi  These feature seems to be like a good feature to have. Are there any plans to add support it?
https://www.elastic.co/guide/en/elasticsearch/reference/current/date-math-index-names.html

**Comment by karmi** [comment]
@tannaga , this should be supported by the client just fine — it just passes anything received as the index name — eg. `<logstash-{now/d}>` - to Elasticsearch.
