### ISSUE TITLE
esapi IndicesUpdateAliases bad response reader

### ISSUE THREAD

**Issue by BoldBrandonM** [elastic/go-elasticsearch#582]
I'm currently working on a feature which leverages this API endpoint via the go-elasticsearch client, and I noticed that when making a request structured like so, I am returned a response object which has the expected content, but an unreadable io.ReadCloser for the body.

`{
  "actions": [
    {
      "add": {
        "alias": "products",
        "index": "product_index_v6"
      }
    }
  ]
}`

Here is the calling code I have drafted for this purpose:
````
res, err := esapi.IndicesUpdateAliasesRequest{
                  Body: bytes.NewReader(reqBytes),
}.Do(ctx, c.inner)

if err != nil {
                  <log error pseudocode>
                  return false, err
}

// CRITICAL: must both consume and close the response body **even if not interested**, impacts reusable TCP connections
defer closeReader(ctx, res.Body)

// Check response status
if res.IsError() {
                  <log error pseudocode>
                  return false, err
}
````

When I inspect the response body in code by reading the reader, I receive no error, but the reader reads zero bytes. Strangely when printing the response object, I can see the body content within...
````
var resBytes []byte
num, err := res.Body.Read(resBytes)
if err != nil {
		<log error pseudocode>
		return false, err
}

fmt.Printf("\nres: %v, numbytes: %v\n", res, num)
````

I hate to call this a bug, but I've not been able to discern why else this would occur. Could there be something I am doing incorrectly which can cause this?

**Comment by BoldBrandonM** [comment]
Ah fantastic, I had a feeling it would be something I had done wrong! Do you mind advising on how I might opt to size this byte array given I don't know the size of the response prior to reading? I suppose I could considerably oversize it to be safe. Perhaps there is a response header available for content-length?

I'll go ahead with that approach for now. Thank you for the assistance!

**Comment by Anaethelion** [comment]
Depending on what you need you can do one of those:
* Exhaust the body content to a `io.Discard` to allow connection reuse
* Decode into a `map`
* Decode into a struct for easier access

Reading directly into a slice doesn't really seem like the way to go right away except for optimization.
In the end this all boils down to how you want to handle the `json` response more than the reader so I'd recommend digging that way.
