### ISSUE TITLE
Sample code  does not produces a result

### ISSUE THREAD

**Issue by liu-xiao-guo** [elastic/go-elasticsearch#585]
I just tried the sample code at https://github.com/elastic/go-elasticsearch, and the search part of the code does not produce any results. I think this is due to the field "Title" in the "test" index  does not match with the "title" field in the search. The relevant part of the code is:

```
      // Build the request body.      
      data, err := json.Marshal(struct{ Title string }{Title: title})
      if err != nil {
        log.Fatalf("Error marshaling document: %s", err)
      }
```
      
 The field is defined as "**T**itle". However, in the search code, it has "**t**itle":
 
 `  // Build the request body.
  var buf bytes.Buffer
  query := map[string]interface{}{

    "query": map[string]interface{}{
      "match": map[string]interface{}{
        "title": "test",
      },
    },
<img width="557" alt="image" src="https://user-images.githubusercontent.com/8455957/211744756-801bc516-e8b3-49d9-a921-bc5ee5a073db.png">
<img width="735" alt="image" src="https://user-images.githubusercontent.com/8455957/211744816-e7b56eb3-1c17-45c5-b78d-97d73f483182.png">

  }`

**Comment by Anaethelion** [comment]
Thank you for noticing, the Readme version was effectively out of sync with the examples!
