### ISSUE TITLE
how to delete multiple documents by documentId 

### ISSUE THREAD

**Issue by jmt99** [elastic/go-elasticsearch#589]
how can i delete multiple documents by documentId  
like mysql  delete * from XXX where id in (1,2,3,4)

**Comment by sethmlarson** [comment]
If you have a list of IDs you'd like to delete, you can use the [Elasticsearch Bulk API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) with multiple `delete` actions or you can use the [Elasticsearch Delete By Query API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html) if you'd like to delete documents which match a given query DSL.

Hope this helps!
