### ISSUE TITLE
How to add index alias with filter path?

### ISSUE THREAD

**Issue by FramnkRulez** [elastic/go-elasticsearch#591]
I'm attempting to add an alias where I want to filter on a specific field but I'm having a lot of difficulty getting this to work both using the ElasticSearch Golang library, or even via curl requests.  The problem is that I can't find any documentation on how to use `filter_path` in the documentation for `PUT {index}/_alias/{alias_name}` anywhere that mentions `filter_path`

There doesn't appear to be a Golang wrapper for using the `_aliases` endpoint to create an alias, so I'm a bit stumped other than making the REST API call outside the library

**Comment by Anaethelion** [comment]
Hi @FramnkRulez 

`filter_path` is specified within the [common options](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#common-options-response-filtering) of the API where you can find examples on how to filter the response.

`PUT {index}/_alias/{alias_name}` would map to a [client.Indices.PutAlias](https://github.com/elastic/go-elasticsearch/blob/main/esapi/api.indices.put_alias.go) where you can specify a `filter` query and `_aliases` would map to [client.Indices.UpdateAliases](https://github.com/elastic/go-elasticsearch/blob/main/esapi/api.indices.update_aliases.go) for which you can find an [example in the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/aliases.html#filter-alias) for what you want to achieve.
