### ISSUE TITLE
Typed Api : Getting Json version of the Payload from the request

### ISSUE THREAD

**Issue by avi94** [elastic/go-elasticsearch#596]
First of all, thank you for adding the **typedapi** package for strong typing. I wanted to know whether you have exposed any **API** or **Methods** or **sub-packages** to get the **actual JSON of the payload** that gets sent in the request to the Elasticsearch deployment?

**Comment by Anaethelion** [comment]
Hi @avi94 

Thank you for the praise!
There's currently no direct way. If this is for development you could recover the `HttpRequest` and read from the body. If this is for logging purposes you can inject a logger directly within transport for which you can find several examples in the [transport readme](https://github.com/elastic/elastic-transport-go/blob/main/README.md).

Could you explain your use case a bit more ?

**Comment by Anaethelion** [comment]
Closing this in the absence of a reply.
