### ISSUE TITLE
Missing Bulk for TypedAPI

### ISSUE THREAD

**Issue by CmpHDL** [elastic/go-elasticsearch#597]
Bulk allows to perform multiple index/update/delete operations in a single request.

`client.Bulk()` is missing from the TypedAPI

**Comment by Anaethelion** [comment]
Thank you for your interest!

It is indeed missing right now as well as all the nd-json APIs. We are still working on adding those in the future, keep an eye on the release notes!

**Comment by yanjinbin** [comment]
curren v8.13 still missing this fancy feature api right ?
