### ISSUE TITLE
Using typed API from 8.4.0 release, facing issue in generating search query having 'terms'

### ISSUE THREAD

**Issue by cmadarsh** [elastic/go-elasticsearch#598]
As part of below search query, I was trying to add 'terms' attribute using typed API.

**Query:**

      POST <index>/_search
      {
        "query": {
          "bool": {
            "must": [
              {
                "terms": {
                  "ID": [
                    "123",
                    "890"
                  ]
                }
              }
            ]
          }
        }
      }

**Here is the code snippet for adding 'terms'.**

qc := types.NewQueryContainerBuilder().Terms(types.NewTermsQueryBuilder().TermsQuery(map[types.Field]*types.TermsQueryFieldBuilder{types.Field(boolClause.TermsQ.FieldName): types.NewTermsQueryFieldBuilder().FieldValues(boolClause.TermsQ.Values)}))
var boolClauseList []types.QueryContainer
boolClauseList = append(boolClauseList, qc.Build()) 
types.NewBoolQueryBuilder().Must(boolClauseList)

**But this is generating 'terms' query as below which is creating an array inside array for 'ID' field.**

      "must": [
        {
          "terms": {
            "ID": [
              [
                "123",
                "890"
              ]
            ]
          }
        }

**Error:**

{
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "[terms] unknown token [END_ARRAY] after [ID]",
        "line": 39,
        "col": 13
      }
    ],
    "type": "x_content_parse_exception",
    "reason": "[39:13] [bool] failed to parse field [must]",
    "caused_by": {
      "type": "parsing_exception",
      "reason": "[terms] unknown token [END_ARRAY] after [ID]",
      "line": 39,
      "col": 13
    }
  },
  "status": 400
}

Could you please advice the code implementation for "terms" using typed API, or let me know if there is an issue with the library or the way I have implemented?

**Comment by Anaethelion** [comment]
Hi @cmadarsh 

The API has moved quite a bit since the 8.4, to achieve what you want I'd recommend using the types directly.
To generate the payload in your first example would take something like this in 8.4:

```go
request := search.Request{
  Query: &types.QueryContainer{
    Bool: &types.BoolQuery{
      Must: []types.QueryContainer{
        {
          Terms: &types.TermsQuery{
            TermsQuery: map[types.Field]types.TermsQueryField{
              "ID": []types.FieldValue{"123", "890"}
            },
          },
        },
      },
    },
  },
}
```
