### ISSUE TITLE
Where is your document, please? 

### ISSUE THREAD

**Issue by figoluis** [elastic/go-elasticsearch#6]
Where is your document, please?  The official website example is wrong

**Comment by 7AC** [comment]
Hi, there is documentation on godoc.org but the client is still a work in progress as stated in the readme (see also https://github.com/elastic/go-elasticsearch/issues/5). We'll remove the statement from the readme once it's usable.

**Comment by karmi** [comment]
Hello, the codebase has been completely replaced today, the documentation for the new client is available in the code repository and at https://godoc.org/github.com/elastic/go-elasticsearch.
