### ISSUE TITLE
Why is it better to use java to call tcp port 9300 than golang to call http port 9200

### ISSUE THREAD

**Issue by amsenhao** [elastic/go-elasticsearch#612]
When golang language is used to replace java language for data import, it is found that the performance of go-elasticsearch is lower than that of java language and the CPU usage is higher than that of java.

code:
	es, err := elasticsearch.NewClient(elasticsearch.Config{
		Addresses: []string{
			fmt.Sprintf("http://%s", config.GetString("elasticsearchupdateoutput_addr")),
		},
		// Retry on 429 TooManyRequests statuses
		RetryOnStatus: []int{502, 503, 504, 429},
		// A simple incremental backoff function
		RetryBackoff: func(i int) time.Duration { return time.Duration(i) * 1000 * time.Millisecond },
		Transport: &http.Transport{
			DisableKeepAlives:   false,
			Proxy:               http.ProxyFromEnvironment,
			MaxIdleConns:        b.concurrent * 2,
			MaxConnsPerHost:     b.concurrent,
			MaxIdleConnsPerHost: 2,
			IdleConnTimeout:     30 * time.Second,
		},
		// Retry up to 5 attempts
		MaxRetries: 5,
	})
      bulkIndexer, _ := esutil.NewBulkIndexer(esutil.BulkIndexerConfig{
		Client:        es,          // The Elasticsearch client
		NumWorkers:    b.numWorkers,// The number of worker goroutines (default: number of CPUs)
		FlushBytes:    b.bulk_size, // The flush threshold in bytes (default: 5M)
		FlushInterval: time.Duration(b.flush_interval) * time.Millisecond,
		OnFlushStart: func(ctx context.Context) context.Context {
			logger.LOG_WARN(">>> Flush started")
			return context.WithValue(ctx, "start", time.Now().UTC())
		},
		OnFlushEnd: func(ctx context.Context) {
			var duration time.Duration
			if v := ctx.Value("start"); v != nil {
				duration = time.Since(v.(time.Time))
			}
			logger.LOG_WARN(fmt.Sprintf(">>> Flush finished (duration: %s)", duration))
		},
		OnError: func(ctx context.Context, err error) {
			if err != nil {
				logger.LOG_ERROR("Flush error ", err)
			}
		},
	})
        err := b.bulkIndexer.Add(b.streamCtx.DoneCtx, esutil.BulkIndexerItem{
			Action: "index",
			Index:        wrap.Index,
			DocumentType: wrap.IndexType,
			Body: bytes.NewReader(wrap.Message),
			//Body:    strings.NewReader(`{"title":"foo"}`),
			OnSuccess: func(ctx context.Context, item esutil.BulkIndexerItem, item2 esutil.BulkIndexerResponseItem) {

			},
			OnFailure: func(ctx context.Context, item esutil.BulkIndexerItem, item2 esutil.BulkIndexerResponseItem, err error) {
				if err != nil {
					logger.LOG_ERROR("Unexpected error: %s", err)
				}
			},
		})

**Comment by Anaethelion** [comment]
Hi @amsenhao Could you specify which Java client are you referring to ?

**Comment by amsenhao** [comment]
> Hi @amsenhao Could you specify which Java client are you referring to ?

I use java sdk for to connect es and to add message，I see it connects to port 9300 of es，The jar packages used are as follows：
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>5.3.3</version>
        </dependency>
and user java sdk to add message，it batter then go，why？

**Comment by Anaethelion** [comment]
Thank you for the precision, if your Java SDK is connecting to the port 9300 I believe you are using the `TransportClient` which is [deprecated](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html).
Port 9300 uses a binary format for inter-nodes communication which explains why it is being faster.
