### ISSUE TITLE
Getting error when trying to access "type" and "reason" in error

### ISSUE THREAD

**Issue by kazakh-in-nz** [elastic/go-elasticsearch#614]
When trying to handle elasticsearch error as follows (which is similar to how it is done in the [ReadMe file here](https://github.dev/elastic/go-elasticsearch/blob/bc507c43e0f77e156927ceac0f8aad93d751cb5b/README.md#L319-L329)):
```
func (r *Repository) handleErr(ctx context.Context, res *esapi.Response) {
	var e map[string]interface{}
	if err := json.NewDecoder(res.Body).Decode(&e); err != nil {
		log.Fatalf("Error parsing the response body: %s", err)
                return
	}

	var (
		errStatus = res.Status()
		errType   = e["error"].(map[string]interface{})["type"]
		errReason = e["error"].(map[string]interface{})["reason"]
	)

	log.Fatalf("[%s] %s: %s",
		errStatus,
		errType,
		errReason,
	)
}
```

I am getting this error: `interface conversion: interface {} is nil, not map[string]interface {}`, which fails at:
```
errType   = e["error"].(map[string]interface{})["type"]
```

**Comment by Anaethelion** [comment]
Hi there,

This is expected in Go, you would have to check for the presence of the `error` key within the map before trying to access it.
Note that the `error` field could also be a `string` if you made a malformed call which was answered by the HTTP layer of the server.
