### ISSUE TITLE
create and put document

### ISSUE THREAD

**Issue by menhuan** [elastic/go-elasticsearch#62]
May I  set id ?  When I create  the document  ,using the sdk 
![image](https://user-images.githubusercontent.com/20064040/60324522-9cc91700-99b7-11e9-9cf5-d4ede7920904.png)

**Comment by karmi** [comment]
Hello, yes, see either example for using the struct directly:

https://github.com/elastic/go-elasticsearch/blob/2870f808ff8548e1ac9d29ff91510eebba15dd3f/_examples/main.go#L76

or check just pass the ID as you do, see https://godoc.org/github.com/elastic/go-elasticsearch/esapi#Create.

**Comment by menhuan** [comment]
yes.  doesn't  elasticsearch  suppose automation id ? I want to use automatic id in the sdk . 
wiki is https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-index_.html#_automatic_id_generation 。 post is ok ，but  how to use  sdk?

**Comment by menhuan** [comment]
> Hello, yes, see either example for using the struct directly:
> 
> https://github.com/elastic/go-elasticsearch/blob/2870f808ff8548e1ac9d29ff91510eebba15dd3f/_examples/main.go#L76
> 
> or check just pass the ID as you do, see https://godoc.org/github.com/elastic/go-elasticsearch/esapi#Create.

yes. doesn't elasticsearch suppose automation id ? I want to use automatic id in the sdk .
wiki is https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-index_.html#_automatic_id_generation 。 post is ok ，but how to use sdk?

**Comment by karmi** [comment]
Right, but you have to use the Index API for that: https://godoc.org/github.com/elastic/go-elasticsearch/esapi#Index

**Comment by menhuan** [comment]
> Right, but you have to use the Index API for that: https://godoc.org/github.com/elastic/go-elasticsearch/esapi#Index

thanks, you  sloves my question.

**Comment by menhuan** [comment]
> Right, but you have to use the Index API for that: https://godoc.org/github.com/elastic/go-elasticsearch/esapi#Index

thanks, you solve my question.
