### ISSUE TITLE
Chaining Filters with go-elasticsearch

### ISSUE THREAD

**Issue by notque** [elastic/go-elasticsearch#626]
Currently using olivere, and need to move to go-elasticsearch for es8 on.

The majority of what I use it for is chaining different filters. 

```
query := elastic.NewBoolQuery()

	if filter.ObserverType != "" {
		//logg.Debug("Filtering on ObserverType %s", filter.ObserverType)
		query = FilterQuery(filter.ObserverType, esFieldMapping["observer_type"], query)
	}
```

with FilterQuery being

```
func FilterQuery(filter, filtername string, query *elastic.BoolQuery) *elastic.BoolQuery {
	switch {
	case strings.HasPrefix(filter, "!"):
		filter = filter[1:]
		query = query.MustNot(elastic.NewTermQuery(filtername, filter))
	default:
		query = query.Filter(elastic.NewTermQuery(filtername, filter))
	}
	return query
}
```

as well as time

`query.Filter(elastic.NewRangeQuery(timeField).Gt(value))`

as well as sorting, and pagination. 

How would I do this currently in go-elasticsearch? My understanding is it would make the most sense waiting for the DSL to enable this kind of flexibility, but looking for approaches.

**Comment by Anaethelion** [comment]
In the absence of the DSL and if I understand your code correctly, this should produce the same effect using the generated types:

```go
func FilterQuery(filter, filtername string, query *types.BoolQuery) *types.BoolQuery {
	switch {
	case strings.HasPrefix(filter, "!"):
		filter = filter[1:]
		query.MustNot = append(query.MustNot, types.Query{Term: map[string]types.TermQuery{filtername: {Value: filter}}})
	default:
		query.Filter = append(query.Filter, types.Query{Term: map[string]types.TermQuery{filtername: {Value: filter}}})
	}

	return query
}
```

Which can then be used like this, given the typed client has be instantiated in `es`:

```go
b := FilterQuery("filter", "filtername", types.NewBoolQuery())
res, err := es.Search().Request(&search.Request{Query: &types.Query{
	Bool: b,
}}).Do(context.Background())
...
```

The logic would be roughly the same for `RangeQuery` & `Sort`.
Let me know if this helps!
