### ISSUE TITLE
mget 503 error 

### ISSUE THREAD

**Issue by menhuan** [elastic/go-elasticsearch#65]
mget error 503 ,but no any words.
![image](https://user-images.githubusercontent.com/20064040/60710178-a9fc7d80-9f44-11e9-8648-35762d533719.png)

I test data by postman . it is ok。
![image](https://user-images.githubusercontent.com/20064040/60710211-be407a80-9f44-11e9-9b3b-af49afced82c.png)

**Comment by karmi** [comment]
Hello, I'll need more information to be able to help. First thing, can you paste the code as text, using the "```" Markdown format, so I have a chance to try it out. Second thing, can you post the error response returned from Elasticsearch? (Use `res.String()` to obtain it easily.)

**Comment by menhuan** [comment]
the 503 error  is what  link els is error.   

version:v8
code  : 
`con := fmt.Sprintf("http://%s:%s", ela.Addr, ela.Port)
	cfg := elasticsearch.Config{
		Addresses: []string{
			con,
		},
	}
	es, err := elasticsearch.NewClient(cfg)
	client = es
	res, err := client.Info()
	if err != nil {
		log.Println(res)
	}`

**Comment by menhuan** [comment]
> Hello, I'll need more information to be able to help. First thing, can you paste the code as text, using the "```" Markdown format, so I have a chance to try it out. Second thing, can you post the error response returned from Elasticsearch? (Use `res.String()` to obtain it easily.)








the 503 error is what link els is error.

version:v8
`

con := fmt.Sprintf("http://%s:%s", ela.Addr, ela.Port) 
cfg := elasticsearch.Config{ Addresses: []string{ con, }, }
 es, err := elasticsearch.NewClient(cfg) client = es res, err := client.Info()
 if err != nil { log.Println(res) }`

**Comment by karmi** [comment]
> the 503 error is what link els is error

I'm sorry, but what does that mean? What is the full response returned from Elasticsearch, not just the status code?

**Comment by menhuan** [comment]
> > the 503 error is what link els is error
> 
> I'm sorry, but what does that mean? What is the full response returned from Elasticsearch, not just the status code?

thanks . I solve  the question. [way](https://github.com/elastic/go-elasticsearch/blob/master/elasticsearch_example_test.go)

I change version yesterday。

**Comment by karmi** [comment]
So by adapting the example, everything works as expected?

**Comment by menhuan** [comment]
> So by adapting the example, everything works as expected?

yes. sorry. 
I forgot changing sdk's version.

**Comment by karmi** [comment]
Glad to hear that! Closing the issue as solved then...
