### ISSUE TITLE
how to do chain filter with boolQuery in go-elasticsearch

### ISSUE THREAD

**Issue by azhu0914** [elastic/go-elasticsearch#656]
I wonder how to use boolQuery in go-elasticsearch like github.com/olivere/elasticsearch
   ```
    boolQuery := types.BoolQuery{}
	boolQuery.Filter = append(boolQuery.Filter, types.Query{Term: map[string]types.TermQuery{"age": {Value: 111}}})

	var re map[string]interface{}
	
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(boolQuery); err != nil {
		log.Fatalf("Error encoding query: %s", err)
	}
	res, err := esclient.Search(
		esclient.Search.WithContext(context.Background()),
		esclient.Search.WithIndex("test"),
		esclient.Search.WithBody(&buf),
		esclient.Search.WithTrackTotalHits(true),
		esclient.Search.WithPretty(),
	)
```

**Comment by xcxinng** [comment]
+1

Looking forward to the response.

**Comment by GithubRyze** [comment]
+1  

Very hard too use, 

func conventToQueryString(q *NotifyRecordQuery) string {
	var query strings.Builder
	query.WriteString(fmt.Sprintf(`{"query": {"bool": {"filter": [`))
	strs := []string{}
	if q.StartTime != "" && q.EndTime != "" {

		strs = append(strs, fmt.Sprintf(`{
			"range": {
				"baseInfo.createdTime": {
					"format": "strict_date_optional_time",
					"from": "%s",
					"include_lower": true,
					"include_upper": true,
					"to": "%s"
				}
			}
		}`, q.StartTime, q.EndTime))
	}
	if q.NotificationSendStatus != "" {
		strs = append(strs,
			fmt.Sprintf(`{
				"match_phrase": {
					"notificationSendStatus.keyword": {
						"query": "%s"
					}
				}
			}`, q.NotificationSendStatus))
	}
	if q.Keyword != "" {
		strs = append(strs,
			fmt.Sprintf(`{
				"multi_match": {
					"fields": ["templateName","notificationSendContent"],
					"lenient": true,
					"query": "%s",
					"type": "phrase"
				}
			}`, q.Keyword))
	}
	if len(strs) == 1 {
		query.WriteString(strs[0])
	} else {
		for i, v := range strs {
			if i == 0 {
				query.WriteString(v)
			} else {
				query.WriteString("," + v)
			}
		}
	}
	query.WriteString(`]}}}`)
	return query.String()
}

**Comment by Anaethelion** [comment]
Should you want to mix the low-level client with the types from the typed client, based on the code in the first post, here's how you could do that:

```go
	boolquery := types.BoolQuery{
		Filter: []types.Query{
			{Term: map[string]types.TermQuery{"age": {Value: 111}}},
		},
	}

	query := search.Request{
		Query: &types.Query{
			Bool: &boolquery,
		},
	}

	var re map[string]interface{}

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(query); err != nil {
		log.Fatalf("Error encoding query: %s", err)
	}
	res, err := esclient.Search(
		esclient.Search.WithContext(context.Background()),
		esclient.Search.WithIndex("test"),
		esclient.Search.WithBody(&buf),
		esclient.Search.WithTrackTotalHits(true),
		esclient.Search.WithPretty(),
	)
	if err != nil {
		log.Fatal(err)
	}
	defer res.Body.Close()
	if err := json.NewDecoder(res.Body).Decode(&re); err != nil {
		log.Fatal(err)
	}
	fmt.Println(re)
```

Which would translate in the TypedClient as:
```go
	boolquery := types.BoolQuery{
		Filter: []types.Query{
			{Term: map[string]types.TermQuery{"age": {Value: 111}}},
		},
	}

	res, err := esclient.Search().
		Index("test").
		TrackTotalHits("true").
		Request(&search.Request{
			Query: &types.Query{
				Bool: &boolquery,
			},
		}).
		Do(context.Background())

	if err != nil {
		log.Fatal(err)
	}
```

**Comment by xcxinng** [comment]
Finally, I've decided to use olivere/elastic, which is much easier to use and understand(for query), and mostly because the majority of my coworkers are more familiar with olivere/elastic than this.

**Comment by azhu0914** [comment]
> esclient.Search.WithBody(&buf),

can not find this useage in the package,can you tell me what version do you use?

**Comment by azhu0914** [comment]
> Should you want to mix the low-level client with the types from the typed client, based on the code in the first post, here's how you could do that:
> 
> ```go
> 	boolquery := types.BoolQuery{
> 		Filter: []types.Query{
> 			{Term: map[string]types.TermQuery{"age": {Value: 111}}},
> 		},
> 	}
> 
> 	query := search.Request{
> 		Query: &types.Query{
> 			Bool: &boolquery,
> 		},
> 	}
> 
> 	var re map[string]interface{}
> 
> 	var buf bytes.Buffer
> 	if err := json.NewEncoder(&buf).Encode(query); err != nil {
> 		log.Fatalf("Error encoding query: %s", err)
> 	}
> 	res, err := esclient.Search(
> 		esclient.Search.WithContext(context.Background()),
> 		esclient.Search.WithIndex("test"),
> 		esclient.Search.WithBody(&buf),
> 		esclient.Search.WithTrackTotalHits(true),
> 		esclient.Search.WithPretty(),
> 	)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	defer res.Body.Close()
> 	if err := json.NewDecoder(res.Body).Decode(&re); err != nil {
> 		log.Fatal(err)
> 	}
> 	fmt.Println(re)
> ```
> 
> Which would translate in the TypedClient as:
> 
> ```go
> 	boolquery := types.BoolQuery{
> 		Filter: []types.Query{
> 			{Term: map[string]types.TermQuery{"age": {Value: 111}}},
> 		},
> 	}
> 
> 	res, err := esclient.Search().
> 		Index("test").
> 		TrackTotalHits("true").
> 		Request(&search.Request{
> 			Query: &types.Query{
> 				Bool: &boolquery,
> 			},
> 		}).
> 		Do(context.Background())
> 
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> ```

`querySearch:=types.Query{}
	boolQuery:=types.BoolQuery{}
	if request.WholesaleId > 0{
		boolQuery.Filter = append(boolQuery.Filter,types.Query{Term: map[string]types.TermQuery{
			"wholesaleId":{Value: 1111},
		}})
	}
	querySearch.Bool = &boolQuery
	searchresqust := esapi.SearchRequest{
		Index: []string{index},
		Body: esutil.NewJSONReader(querySearch),
	}
	`res,err:=searchresqust.Do(ctx,elasticv8)`
`
only can use like this,but seems something go wrong and can not get the search result

**Comment by azhu0914** [comment]
> Should you want to mix the low-level client with the types from the typed client, based on the code in the first post, here's how you could do that:
> 
> ```go
> 	boolquery := types.BoolQuery{
> 		Filter: []types.Query{
> 			{Term: map[string]types.TermQuery{"age": {Value: 111}}},
> 		},
> 	}
> 
> 	query := search.Request{
> 		Query: &types.Query{
> 			Bool: &boolquery,
> 		},
> 	}
> 
> 	var re map[string]interface{}
> 
> 	var buf bytes.Buffer
> 	if err := json.NewEncoder(&buf).Encode(query); err != nil {
> 		log.Fatalf("Error encoding query: %s", err)
> 	}
> 	res, err := esclient.Search(
> 		esclient.Search.WithContext(context.Background()),
> 		esclient.Search.WithIndex("test"),
> 		esclient.Search.WithBody(&buf),
> 		esclient.Search.WithTrackTotalHits(true),
> 		esclient.Search.WithPretty(),
> 	)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	defer res.Body.Close()
> 	if err := json.NewDecoder(res.Body).Decode(&re); err != nil {
> 		log.Fatal(err)
> 	}
> 	fmt.Println(re)
> ```
> 
> Which would translate in the TypedClient as:
> 
> ```go
> 	boolquery := types.BoolQuery{
> 		Filter: []types.Query{
> 			{Term: map[string]types.TermQuery{"age": {Value: 111}}},
> 		},
> 	}
> 
> 	res, err := esclient.Search().
> 		Index("test").
> 		TrackTotalHits("true").
> 		Request(&search.Request{
> 			Query: &types.Query{
> 				Bool: &boolquery,
> 			},
> 		}).
> 		Do(context.Background())
> 
> 	if err != nil {
> 		log.Fatal(err)
> 	}

querySearch:=types.Query{}
	boolQuery:=types.BoolQuery{}
	if request.WholesaleId > 0{
		boolQuery.Filter = append(boolQuery.Filter,types.Query{Term: map[string]types.TermQuery{
			"wholesaleId":{Value: 1111},
		}})
	}
	querySearch.Bool = &boolQuery
	searchresqust := esapi.SearchRequest{
		Index: []string{index},
		Body: esutil.NewJSONReader(querySearch),
	}
	`res,err:=searchresqust.Do(ctx,elasticv8)`

> ```
can use like this ,but seems somothing wrong and can not get result 
``

**Comment by technige** [comment]
> can use like this ,but seems somothing wrong and can not get result

@azhu0914 You'll have to be a lot more specific for us to be able to help you here. Please describe your setup and the exact code you are running, as well as the behaviour, response, or error that you see as a result.

**Comment by Anaethelion** [comment]
Without more informations we are unable to help, I'm closing this for now.
