### ISSUE TITLE
BUG   unknown field 'Username' ,'Password'   in struct literal of type elasticsearch.Config

### ISSUE THREAD

**Issue by tx991020** [elastic/go-elasticsearch#68]
111/main.go:34:3: unknown field 'Username' in struct literal of type elasticsearch.Config
111/main.go:35:3: unknown field 'Password' in struct literal of type elasticsearch.Config
111/main.go:36:3: unknown field 'CloudID' in struct literal of type elasticsearch.Config
111/main.go:37:3: unknown field 'APIKey' in struct literal of type elasticsearch.Config

```
func main() {
  config1 := elasticsearch.Config{
  Addresses: []string{
    "http://elasticsearch.aliyuncs.com:9200",
  },
  Username:  "elastic",
  Password:  "elastic1",
  CloudID:   "",
  APIKey:    "",
  Transport: &http.Transport{
    MaxIdleConnsPerHost:   10,
    ResponseHeaderTimeout: time.Second,
    DialContext:           (&net.Dialer{Timeout: time.Second}).DialContext,
    TLSClientConfig: &tls.Config{
      MinVersion: tls.VersionTLS11,
      // ...
    },
  },
    //Logger:    nil,
  }
  
  es, err := elasticsearch.NewClient(config1)
  fmt.Println(es,err)
}
```

**Comment by karmi** [comment]
Hello, first of all, why are you using a configuration with so many empty fields, and why do you customize the default transport at all?

Second, what version of Go and the package is this? Ie. can you paste the relevant `import` lines, and the output of elasticsearch.Version()?

**Comment by tx991020** [comment]
I don't understand how go.mod works, it is go.mod not imported properly。now it is ok

**Comment by karmi** [comment]
Cool, so it's OK to close the issue?

**Comment by chundurysrikar** [comment]
Hi karmi, there is something fishy going on here. This is what I ran :

```
package main
import (
	"github.com/elastic/go-elasticsearch"
	"reflect"
	"fmt"
)

func main() {
	cfg := elasticsearch.Config{}
    e := reflect.ValueOf(&cfg).Elem()
    for i := 0; i < e.NumField(); i++ {
        varName := e.Type().Field(i).Name
        varType := e.Type().Field(i).Type
        varValue := e.Field(i).Interface()
        fmt.Printf("%v %v %v\n", varName,varType,varValue)
    }
}
```
and this is what I get in the output:
```
Addresses []string []
Transport http.RoundTripper <nil>
```
version in go.mod file :
```
github.com/elastic/go-elasticsearch v0.0.0
github.com/elastic/go-elasticsearch/v8 v8.0.0-20200408073057-6f36a473b19f
```
Can I get any help ?

**Comment by karmi** [comment]
Hey! Can you remove this line from `go.mod`?

```
github.com/elastic/go-elasticsearch v0.0.0
```

Go perhaps resolves this to the initial version of the package, which didn't have the configuration fields. Sometimes IDEs and editor plugins mess up the import declarations.

Use the import with the version suffix — the one you have points to a recent commit on the master branch:

```
github.com/elastic/go-elasticsearch/v8 v8.0.0-20200408073057-6f36a473b19f
```

Note: In general, use a major version of the package matching the major version of Elasticsearch. For example, if you're using Elastiscsearch 7.x, use either the `7.x` branch, or a specific tag.

**Comment by chundurysrikar** [comment]
`github.com/elastic/go-elasticsearch v0.0.0
`
The above line is auto added anyway right ?
The issue still persists..

**Comment by karmi** [comment]
As I'm saying, your editor might be adding this, but that line is incorrect — that points to a really old version. You have to remove the line.

**Comment by chundurysrikar** [comment]
Got it!, Awesome. Works now after I changed that.
my go.mod file now has:
`github.com/elastic/go-elasticsearch/v7 v7.5.1-0.20200429062015-142e0c281dde`
Thanks Karmi!

**Comment by karmi** [comment]
You're welcome — glad that it's working!

---

Note: Go resolver is a bit funky, note that it seems to point to version `v7.5.1`, but if you decipher the date and the commit, it points to a recent commit. When you print `elasticsearch.Version`, that should tell the truth about the version you're using.
