### ISSUE TITLE
Memory leak on `bulk insert`

### ISSUE THREAD

**Issue by zhaoyi0113** [elastic/go-elasticsearch#681]
I have a service to bulk insert items on Elasticsearch. But I found there could be a memory leak on this API. Below is my code:

```go
var client *elasticsearch.Client = nil

func CreateESClient() *elasticsearch.Client {
	esHost := getEsHost()
	cfg := elasticsearch.Config{
		Addresses: []string{
			esHost,
		},
	}
	es, err := elasticsearch.NewClient(cfg)
	FailOnError(err, "Failed to create elasticsearch connection.")
	return es
}

func BulkInsert(indexName string, docs string) {
       if client == nil {
		client = CreateESClient()
	}
	res, err := client.Bulk(strings.NewReader(docs), client.Bulk.WithIndex(indexName))
	failOnEsError(res)
	FailOnError(err, "Cant insert into ES")
}
```

If I remove the line `client.Bulk` and let my application run for a long time, it doesn't have any memory issue. However, the memory usage keep increasing if I keep the `client.Bulk` API call. I wonder whether there is a memory leak issue on this method. Or am I doing something wrong in my code?

**Comment by Anaethelion** [comment]
Hi @zhaoyi0113 

Picking this up, I believe the memory leak you are experiencing is due to you not closing the reader that is found within the `http.Response` in:

```go
res, err := client.Bulk(strings.NewReader(docs), client.Bulk.WithIndex(indexName))
```

Should be followed by something like this:
```go
defer res.Body.Close()
```
