### ISSUE TITLE
No method to create index patterns 

### ISSUE THREAD

**Issue by lakshayarora476** [elastic/go-elasticsearch#695]
There is no method to create index patterns in Elasticsearch?

**Comment by Anaethelion** [comment]
Hi!

Maybe are you referring to [Index Templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html) ?

In any case, questions are better asked in the [discuss forum](https://discuss.elastic.co/c/elastic-stack/81)!

**Comment by lakshayarora476** [comment]
No, I am referring to index patterns which we create on kibana dashboard.
