### ISSUE TITLE
when will official release for elasticsearch 5.x be available?

### ISSUE THREAD

**Issue by aslng** [elastic/go-elasticsearch#7]
Is there any estimated availability date? i.e. officially released for 5.x

**Comment by 7AC** [comment]
I'm not sure about dates but you can track the progress with https://github.com/elastic/go-elasticsearch/issues/5.

**Comment by karmi** [comment]
Hello, the project has been completely replaced today with a new codebase — the client supports Elasticsearch `7.x`, we will be adding support for `5.x` and `6.x` shortly.
