### ISSUE TITLE
[400 Bad Request] search_phase_execution_exception: all shards failed error when I specify 'WithSize' >=10000

### ISSUE THREAD

**Issue by HouJiuZhu** [elastic/go-elasticsearch#71]
[400 Bad Request] search_phase_execution_exception: all shards failed error when I specify 'WithSize' >=10000

**Comment by karmi** [comment]
That seems to be expected, see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html — 10,000 is the limit. As the documentation suggests, use either the Scroll API for large-scale fetching of data, or the `search_after` parameter for deep pagination (the `_examples/xkcd` has an example for doing that with the Go client.)

**Comment by karmi** [comment]
Hi, any news?

**Comment by HouJiuZhu** [comment]
This is my solution：

**Comment by HouJiuZhu** [comment]
This is my solution：
PUT ***/_settings
{ 
  "max_result_window" : 500000 
}

**Comment by karmi** [comment]
All right — be aware of the impact on the cluster, as explained in the documentation. It's really not advisable to use such a large number of total hits.
