### ISSUE TITLE
Support for custom keywords in typed-api

### ISSUE THREAD

**Issue by rajivprab** [elastic/go-elasticsearch#711]
Hi. We're using a [3rd party plugin (LTR) together with Elastic to run our searches](https://elasticsearch-learning-to-rank.readthedocs.io/en/latest/searching-with-your-model.html). In order to use this plugin, our queries contain some custom keywords. Simplified example (see the `sltr` section):
```
POST tmdb/_search
{
    "query": {
        "match": {
            "_all": "rambo"
        }
    },
    "rescore": {
        "window_size": 1000,
        "query": {
            "rescore_query": {
                "sltr": {
                    "params": {
                        "keywords": "rambo"
                    },
                    "model": "my_model"
                }
            }
        }
    }
}
```

Is there any way to construct semi-custom queries like the above using the typed-api structs? From what I see, there's no way to incorporate raw-json or custom keywords into `types.RescoreQuery`, `types.Query` etc

The only solution I could think of is:

1. Construct most of the query, without the sltr portion, using the typed-api structs
2. Marshal the Request into a json-string
3. Unmarshal the json-string into a generic map[string]interface{}
4. Insert the `sltr` portion of the query into the above generic map
5. Marshal the updated map back into a json
6. Use the `raw json` [functionality to run the updated query](https://www.elastic.co/guide/en/elasticsearch/client/go-api/8.9/runningqueries.html)

Is there a better way of building the above query using the typed-api?

**Comment by Anaethelion** [comment]
Hi @rajivprab 

That's an interesting topic!

First of all the way you highlighted works.

Another would be to use a `go:generate` command to vendor a custom version of the `search.Request` type on which you would override `Rescore` with a `sltr` type.

Lastly I'd do it by embedding the `search.Request` in another type along with an `sltr` field and write a custom serializer field by field. You never desync with the lib and you control what you use.

In the end all three would end up using the raw json to pass the query to the client.

Hope this helps, let me know if you have any further questions!
