### ISSUE TITLE
Govendor installation problem

### ISSUE THREAD

**Issue by ObrookO** [elastic/go-elasticsearch#72]
When I package  dependencies with govendor, an error occured:  "use of internal package github.com/elastic/go-elasticsearch/internal/version not allowed".How can I fix it?
Package version:elasticsearch/v6
Operating system: Mac os 10.14.1

**Comment by karmi** [comment]
Hi, the package expects to be installed via `go.mod`, or manually. I've experimented with `govendor` at some time, and it can be made to work, but requires some [terrible acrobatics](https://gist.github.com/karmi/52fe8086128dea4a931e9d911530d532) — so I advise to use Go modules.

**Comment by ObrookO** [comment]
> Hi, the package expects to be installed via `go.mod`, or manually. I've experimented with `govendor` at some time, and it can be made to work, but requires some [terrible acrobatics](https://gist.github.com/karmi/52fe8086128dea4a931e9d911530d532) — so I advise to use Go modules.

thank you! I use Go modules instead of govendor and it works.

**Comment by karmi** [comment]
Cool!
