### ISSUE TITLE
BulkIndexer in v8.x can silently drop items when flush is not ok

### ISSUE THREAD

**Issue by styleex** [elastic/go-elasticsearch#732]
Conducting a review of the BulkIndexer code before using it in my project, I saw a problem in the line https://github.com/elastic/go-elasticsearch/blob/v8.10.0/esutil/bulk_indexer.go#L418:

if flush fails with an error, the current item will simply be skipped, which seems incorrect to me. Fortunately, in case of an error in flush, onError will be called and the program can be stopped.

In general, it is difficult for me to say what kind of behavior will be 100% correct here. In theory, either wait for a successful flush, or stop the cycle, but definitely not drop elements.

**Comment by Anaethelion** [comment]
The BulkIndexer is supposed to be long lived which is why we continue in case of an error during flush.
I would encourage you to subscribe to the callback and decide if you want to re-queue, abort completely or any behavior that fit your use case.
