### ISSUE TITLE
Indices.PutSettings can't specify index name in v8.11.0

### ISSUE THREAD

**Issue by gannett-ggreer** [elastic/go-elasticsearch#756]
Possibly related to commit: https://github.com/elastic/go-elasticsearch/commit/537d09014a37fd1288919bd43eb7f1ab1bd374ae

Previously the usage was: `.client.Indices.PutSettings().Index(index).Request(settings).Do(ctx)`

Now `.Index()` has changed to accept `index *types.IndexSettings` instead of `index string` and no method to set the index name exists.

There was a similar change to `PutMappings` in the same commit but there the index name can be set via the `PutMappings(index)` call after the `.Index()` method changed, which makes sense, but a similar change was not done for `PutSettings()`.

**Comment by Anaethelion** [comment]
Thank you, this is indeed a bug in the generation process that validates collisions and priorities, I'll have a look.

**Comment by Anaethelion** [comment]
Fixed in [v8.11.1](https://github.com/elastic/go-elasticsearch/releases/tag/v8.11.1)
