### ISSUE TITLE
Trying Sort by Script. Kibana worked but GoLang failed on JSON parsing, "_script"

### ISSUE THREAD

**Issue by 9tontruck** [elastic/go-elasticsearch#757]
Hi,

My ElasticSearch version is `6.4`
and I am using `olivere's client` in GoLang

I am trying to sort the result by a custom script which is introduced here:
https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-request-sort.html#_script_based_sorting

Here's my GoLang search code:
```
func (s *ElasticSearchClient) Search(ctx context.Context,
	index string, searchType string,
	search string) (*elastic.SearchResult, error) {
	return s.es.Search(index).Type(searchType).Source(search).Do(ctx)
}
```

And here's my query:
```
 {
  "query": {
    "bool" : {
      "must" : [
        {
          "term" : { "latestEvent" : "AAA" }
        },
        {
          "range" : {
          "latestEventDate" : { "gte" : "2023-11-10T17:40:50.07Z" }
          }
        }
      ]
    }
  },
  "sort": [
    {
      "_script": {
        "type": "number",
        "order": "desc",
        "script": {
          "source": """
            def value = {some kind of calculation}
            return value;
          """,
          "params": {
            "mean": 1,
            "sd": 2,
            "currentTimestamp": 1699943316141
          }
        }
      }
      
    }
  ],
  "_source": [
    "latestEvent",
    "latestEventDate"
  ]
}
```

I wrote my query like above and confirmed it worked well in Kibana.
But I started having issues within the code.

I am facing an error because `_parse` is not a JSON friendly key.
```
"elastic: Error 400 (Bad Request): [28:21] [_script] failed to parse field [script] [type=x_content_parse_exception]"
```

I spent days to figure out how I can fix this but there was no luck. Can someone please help me to either
1. forcing JSON parsing allowing underscored keys like `_script` and `_source`
2. find another way to sort the result by script value

Thanks in advance!

**Comment by Anaethelion** [comment]
Hello @9tontruck 

Unfortunately we do not provide support for Oliver's client.
If you decide to switch to the official client I can help you rewrite your query with the `TypedAPI`.

**Comment by 9tontruck** [comment]
@Anaethelion 
Thanks for your comment. I updated my ES client so my app is using `"github.com/elastic/go-elasticsearch/v7/esapi"`
And my search function is something like this now:
```
func (e ElasticSearchClient) Search(ctx context.Context,
	index string,
	searchType string,
	search map[string]interface{},
) (*esapi.Response, error) {
	jsonString, _ := json.Marshal(search)
	return e.es.Search(
		e.es.Search.WithContext(context.Background()),
		e.es.Search.WithIndex(index),
		e.es.Search.WithBody(strings.NewReader(string(jsonString))),
		e.es.Search.WithTrackTotalHits(true),
		e.es.Search.WithContext(ctx),
	)
}
```

But I am still having JSON parsing errors when I add `_script` inside of the `Sort` field.
ref- https://www.elastic.co/guide/en/elasticsearch/reference/6.4/search-request-sort.html#_script_based_sorting

The version of my ElasticSearch is 6.4

Would you guide me to use scrip-sort using the `go-elasticsearch` client?

**Comment by 9tontruck** [comment]
Created a new thread as it's closed
https://github.com/elastic/go-elasticsearch/issues/764
