### ISSUE TITLE
how to use upsert ?  can you give a example?

### ISSUE THREAD

**Issue by tx991020** [elastic/go-elasticsearch#76]
like this in java

IndexRequest indexRequest = new IndexRequest("index", "type", "1")
        .source(jsonBuilder()
            .startObject()
                .field("name", "Joe Smith")
                .field("gender", "male")
            .endObject());
UpdateRequest updateRequest = new UpdateRequest("index", "type", "1")
        .doc(jsonBuilder()
            .startObject()
                .field("gender", "male")
            .endObject())
        .upsert(indexRequest);              
client.update(updateRequest).get();

**Comment by karmi** [comment]
Hi, the client doesn't have any helper methods for programatically building the body — it accepts an `io.Reader`. Hence, following the [documentation for upsert](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#upserts), you have to provide the body somehow like this:

```golang
//+build ignore

package main

import (
	"log"
	"strings"

	"github.com/elastic/go-elasticsearch/v8"
)

func main() {
	log.SetFlags(0)

	es, err := elasticsearch.NewDefaultClient()
	if err != nil {
		log.Fatalf("Error creating the client: %s", err)
	}

	res, err := es.Update(
		"test",
		"1",
		strings.NewReader(`{
      "script" : {
        "source": "ctx._source.counter += params.count",
        "lang": "painless",
        "params" : {
            "count" : 4
        }
      },
      "upsert" : {
        "counter" : 1
      }
    }`),
	)

	log.Println(res.Status(), err)

	log.Println(es.Get("test", "1"))
}
```
