### ISSUE TITLE
mdsc certificate is not truested

### ISSUE THREAD

**Issue by mingmingshiliyu** [elastic/go-elasticsearch#765]
<img width="875" alt="image" src="https://github.com/elastic/go-elasticsearch/assets/143821597/67edc8b8-194a-483b-849a-d5bb51670ec3">
elasticsearch address is a https address,and i use username,password to login,but return above.how to fix this.i want to ignore certificate related warnings.

**Comment by mingmingshiliyu** [comment]
but i can not found any evidence about certificates validate ignorance

**Comment by Anaethelion** [comment]
Hi @mingmingshiliyu 

Could you give more information about what is MDSC ?
Root certificates should be retrieved from the system by Go, keeping them up to date should be you first choice.

In case you cannot upgrade, here are several options:

- You can add the server's CA to [the client config](https://www.elastic.co/guide/en/elasticsearch/client/go-api/current/connecting.html#verifying-with-ca).
- You can pin the fingerprint of [the server's certificate](https://www.elastic.co/guide/en/elasticsearch/client/go-api/current/connecting.html#verifying-with-fingerprint).

Ultimately you can set `InsecureSkipVerify` to `true` in the `tls.Config` for the transport, that should be you last resort.

**Comment by mingmingshiliyu** [comment]
> Hi @mingmingshiliyu
> 
> Could you give more information about what is MDSC ? Root certificates should be retrieved from the system by Go, keeping them up to date should be you first choice.
> 
> In case you cannot upgrade, here are several options:
> 
> * You can add the server's CA to [the client config](https://www.elastic.co/guide/en/elasticsearch/client/go-api/current/connecting.html#verifying-with-ca).
> * You can pin the fingerprint of [the server's certificate](https://www.elastic.co/guide/en/elasticsearch/client/go-api/current/connecting.html#verifying-with-fingerprint).
> 
> Ultimately you can set `InsecureSkipVerify` to `true` in the `tls.Config` for the transport, that should be you last resort.

resolved,`InsecureSkipVerify` is ok
