### ISSUE TITLE
Unstructured multisearch response

### ISSUE THREAD

**Issue by xlucas** [elastic/go-elasticsearch#766]
When calling the multisearch API I was expecting the result to be structured and be able to cast individual response items to `MultiSearchItem`.

Instead I'm getting a raw map for each. I believe the top-level `Response` type for that endpoint is missing an unmarshal helper to parse the response body: https://github.com/elastic/go-elasticsearch/blob/19b7047994ef03b78c0a8bc18c5c509dee188d3d/typedapi/core/msearch/response.go.

**Comment by Anaethelion** [comment]
Fixed in the aforementioned PR, this will be part of the next release!
