### ISSUE TITLE
The Delete By Query "slices" field cannot be set to "auto"

### ISSUE THREAD

**Issue by rliebz** [elastic/go-elasticsearch#77]
Based on [the Delete By Query API documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html#docs-delete-by-query-picking-slices), the `slices` field may be set to `auto`.

The `DeleteByQueryRequest` struct [only allows `*int` as input](https://github.com/elastic/go-elasticsearch/blob/ea052088db25bb87db9ce22b8191a5205665ee99/esapi/api.delete_by_query.go#L60), as does the `DeleteByQuery` method, so there does not currently appear to be a way to set that value using this library.

**Comment by karmi** [comment]
Hi, it seems like the [REST API specification](https://github.com/elastic/elasticsearch/blob/5508aba42b376951b0c036335e172c1bedf71f2f/rest-api-spec/src/main/resources/rest-api-spec/api/delete_by_query.json#L153-L154) for this API lists the parameter as `number`, and that's being picked up by the generator. It's worth opening an issue against the specification...

**Comment by karmi** [comment]
Hi @rliebz, it looks like the spec hasn't been updated yet. I'll have a look into that.

**Comment by Ice3man543** [comment]
Hey @karmi, any updates on this issue? I also came across this issue in my use case. This seems like a much needed fix.

**Comment by karmi** [comment]
Hi, sorry, not news yet — I'll prioritize it for the next month.

**Comment by karmi** [comment]
Hello, this has been fixed in the REST API specification, and the field is takes "polymorphic" values on master:

https://github.com/elastic/go-elasticsearch/blob/aff00e5adfde9994ddeb2619ecb7b2131071c338/esapi/api.delete_by_query.go#L65

I'll have a look into backporting this into 7.x.

**Comment by daidi** [comment]
rely on this cofig too ,  in version 6.x

**Comment by technige** [comment]
Closing as this has now been fixed.
