### ISSUE TITLE
IAM roles support

### ISSUE THREAD

**Issue by alimoeeny** [elastic/go-elasticsearch#78]
Are there any plans to support AWS IAM roles / credentials , as means of authentication?

**Comment by karmi** [comment]
Hi, based on my experience with other language clients, implementing eg. IAM authentication is usually done on the client side, by configuring or replacing the HTTP transport. I imagine a package like https://docs.aws.amazon.com/sdk-for-go/api/aws/signer/v4/ can be used to manipulate the requests. (See the [`_examples`](https://github.com/elastic/go-elasticsearch/tree/master/_examples) folder for examples of configuration and customization of the transport.)

**Comment by karmi** [comment]
Hi, returning to the discussion, is it OK to close the issue?

**Comment by alimoeeny** [comment]
Hi @karmi  sorry I didn’t reply sooner, wanted to investigate more but didn’t get a chance, will close

**Comment by jriquelme** [comment]
if someone needs a concrete example using the AWS GO SDK v2: https://gist.github.com/jriquelme/d11e0bb2e4523523a4ee507282ba6184

**Comment by adreasnow** [comment]
for anyone who stumbles upon this like I did, the snippet provided is missing one crucial step, the conversion from `aws.CredentialsProvider` to `*credentials.Credentials` as needed by v4.NewSigner()

Here is the missing snippet:
```go
func (s *V4Signer) RoundTrip(req *http.Request) (*http.Response, error) {

	creds, err := credentials.NewCredentialsCache(s.Credentials)
	if err != nil {
		fmt.Println("Error creating credentials cache:", err)
		return &http.Response{}, err
	}

	signer := v4.NewSigner(creds)
...
```

You'll also need to `go get github.com/aws/aws-sdk-go-v2/aws/credentials`
