### ISSUE TITLE
Elasticsearch new template version support

### ISSUE THREAD

**Issue by ps-rterzman** [elastic/go-elasticsearch#780]
Hello,
I am trying to use the latest version of go-elasticsearch to apply new verson of ES template:
`{
  "index_patterns": [
    "client-products_*"
  ],
  "version": 1,
  "template": {
    "settings": {
      "index": {
        "number_of_shards": "15",
        "number_of_replicas": "1",
        "refresh_interval": "5s",
        "max_ngram_diff": "10"
      },
}`

Elasticsearch returns an error:
`2023/12/27 18:23:13 Put elastic serach template path [templates/client-product_template.json]
2023/12/27 18:23:13 [400 Bad Request] {"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400}`

Is there any way to apply new version of template?

**Comment by Anaethelion** [comment]
Hi @ps-rterzman could you share a snippet of code to highlight how you are trying to use the client to achieve that ?

**Comment by Anaethelion** [comment]
Closing this without response.
