### ISSUE TITLE
Connect to Elasticsearch from AWS

### ISSUE THREAD

**Issue by Zakisu** [elastic/go-elasticsearch#782]
I use Elasticsearch from AWS, which operates on port 443 (default is 9200). When I try to connect, it always returns the error: 'The client noticed that the server is not Elasticsearch, and we do not support this unknown product.

When I trace the error message, it comes from this function:
/go-elasticsearch-main/elasticsearch.go
```
func genuineCheckHeader(header http.Header) error {
    if header.Get("X-Elastic-Product") != "Elasticsearch" {
        return errors.New(unknownProduct)
    }
    return nil
}
```
how to solve this?

**Comment by srri** [comment]
You are either using a newer client against an older version of Elasticsearch on AWS (eg: version 8 client against version 7 ES), or you're trying to connect to an OpenSearch cluster in AWS (which is not the same as Elasticsearch).

**Comment by Zakisu** [comment]
> You are either using a newer client against an older version of Elasticsearch on AWS (eg: version 8 client against version 7 ES), or you're trying to connect to an OpenSearch cluster in AWS (which is not the same as Elasticsearch).

Works! Thanks! previously i used python and works in ES library, so i tried use this lib in Golang

**Comment by Anaethelion** [comment]
Thank you @srri for the right answer, closing this issue.
