### ISSUE TITLE
Is it safe to use multiple BulkIndexers concurrently?

### ISSUE THREAD

**Issue by Jakub-Kapusta** [elastic/go-elasticsearch#795]
For example: I want to index multiple documents (with different index names) concurrently.

This would require creating multiple [Bulkindexers](https://github.com/elastic/go-elasticsearch/blob/a58e89f1ecc47a94db81a93c13935e8da3b8438b/esutil/bulk_indexer.go#L280), however, I was unable to find concurrency-safety related information about this.

**Comment by Jakub-Kapusta** [comment]
Correction: It seems that the index name can be specified for each [BulkIndexerItem](https://github.com/elastic/go-elasticsearch/blob/a58e89f1ecc47a94db81a93c13935e8da3b8438b/esutil/bulk_indexer.go#L101), So multiple BulkIndexers are not required for handling multiple index names.

However, I would still like to ask if Multiple BulkIndexers can be run concurrently.

**Comment by Anaethelion** [comment]
Hi @Jakub-Kapusta 

Yes you can. However I would advise against that if your use case is using only one cluster and multiple indices.
I would recommend to use use the metadata to route your data properly and tuning the indexer accordingly.
If you still want to use multiple BulkIndexers I'd be very cautious with retry and backoff functions to avoid pushing the cluster too hard.
