### ISSUE TITLE
Aggregation alias (`aggs`) is not handled in generated Go code

### ISSUE THREAD

**Issue by mieciu** [elastic/go-elasticsearch#800]
I'm doing pretty basic thing when parsing ES's search request:
```go
	esRequest := search.Request{}
	if json.Unmarshal(body, &esRequest) != nil {
		return nil, errors.New("Failed to unmarshal request body")
	}
```
And I've noticed that the `Request` struct doesn't respect the `aggs` alias, even though is is present in the [source spec](https://github.com/elastic/elasticsearch-specification/blob/e16324dcde9297dd1149c1ef3d6d58afe272e646/specification/_global/search/SearchRequest.ts#L332). 

Therefore, my request cannot be deserialized properly and the aggregations are empty whenever request uses `aggs` alias.

For some reason though, this alias is handled in Aggregations type (ref: [aggregations.go#L309](https://github.com/elastic/go-elasticsearch/blob/main/typedapi/types/aggregations.go#L309)), so I'd suspect it's something wrong with the code generation for that specific `Request` struct?

**Comment by Anaethelion** [comment]
Hi @mieciu 

Thank you for reporting this.
The request deserialization was not generated until now, since it doesn't break the API I've regenerated it and added that to the `8.12` branch.
Could you test the changes in the branch and let me know if that works for you ?

Thank you!

**Comment by mieciu** [comment]
I can confirm this works on `8.12` branch (but still not on `latest` though):
```
go get github.com/elastic/go-elasticsearch/v8@8.12  

go: downloading github.com/elastic/go-elasticsearch/v8 v8.12.1-0.20240215175737-98e908d60274
go: upgraded github.com/elastic/go-elasticsearch/v8 v8.12.0 => v8.12.1-0.20240215175737-98e908d60274
```

Thanks for a quick response!

**Comment by Anaethelion** [comment]
Thank you for the feedback, I'll regenerate all the APIs and this will be part of the next patch release.
