### ISSUE TITLE
why the SearchRequest  don't support Document Type

### ISSUE THREAD

**Issue by chazex** [elastic/go-elasticsearch#82]
hi, all
Does the SearchRequest  not support Document Type?
es support it.
GET /twitter/tweet,user/_search?q=user:kimchy

source code in api.search.go 
i can't set the type.

path.Grow(1 + len(strings.Join(r.Index, ",")) + 1 + len("_search"))
	if len(r.Index) > 0 {
		path.WriteString("/")
		path.WriteString(strings.Join(r.Index, ","))
	}
	path.WriteString("/")
	path.WriteString("_search")

**Comment by philkra** [comment]
Hi @hchaze, what version of Elasticsearch are you using? Because _customer_ mapping types were  with Elasticsearch `v7.0.0`. Please refer to this [link](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html) for more informations.

**Comment by hchaze** [comment]
@philkra, the version of Elasticsearch is 6.3.2.   i got it ,thanks.
