### ISSUE TITLE
Reset方法不存在

### ISSUE THREAD

**Issue by heqishengcai** [elastic/go-elasticsearch#823]
github.com/elastic/elastic-transport-go/v8 v8.3.0
	github.com/elastic/go-elasticsearch/v8 v8.11.0

package esutil 的 flush 方法，其中 Reset方法不存在。

w.ticker.Reset(w.bi.config.FlushInterval)

**Comment by Anaethelion** [comment]
Closing as this has been solved since `8.12.0`.
