### ISSUE TITLE
typedapi.core.search.Request does not have filter_path

### ISSUE THREAD

**Issue by rajivprab** [elastic/go-elasticsearch#826]
This is almost identical to the issue #93 . The only difference is that I'm trying to specify filter_path on a typedapi search-request. 

I've already double-checked both of the following places:
- [typedapi::Search](https://github.com/elastic/go-elasticsearch/blob/main/typedapi/core/search/search.go)
- [typedapi::search.Request](https://github.com/elastic/go-elasticsearch/blob/main/typedapi/core/search/request.go)

But I don't see `filter_path` in either of the above.

I do see filter_path in [esapi::SearchRequest](https://github.com/elastic/go-elasticsearch/blob/c4f3d4024478148d9eb64187de167de7c45b9669/esapi/api.search.go#L90). But our project is using the typedapi client, hence why we're using `typedapi::Search` and `typedapi::search.Request`

**Comment by Anaethelion** [comment]
We're indeed missing some query parameters from within an expansion phase in the https://github.com/elastic/elasticsearch-specification
I'll have a look and will regenerate the API when this is fixed.

**Comment by rajivprab** [comment]
Thanks @Anaethelion . Do you have a ballpark estimate of when this will be fixed? Ie, will this be a few weeks, months, year?

**Comment by Anaethelion** [comment]
Hi @rajivprab this should be available in the [latest release](https://github.com/elastic/go-elasticsearch/releases/tag/v8.14.0)!
