### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by geoffmore** [elastic/go-elasticsearch#83]
I have a set of patches that I'd like to see in the 7.x branch of the package. What is the process for getting new code into a specific branch? Is it ported from 7.x to master or does it go from master to 7.x?

**Comment by karmi** [comment]
Hi @geoffmore , sorry for a delayed response. The workflow being used is to work inside `master`, and then backport into `7.x` and `6.x` branches (there's a Make target for that). Note that the `esapi` package is an exception, since the API is generated from the specification, not written manually.
