### ISSUE TITLE
How do you multi search?

### ISSUE THREAD

**Issue by aniskhan001** [elastic/go-elasticsearch#85]
I'm working on a task where I need to get a set of result in JSON from 3 different indices.
So, I was thinking of using the [Elastic Multi Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html) API. 
How do I use muti search with this client? Guides or suggestions would be very helpful.
Thanks!

**Comment by karmi** [comment]
Hi @aniskhan001 , the link provided by @geoffmore is indeed what you need. Please re-open if you'd run into issues.

**Comment by Buckley404** [comment]
@karmi That link wasn't much help I'm afraid. A simpler answer would be to implement the following:

```
	var buf bytes.Buffer

	match := []interface{}{
		map[string]interface{}{"match": map[string]string{"podcast_url": podcast_url}},
		map[string]interface{}{"match": map[string]string{"text_value": word}},
	}

	query := map[string]interface{}{
		"query": map[string]interface{}{
			"bool": map[string]interface{}{
		  		"must": match,
				},
			},
		}

	if err := json.NewEncoder(&buf).Encode(query); err != nil {
		log.Fatalf("Error encoding query: %s", err)
  	}
```
I think it would be a good idea to update your examples to include this multi search logic as it's not very clear at all, and took me a good bit of trial and error to figure out. (There is literally no documentation out there which shows how this works).

**Comment by karmi** [comment]
In general, the client accepts the search definition or other payload as an `io.Reader`, which is what you need to pass to the `Msearch()` function — that should correspond exactly to what you find eg. in the [documentation on the elastic.co website](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html).

Note that to facilitate encoding custom structures or `map[string]interface{}` types, the package provides the `esutil.JSONReader` helper:

https://github.com/elastic/go-elasticsearch/blob/e9eb76d55d12256a0777ad825bf25cd5e02fa105/_examples/encoding/jsonreader.go#L30-L34

**Comment by codecandy2015** [comment]
I am able to get Multi search results directly from the Elastic Search API using _msearch for the following request Body

`
{"index":"csv1"}
{"query" : {"match" :  {"_meta._clusterID": "8811547417"} }, "size" : 1} 

{"index":"csv1"}
{"query" : {"match" :  {"_meta._clusterID": "88115479144"} }, "size" : 1}

{"index":"csv2"}
{"query" : {"match" :  {"_meta._clusterID": "86443104548"} }, "size" : 1}

{"index":"csv3"}
{"query" : {"match" :  {"_meta._clusterID": "86642503112"} }, "size" : 1}`

However, the above suggestions are very difficult to understand how to use the go-elasticsearch API for Msearch.  What should the MsearchRequest look like , I tried using the JSON option, It always complains an error. 

If someone did use this API, any examples would be highly appreciated.
