### ISSUE TITLE
The issue of automatic message retry 

### ISSUE THREAD

**Issue by wd-h2** [elastic/go-elasticsearch#859]
`err := consumerClient.Subscribe(mounter.topic, consumer.MessageSelector{}, func(ctx context.Context, msgs ...*primitive.MessageExt) (consumer.ConsumeResult, error) {
		err := mounter.logic.Execute(msgs)
		if err != nil {
			c.svcCtx.Log.Sugar().Errorf("cosumer_topic_msg:%s:err:%s", mounter.topic, err.Error())
	
			return consumer.ConsumeRetryLater, nil
		}

		return consumer.ConsumeSuccess, nil
	})
	if err != nil {
		return
	}`

 consumer.ConsumeRetryLater  ：No automatic retry, is there a solution ?

**Comment by Anaethelion** [comment]
Hello there,

I think you have the wrong library, nothing in the code above fits this repository.

Closing now.
