### ISSUE TITLE
Certificate signed by Unknown authority

### ISSUE THREAD

**Issue by intellectape** [elastic/go-elasticsearch#86]
I am trying to connect to my elastic search instance on the cloud with following Configurations:
```
config := elasticsearch.Config{
		Addresses: []string{
			"https://<address>",
		},
		Username: "<username>",
		Password: "<password>",
		Transport: &http.Transport{
			MaxIdleConnsPerHost:   10,
			ResponseHeaderTimeout: time.Second,
			DialContext:           (&net.Dialer{Timeout: time.Second}).DialContext,
			TLSClientConfig: &tls.Config{
				MinVersion: tls.VersionTLS11,
			},
		},
	}
	es, err := elasticsearch.NewClient(config)
```

Now, although I don't issue at the line: `es, err := elasticsearch.NewClient(config)` but when I try to do `es.Info()`, I get the following error:
`x509: certificate signed by unknown authority`

I know that I would need to include the CA certificate, but I am not able to find where that is required to be included. If this is not the solution, what can be the solution to this issue I am seeing while trying to use the ElasticSearch Client?

**Comment by karmi** [comment]
Hello, first, what kind of "cloud" are you referring to?

**Comment by intellectape** [comment]
I was referring to IBM cloud, but I figured the issue out. I was not passing the right certificates. This solved my issue:

```
insecure := flag.Bool("insecure-ssl", false, "Accept/Ignore all server SSL certificates")
	flag.Parse()

	// Get the SystemCertPool, continue with an empty pool on error
	rootCAs, _ := x509.SystemCertPool()
	if rootCAs == nil {
		rootCAs = x509.NewCertPool()
	}

	// Read in the cert file
	certs, err := ioutil.ReadFile(<cert-file-name>)
	if err != nil {
		log.Fatalf("Failed to append %q to RootCAs: %v", localCertFile, err)
	}

	// Append our cert to the system pool
	if ok := rootCAs.AppendCertsFromPEM(certs); !ok {
		log.Println("No certs appended, using system certs only")
	}

	config := elasticsearch.Config{
		Addresses: []string{
			ESConfig.URL,
		},
		Username: ESConfig.User,
		Password: ESConfig.Pass,
		Transport: &http.Transport{
			MaxIdleConnsPerHost:   10,
			ResponseHeaderTimeout: time.Second,
			DialContext:           (&net.Dialer{
				Timeout: 30 * time.Second,
				KeepAlive: 30 * time.Second,
				}).DialContext,
			TLSClientConfig: &tls.Config{
				InsecureSkipVerify: *insecure,
				RootCAs: rootCAs,
	},
		},
	}
```

For self-signed certificates, we need to use the above steps to connect to the ES instance. If there is any better way to do it?

**Comment by karmi** [comment]
I'm afraid that with self-signed certificates, you have to indeed set the `InsecureSkipVerify` to true... I guess it's more of a question for the cloud provider, since I assume they control the domains and certificates. (For what it's worth, SSL works out of the box on Elastic Cloud.)
