### ISSUE TITLE
go-elasticsearch using immense amount of resources.

### ISSUE THREAD

**Issue by ZainJavedDev** [elastic/go-elasticsearch#865]
Elastic Version: v8
OS: Ubuntu 22.04

Installed elasticsearch for the first time and just creating a client consumes all of my CPU cores and lots of memory before crashing the system. 
Never experienced this with any other service before.

Here is my go code:
```
package main

import (
	elasticsearch8 "github.com/elastic/go-elasticsearch/v8"
)

func main() {
	_, _ = elasticsearch8.NewDefaultClient()

}

```

Screenshot of system monitor:
![IMG_20240531_112757~2](https://github.com/elastic/go-elasticsearch/assets/33459428/a3b3a82c-866c-423f-a611-27fee40e745a)

```[tasklist]
### Tasks
```

**Comment by Anaethelion** [comment]
Hi @ZainJavedDev 

The package holds the entire API for Elasticsearch, which is quite large. What you experience is the initial cache build which is then used to link the executable.

Can you share a bit more about the resources of your machine, number of cores and amount of ram, and which version of Go you are currently using ?

**Comment by ZainJavedDev** [comment]
@Anaethelion I have a core i7 6th gen with 8GB ram. I am using go 1.21

Not sure why this cache build is crashing my system.

**Comment by Anaethelion** [comment]
Its unclear to me why it is crashing your system. You can try building with these arguments:
`go build -p=1 '-gcflags=all="-c=1"'`

This should contain the compiler quite a bit at the cost of time for the initial compilation.

**Comment by ZainJavedDev** [comment]
I will test with python so we could know if the issue is with this package or with elasticsearch itself.

**Comment by Anaethelion** [comment]
Closing this, the issue doesn't seem related to the client.
Please open a new issue or ping me if you find evidence of the contrary!
