### ISSUE TITLE
Search_After functionality

### ISSUE THREAD

**Issue by Lupanoide** [elastic/go-elasticsearch#87]
I sought in https://github.com/elastic/go-elasticsearch/blob/7.x/esapi/api.search.go for search_after functionality but i didn't find it. I could achieve it? Thanks

**Comment by karmi** [comment]
Hello, `search_after` is part of the request body, so you have to supply it to the Search method. There's a working example available in the `_examples` folder:

https://github.com/elastic/go-elasticsearch/blob/7540ece56511ee0e5ed9f1a4f64fecdadb90a9fb/_examples/xkcdsearch/store.go#L192

**Comment by Lupanoide** [comment]
Super! thanks a lot
