### ISSUE TITLE
incorrect documentation in README for installing github.com/elastic/go-elasticsearch/v8@master

### ISSUE THREAD

**Issue by julieqiu** [elastic/go-elasticsearch#88]
The README suggests adding the following to the go.mod file during installation:

```
require github.com/elastic/go-elasticsearch/v8 master
```

However, doing do will result in the following error:

```
go.mod|8| require github.com/elastic/go-elasticsearch/v8: version "master" invalid: must be of the form v1.2.3
```

Instead you should run `go get github.com/elastic/go-elasticsearch/v8`

It also seems the latest stable version if v7.3.0, so should we be fetching `github.com/elastic/go-elasticsearch/v7` instead?

**Comment by julieqiu** [comment]
It seems that the error:
```
go.mod|8| require github.com/elastic/go-elasticsearch/v8: version "master" invalid: must be of the form v1.2.3
```
is actually an issue with my editor.

However, the product page refers to v7.3.2 as the latest stable version, so it might be useful for the README to reference that client version as well.
![image](https://user-images.githubusercontent.com/5943521/65277866-d9109d00-daf8-11e9-96cc-1de964ad41c1.png)

**Comment by karmi** [comment]
Hello, I’m currently on a vacation, will have a proper look when I’m back.

One thing to note is that the README on the master branch intentionally lists v8/master, since that particular branch follows the Elasticsearch master.

The 7.x and 6.x have a different version in README, since they target corresponding versions of Elasticsearch.

**Comment by karmi** [comment]
Hi, returning to this issue. The _Compatibility_ part of the README says clearly, to my eyes, that you have to use a major version of the client corresponding to the major version of Elasticsearch. I'm not sure if I can make the text any more clear... I'll close the issue if it's OK — please re-open or open a new one if you run into issues.
