### ISSUE TITLE
SearchRequest struct does not have documented FilterPath field

### ISSUE THREAD

**Issue by geoffmore** [elastic/go-elasticsearch#93]
Recently, I tried adding the [filter_path](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#common-options-response-filtering) parameter to a esapi.SearchRequest https://github.com/elastic/go-elasticsearch/blob/bbddf24d4973e9e92080bd27f77b50e635a1c0f6/esapi/api.search.go#L35

Since I did not see a FilterPath field within the struct, I tried unsuccessfully to add this option to the Query field of the struct. Digging in to the code, I found this option available https://github.com/elastic/go-elasticsearch/blob/bbddf24d4973e9e92080bd27f77b50e635a1c0f6/esapi/api.search.go#L294

Adding to field to the struct allows the search to execute as intended, even without the field being explicitly defined in the struct.

I think this is a bug and that the FilterPath field should be added to the SearchRequest struct to reflect the already available functionality exposed to users.

**Comment by karmi** [comment]
Hey, thanks for catching it! The `filter_path` is not defined in the specification of the Search API, but in the [list of common options](https://github.com/elastic/elasticsearch/blob/f966fa1188ecd02a9917ca8bf72d33a1f2191207/rest-api-spec/src/main/resources/rest-api-spec/api/_common.json#L26), and the generator skipped that. I'll look into fixing it!

**Comment by geoffmore** [comment]
Out of curiosity, how are you generating this code? I may be able to tackle this issue if I better understand the generation process.

**Comment by karmi** [comment]
Wait, I was wrong, this parameter is correctly picked up by the generator. What version of the package are you using? Can you run the following script, since that correctly handles the parameter?

```golang
//+build ignore

package main

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/elastic/go-elasticsearch/v8"
	"github.com/elastic/go-elasticsearch/v8/esapi"
	"github.com/elastic/go-elasticsearch/v8/estransport"
)

func main() {
	cfg := elasticsearch.Config{
		Logger: &estransport.ColorLogger{
			Output:             os.Stdout,
			EnableRequestBody:  true,
			EnableResponseBody: true,
		},
	}
	es, _ := elasticsearch.NewClient(cfg)

	fmt.Println("go-elasticsearch", elasticsearch.Version)
	fmt.Println(strings.Repeat("-", 80))

	fmt.Println(`es.Search(es.Search.WithFilterPath("took"))`)
	es.Search(es.Search.WithFilterPath("took", "timed_out"))

	fmt.Println(`esapi.SearchRequest{FilterPath: "took"}`)
	req := esapi.SearchRequest{FilterPath: []string{"took", "timed_out"}}
	req.Do(context.Background(), es)
}
```

Output:

```
go-elasticsearch 8.0.0-SNAPSHOT
--------------------------------------------------------------------------------
es.Search(es.Search.WithFilterPath("took"))
   GET http://localhost:9200/_search?filter_path=took,timed_out 200 OK 68ms
       « {"took":19,"timed_out":false}
────────────────────────────────────────────────────────────────────────────────
esapi.SearchRequest{FilterPath: "took"}
   GET http://localhost:9200/_search?filter_path=took,timed_out 200 OK 24ms
       « {"took":13,"timed_out":false}
────────────────────────────────────────────────────────────────────────────────
```

**Comment by geoffmore** [comment]
go-elasticsearch 7.3.0
--------------------------------------------------------------------------------
esClient.Search(es.Search.WithFilterPath("took"))
   GET <cloud-instance-path>/_search?filter_path=took,time
d_out 200 OK 2.069s
       « {"took":1767,"timed_out":false}
────────────────────────────────────────────────────────────────────────────────
esapi.SearchRequest{FilterPath: "took"}
   GET <cloud-instance-path>/_search?filter_path=took,timed_out 200 OK 31ms
       « {"took":13,"timed_out":false}
────────────────────────────────────────────────────────────────────────────────

**Comment by karmi** [comment]
Looks like the package then behaves as expected, or?

**Comment by geoffmore** [comment]
The package behaves as expected, but the SearchRequest struct doesn't have a FilterPath field

**Comment by karmi** [comment]
@geoffmore , maybe I still don't understand, but I do see it there:

https://github.com/elastic/go-elasticsearch/blob/c4f3d4024478148d9eb64187de167de7c45b9669/esapi/api.search.go#L90

**Comment by geoffmore** [comment]
You're right. I must have missed it since it was very close to the bottom of the struct and I was expecting it elsewhere. This is definitely not a bug, but rather user error. I appreciate the help!

**Comment by karmi** [comment]
All right, closing the ticket then!
